Ast\Domain\Model\Musiconhold\Musiconhold:
  repositoryClass: Ast\Infrastructure\Persistence\Doctrine\MusiconholdDoctrineRepository
  type: entity
  table: ast_musiconhold
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
