Ast\Model\Musiconhold\Musiconhold:
  repositoryClass: Ast\Infrastructure\Persistence\Doctrine\MusiconholdDoctrineRepository
  type: entity
  table: ast_musiconhold
  uniqueConstraints:
    name:
      columns:
        - name
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 80
      options:
        fixed: false
    mode:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
    directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    application:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    digit:
      type: string
      nullable: true
      length: 1
      options:
        fixed: false
    sort:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
    format:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
    stamp:
      type: datetime
      nullable: true
  lifecycleCallbacks: {  }
