Ast\Domain\Model\PsEndpoint\PsEndpointAbstract:
  type: mappedSuperclass
  indexes:
    terminalId:
      columns:
        - terminalId
    friendId:
      columns:
        - friendId
    sorcery_idx:
      columns:
        - sorcery_id
  uniqueConstraints:
    id:
      columns:
        - id
  fields:
    sorceryId:
      type: string
      nullable: false
      length: 40
      options:
        fixed: false
      column: sorcery_id
    fromDomain:
      type: string
      nullable: true
      length: 190
      options:
        fixed: false
      column: from_domain
    aors:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
    callerid:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    context:
      type: string
      nullable: false
      length: 40
      options:
        fixed: false
        default: users
    disallow:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
        default: all
    allow:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
        default: all
    directMedia:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: 'yes'
      column: direct_media
    directMediaMethod:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        comment: '[enum:update|invite|reinvite]'
        default: update
      column: direct_media_method
    mailboxes:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    pickupGroup:
      type: string
      nullable: true
      length: 40
      options:
        fixed: false
      column: pickup_group
    sendDiversion:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: 'yes'
      column: send_diversion
    sendPai:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: 'yes'
      column: send_pai
    subscribecontext:
      type: string
      nullable: false
      length: 40
      options:
        fixed: false
        default: default
    oneHundredRel:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        default: 'no'
      column: 100rel
    outboundProxy:
      type: string
      nullable: true
      length: 256
      options:
        fixed: false
      column: outbound_proxy
    trustIdInbound:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
      column: trust_id_inbound
  manyToOne:
    terminal:
      targetEntity: \Core\Domain\Model\Terminal\TerminalInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        terminalId:
          referencedColumnName: id
      orphanRemoval: false
    friend:
      targetEntity: \Core\Domain\Model\Friend\FriendInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        friendId:
          referencedColumnName: id
      orphanRemoval: false
    retailAccount:
      targetEntity: \Core\Domain\Model\RetailAccount\RetailAccountInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        retailAccountId:
          referencedColumnName: id
      orphanRemoval: false
