Ast\Domain\Model\Queue\Queue:
  repositoryClass: Ast\Infrastructure\Persistence\Doctrine\QueueDoctrineRepository
  type: entity
  table: ast_queues
  id:
    name:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
      id: true
      generator:
        strategy: NONE
  lifecycleCallbacks: {  }
