Ast\Domain\Model\Voicemail\Voicemail:
  repositoryClass: Ast\Infrastructure\Persistence\Doctrine\VoicemailDoctrineRepository
  type: entity
  table: ast_voicemail
  id:
    uniqueid:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
