<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Model\AstMusiconhold\AstMusiconholdRepository;

/**
 * AstMusiconholdDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstMusiconholdDoctrineRepository extends EntityRepository implements AstMusiconholdRepository
{
}
