<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Model\AstPsAor\AstPsAorRepository;

/**
 * AstPsAorDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstPsAorDoctrineRepository extends EntityRepository implements AstPsAorRepository
{
}
