<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Model\AstQueueMember\AstQueueMemberRepository;

/**
 * AstQueueMemberDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstQueueMemberDoctrineRepository extends EntityRepository implements AstQueueMemberRepository
{
}
