<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Model\AstQueue\AstQueueRepository;

/**
 * AstQueueDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstQueueDoctrineRepository extends EntityRepository implements AstQueueRepository
{
}
