<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Model\Musiconhold\MusiconholdRepository;

/**
 * MusiconholdDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusiconholdDoctrineRepository extends EntityRepository implements MusiconholdRepository
{
}
