<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Model\PsAor\PsAorRepository;

/**
 * PsAorDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsAorDoctrineRepository extends EntityRepository implements PsAorRepository
{
}
