<?php

namespace Ast\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ast\Domain\Model\PsEndpoint\PsEndpointRepository;

/**
 * PsEndpointDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsEndpointDoctrineRepository extends EntityRepository implements PsEndpointRepository
{
}
