#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include AstQueueMembersList.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: astQueuesList_screen
  screens: &astQueues_screensLink
    astQueuesList_screen: &astQueuesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *AstQueues
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Queue', 'Queues', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields: &astQueues_fieldsLink
        options:
          title: _("Options")
          screens:
            astQueuesEdit_screen: true
            astQueueMembersList_screen: true
          dialogs:
            astQueuesDel_dialog: true
          default: astQueuesEdit_screen
        blacklist:
          name: true
      options:
        title: _("Options")
        screens:
          astQueuesNew_screen: true
        dialogs:
          astQueuesDel_dialog: true
    astQueuesNew_screen: &astQueuesNew_screenLink
      <<: *AstQueues
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Queue', 'Queues', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          name: true
      shortcutOption: N
      postActionOptions:
        screens:
          astQueuesEdit_screen: true
    astQueuesEdit_screen: &astQueuesEdit_screenLink
      <<: *AstQueues
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Queue', 'Queues', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Queue', 'Queues', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          name: true
    #astQueueMembers:
    <<: *astQueueMembers_screensLink
    astQueueMembersList_screen:
      <<: *astQueueMembersList_screenLink
      filterField: Queue
      parentOptionCustomizer:
        - recordCount
    astQueueMembersNew_screen:
      <<: *astQueueMembersNew_screenLink
      filterField: Queue
    astQueueMembersEdit_screen:
      <<: *astQueueMembersEdit_screenLink
      filterField: Queue

  dialogs: &astQueues_dialogsLink
    astQueuesDel_dialog: &astQueuesDel_dialogLink
      <<: *AstQueues
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Queue', 'Queues', 1))
      description: _("Do you want to delete this %s?", ngettext('Queue', 'Queues', 1))
      message: _("%s successfully deleted.", ngettext('Queue', 'Queues', 1))
      multiItem: 1
      labelOnList: 1
  # astQueueMembers dialogs:
    <<: *astQueueMembers_dialogsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
