#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: dDIsList_screen
  screens: &dDIs_screenLink
    dDIsList_screen: &dDIsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *DDIs
      title: _("List of %s %2s", ngettext('DDI', 'DDIs', 0), "[format| (%parent%)]")
      class: ui-silk-lightning-go
      forcedValues:
        <<: *forcedBrand
      order:
        field:
          - DDI.ddi asc
          - DDI.routeType desc
      fields:
        order: &dDIsFieldsOder_Link
          company: true
          country: true
          DDI: true
          externalCallFilter: true
          routeType: true
          target: true
        blacklist:
          user: true
          fax: true
          IVRCommon: true
          IVRCustom: true
          huntGroup: true
          ddie164: true
          brand: true
          conferenceRoom: true
          recordCalls: true
          billInboundCalls: true
          friendValue: true
          queue: true
      fixedPositions: &dDIsFixedPositions_Link
        group0:
          label: _("Number data")
          colsPerRow: 3
          fields:
            country: 1
            DDI: 1
            peeringContract: 1
        group1:
          label: _("Filters data")
          colsPerRow: 2
          fields:
            externalCallFilter: 2
        group2:
          label: _("Routing data")
          colsPerRow: 3
          fields:
            routeType: 1 
            user: 1
            fax: 1
            IVRCommon: 1
            IVRCustom: 1
            huntGroup: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
