#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include CallACLRelPatternsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: callACLList_screen
  screens: &callACL_screensLink
    callACLList_screen: &callACLList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *CallACL
      class: ui-silk-lock
      title: _("List of %s %2s", ngettext('Call ACL', 'Call ACLs', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            callACLEdit_screen: true
          dialogs:
            callACLDel_dialog: true
          default: callACLEdit_screen
        blacklist:
          CallACLRelPatterns: true
      options:
        title: _("Options")
        screens:
          callACLNew_screen: true
        dialogs:
          callACLDel_dialog: true
    callACLNew_screen: &callACLNew_screenLink
      <<: *CallACL
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s %2s", ngettext('Call ACL', 'Call ACLs', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          CallACLRelPatterns: true
    callACLEdit_screen: &callACLEdit_screenLink
      <<: *CallACL
      controller: edit
      class: ui-silk-pencil
      label: false
      forcedValues: 
        <<: *forcedCompany
      title: _("Edit %s %2s", ngettext('Call ACL', 'Call ACLs', 1), "[format| (%item%)]")
      fields:
        order:
          name: true
          defaultPolicy: true
          CallACLRelPatterns: true
      fixedPositions:
        group0:
          label: _("ACL data")
          colsPerRow: 3
          fields:
            name: 2
            defaultPolicy: 1
        group1:
          label: _("Patterns")
          colsPerRow: 3
          fields:
            CallACLRelPatterns: 3
    # CallACLRelPatterns
    <<: *callACLRelPatterns_screensLink
    callACLRelPatternsList_screen:
      <<: *callACLRelPatternsList_screenLink
      title: _("List of %s %2s", ngettext('Call ACL Rel rel pattern', 'Call ACL Rel rel pattern', 0), "[format| (%parent%)]")
      filterField: CallACL
      parentOptionCustomizer:
        - recordCount
    callACLRelPatternsNew_screen:
      <<: *callACLRelPatternsNew_screenLink
      title: _("Add pattern to %2s", "[format| %parent%]")
      filterField: CallACL
    callACLRelPatternsEdit_screen:
      <<: *callACLRelPatternsEdit_screenLink
      filterField: CallACL
      title: _("Edit pattern of %s", ngettext('Call ACL Rel rel pattern', 'Call ACL Rel rel pattern', 1))

  dialogs: &callACL_dialogsLink
    callACLDel_dialog: &callACLDel_dialogLink
      <<: *CallACL
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Call ACL', 'Call ACLs', 1))
      description: _("Do you want to delete this %s?", ngettext('Call ACL', 'Call ACLs', 1))
      message: _("%s successfully deleted.", ngettext('Call ACL', 'Call ACLs', 1))
      multiItem: 1
      labelOnList: 1

    # CallACLRelPatterns
    <<: *callACLRelPatterns_dialogsLink
    callACLRelPatternsDel_dialog:
      <<: *callACLRelPatternsDel_dialogLink
      title: _("Delete %s", ngettext('Call ACL Rel rel pattern', 'Call ACL Rel patterns', 1))
      description: _("Do you want to delete this %s?", ngettext('Call ACL Rel rel pattern', 'Call ACL Rel rel patterns', 1))
      message: _("%s successfully deleted.", ngettext('Call ACL Rel pattern', 'Call ACL Rel patterns', 1))

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
