#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include KamTrunksDomainList.yaml
#include KamUsersDomainList.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: domainsList_screen
  screens: &domains_screensLink 
    domainsList_screen: &domainsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Domains
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Domain', 'Domains', 0), "[format| (%parent%)]")
      fields:
        options: 
          title: _("Options")
          screens: 
            domainsEdit_screen: false
            domainsView_screen: true
          dialogs: 
            domainsDel_dialog: false
          default: domainsView_screen
        order: &domains_orderLink
          domain: true
          target: true
          scope: true
          pointsTo: true
          brand: true
          company: true
          description: true
        blacklist:
          scope: true
          brand: true
          company: true
      options: 
        title: _("Options")
        screens: 
          domainsNew_screen: false
    domainsNew_screen: &domainsNew_screenLink 
      <<: *Domains
      controller: new
      class: ui-silk-add
      fields: &domains_fieldsLink 
        order:
          scope: true
          pointsTo: true
          domain: true
          description: true
        blacklist:
          company: true
          brand: true
          target: true
        readOnly:
          scope: true
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Domain', 'Domains', 1), "[format| (%parent%)]")
      shortcutOption: N
    domainsEdit_screen: &domainsEdit_screenLink 
      <<: *Domains
      controller: edit
      class: ui-silk-pencil
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      fields:
        order:
          target: true
          pointsTo: true
          domain: true
          description: true
        blacklist:
          company: true
          brand: true
          scope: true
        readOnly:
          target: true
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Domain', 'Domains', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Domain', 'Domains', 1), "[format| (%item%)]")
    domainsView_screen:
      <<: *domainsEdit_screenLink 
      class: ui-silk-eye
      disableSave: true
      labelOnPostAction: _("View %s %2s", ngettext('Domain', 'Domains', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('Domain', 'Domains', 1), "[format| (%item%)]")
    #kamTrunksDomain: 
    <<: *kamTrunksDomain_screensLink
    kamTrunksDomainList_screen: 
      <<: *kamTrunksDomainList_screenLink
      filterField: Domain
      parentOptionCustomizer: 
        - recordCount
    kamTrunksDomainNew_screen: 
      <<: *kamTrunksDomainNew_screenLink
      filterField: Domain
    kamTrunksDomainEdit_screen: 
      <<: *kamTrunksDomainEdit_screenLink
      filterField: Domain

    #kamUsersDomain: 
    kamUsersDomainList_screen: 
      <<: *kamUsersDomainList_screenLink
      filterField: Domain
      parentOptionCustomizer: 
        - recordCount
    kamUsersDomainNew_screen: 
      <<: *kamUsersDomainNew_screenLink
      filterField: Domain
    kamUsersDomainEdit_screen: 
      <<: *kamUsersDomainEdit_screenLink
      filterField: Domain

  dialogs: &domains_dialogsLink 
    domainsDel_dialog: &domainsDel_dialogLink 
      <<: *Domains
      controller: delete
      class: ui-silk-bin
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      labelOption: false
      title: _("Delete %s", ngettext('Domain', 'Domains', 1))
      description: _("Do you want to delete this %s?", ngettext('Domain', 'Domains', 1))
      message: _("%s successfully deleted.", ngettext('Domain', 'Domains', 1))
      multiItem: 1
      labelOnList: 1
  # kamTrunksDomain dialogs: 
    <<: *kamTrunksDomain_dialogsLink
  # kamUsersDomain dialogs: 
    <<: *kamUsersDomain_dialogsLink
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
