#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: genericMusicOnHoldList_screen
  screens: &genericMusicOnHold_screensLink
    genericMusicOnHoldList_screen: &genericMusicOnHoldList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *GenericMusicOnHold
      class: ui-silk-music
      title: _("List of %s %2s", ngettext('Generic music on hold', 'Generic music on hold(s)', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields: 
        options: 
          title: _("Options")
          screens: 
            genericMusicOnHoldEdit_screen: true
          dialogs: 
            genericMusicOnHoldDel_dialog: true
          default: genericMusicOnHoldEdit_screen
        order: &genericMusicOnHold_orderLink
          brand: true
          name: true
          originalFile: true
        blacklist:
          encodedFile: true
      options: 
        title: _("Options")
        screens: 
          genericMusicOnHoldNew_screen: true
        dialogs: 
          genericMusicOnHoldDel_dialog: true
    genericMusicOnHoldNew_screen: &genericMusicOnHoldNew_screenLink
      <<: *GenericMusicOnHold
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s %2s", ngettext('Generic music on hold', 'Generic music on hold(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *genericMusicOnHold_orderLink
        blacklist:
          encodedFile: true
          status: true
      fixedPositions: &musicOnHold_fixedPosLink
        group0:
          colsPerRow: 2
          fields:
            brand: 1
            name: 1
        group1:
          colsPerRow: 1
          fields:
            originalFile: 1
            encodedFile: 1
    genericMusicOnHoldEdit_screen: &genericMusicOnHoldEdit_screenLink
      <<: *GenericMusicOnHold
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Generic music on hold', 'Generic music on hold(s)', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *genericMusicOnHold_orderLink
        fixedPositions:
          <<: *musicOnHold_fixedPosLink
        blacklist:
          status: true
      fixedPositions:
        <<: *musicOnHold_fixedPosLink
  dialogs: &genericMusicOnHold_dialogsLink
    genericMusicOnHoldDel_dialog: &genericMusicOnHoldDel_dialogLink 
      <<: *GenericMusicOnHold
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Generic music on hold', 'Generic music on hold(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Generic music on hold', 'Generic music on hold(s)', 1))
      message: _("%s successfully deleted.", ngettext('Generic music on hold', 'Generic music on hold(s)', 1))
      multiItem: 1
      labelOnList: 1
      fields:
        order:
          <<: *genericMusicOnHold_orderLink
  commands: &genericMusicOnHold_commandsLink
    genericMusicOnHold_FileDownload_command: 
      <<: *GenericMusicOnHold
      controller: File
      action: force-download
      mainColumn: originalFile
    genericMusicOnHold_FileUpload_command: 
      <<: *GenericMusicOnHold
      controller: File
      action: upload
      mainColumn: originalFile
    genericMusicOnHold_FilePreview_command: 
      <<: *GenericMusicOnHold
      controller: File
      action: preview
      mainColumn: originalFile
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
