#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: huntGroupsRelUsersList_screen
  screens: &huntGroupsRelUsers_screensLink
    huntGroupsRelUsersList_screen: &huntGroupsRelUsersList_screenLink 
      controller: list
      class: ui-silk-group-go
      pagination: 
        items: 25
      <<: *HuntGroupsRelUsers
      title: _("List of %s %2s", ngettext('Hunt groups rel user', 'Hunt groups rel users', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            huntGroupsRelUsersEdit_screen: true
          dialogs: 
            huntGroupsRelUsersDel_dialog: true
          default: huntGroupsRelUsersEdit_screen
      options: 
        title: _("Options")
        screens: 
          huntGroupsRelUsersNew_screen: true
        dialogs: 
          huntGroupsRelUsersDel_dialog: true
    huntGroupsRelUsersNew_screen: &huntGroupsRelUsersNew_screenLink 
      <<: *HuntGroupsRelUsers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Hunt groups rel user', 'Hunt groups rel users', 1))
      shortcutOption: N
#      fields:
#        blacklist:
#          huntGroup: true
    huntGroupsRelUsersEdit_screen: &huntGroupsRelUsersEdit_screenLink
      <<: *HuntGroupsRelUsers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Hunt groups rel user', 'Hunt groups rel users', 1), "[format| (%parent%)]")
      fields:
        blacklist:
          huntGroup: false
        readOnly:
          huntGroup: true
          user: true
      
    #HuntGroups
#    <<: *huntGroups_screensLink
#    huntGroupsEdit_screen:
#      <<: *huntGroupsEdit_screenLink
#      class: ui-silk-group-go
#      calculatedPk:
#        class: IvozProvider_Klear_Calculated_Primarykeys
#        method: huntGroupPk
    
  dialogs: &huntGroupsRelUsers_dialogsLink
    huntGroupsRelUsersDel_dialog: &huntGroupsRelUsersDel_dialogLink
      <<: *HuntGroupsRelUsers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Hunt groups rel user', 'Hunt groups rel users', 1))
      description: _("Do you want to delete this %s?", ngettext('Hunt groups rel user', 'Hunt groups rel users', 1))
      message: _("%s successfully deleted.", ngettext('Hunt groups rel user', 'Hunt groups rel users', 1))
      multiItem: 1
      labelOnList: 1
      
    #HuntGroups
#    <<: *huntGroups_dialogsLink
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
