#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: iVRCommonList_screen
  screens:
    iVRCommonList_screen: &iVRCommonList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *IVRCommon
      title: _("List of %s %2s", ngettext('I v r common', 'I v r common(s)', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          order:
          name: true
          timeout: true
          noAnswerTimeout: true
          timeoutTargetType: true
          timeoutTarget: true
          errorTargetType: true
          errorTarget: true
        blacklist:
          maxDigits: true
          welcomeLocution: true
          noAnswerLocution: true
          errorLocution: true
          successLocution: true
          timeoutNumberValue: true
          timeoutExtension: true
          timeoutVoiceMailUser: true
          errorNumberValue: true
          errorExtension: true
          errorVoiceMailUser: true
          blackListRegExp: true
        options:
          title: _("Options")
          screens:
            iVRCommonEdit_screen: true
          dialogs:
            iVRCommonDel_dialog: true
          default: iVRCommonEdit_screen
      options:
        title: _("Options")
        screens:
          iVRCommonNew_screen: true
        dialogs:
          iVRCommonDel_dialog: true
    iVRCommonNew_screen: &iVRCommonNew_screenLink
      <<: *IVRCommon
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('I v r common', 'I v r common(s)', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          timeoutTarget: true
          errorTarget: true
      fixedPositions: &IVRCommonFixedPositions_link
        group0:
          label: _("Basic configuration")
          colsPerRow: 12
          fields:
            name: 4
            timeout: 4
            maxDigits: 4
            welcomeLocution: 6
            successLocution: 6
            blackListRegExp: 8
        group1:
          label: _("No answer configuration")
          colsPerRow: 3
          fields:
            noAnswerLocution: 2
            noAnswerTimeout: 1
            timeoutTargetType: 1
            timeoutNumberValue: 1
            timeoutExtension: 1
            timeoutVoiceMailUser: 1
        group2:
          label: _("Error configuration")
          colsPerRow: 6
          fields:
            errorLocution: 5
            errorTargetType: 2
            errorNumberValue: 2
            errorExtension: 2
            errorVoiceMailUser: 2
    iVRCommonEdit_screen: &iVRCommonEdit_screenLink
      <<: *IVRCommon
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('I v r common', 'I v r common(s)', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          timeoutTarget: true
          errorTarget: true
      fixedPositions:
        <<: *IVRCommonFixedPositions_link
  dialogs:
    iVRCommonDel_dialog: &iVRCommonDel_dialogLink
      <<: *IVRCommon
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('I v r common', 'I v r common(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('I v r common', 'I v r common(s)', 1))
      message: _("%s successfully deleted.", ngettext('I v r common', 'I v r common(s)', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
