#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: kamPikeTrustedList_screen
  screens: &kamPikeTrusted_screensLink 
    kamPikeTrustedList_screen: &kamPikeTrustedList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KamPikeTrusted
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Trusted IP address', 'Trusted IP address(es)', 0), "[format| (%parent%)]")
      fields: &kamPikeTrusted_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            kamPikeTrustedEdit_screen: true
          dialogs: 
            kamPikeTrustedDel_dialog: true
          default: kamPikeTrustedEdit_screen
        blacklist:
          proto: true
          fromPattern: true
          ruriPattern: true
          priority: true
      options: 
        title: _("Options")
        screens: 
          kamPikeTrustedNew_screen: true
        dialogs: 
          kamPikeTrustedDel_dialog: true
    kamPikeTrustedNew_screen: &kamPikeTrustedNew_screenLink 
      <<: *KamPikeTrusted
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Trusted IP address', 'Trusted IP address(es)', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        blacklist:
          proto: true
          fromPattern: true
          ruriPattern: true
          priority: true
    kamPikeTrustedEdit_screen: &kamPikeTrustedEdit_screenLink
      <<: *KamPikeTrusted
      controller: edit
      class: ui-silk-pencil
      fields:
        blacklist:
          proto: true
          fromPattern: true
          ruriPattern: true
          priority: true
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Trusted IP address', 'Trusted IP address(es)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Trusted IP address', 'Trusted IP address(es)', 1), "[format| (%item%)]")
  dialogs: &kamPikeTrusted_dialogsLink 
    kamPikeTrustedDel_dialog: &kamPikeTrustedDel_dialogLink 
      <<: *KamPikeTrusted
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Trusted IP address', 'Trusted IP address(es)', 1))
      description: _("Do you want to delete this %s?", ngettext('Trusted IP address', 'Trusted IP address(es)', 1))
      message: _("%s successfully deleted.", ngettext('Trusted IP address', 'Trusted IP address(es)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
