#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: kamTrunksDialplanList_screen
  screens: &kamTrunksDialplan_screensLink 
    kamTrunksDialplanList_screen: &kamTrunksDialplanList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KamTrunksDialplan
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Kam trunks dialplan', 'Kam trunks dialplan(s)', 0), "[format| (%parent%)]")
      filterField: TransformationRulesetGroupsTrunk
      fields: &kamTrunksDialplan_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            kamTrunksDialplanEdit_screen: true
          dialogs: 
            kamTrunksDialplanDel_dialog: true
          default: kamTrunksDialplanEdit_screen
        blacklist: &kamTrunksDialplanBlacklist_Link
          dpid: true
          match_op: true
          match_len: true
          subst_exp: true
      options: 
        title: _("Options")
        screens: 
          kamTrunksDialplanNew_screen: true
        dialogs: 
          kamTrunksDialplanDel_dialog: true
    kamTrunksDialplanNew_screen: &kamTrunksDialplanNew_screenLink 
      <<: *KamTrunksDialplan
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Transformation', 'Transformation(s)', 1), "[format| (%parent%)]")
      filterField: TransformationRulesetGroupsTrunk
      shortcutOption: N
      forcedValues:
        matchPp: 1
        matchLen: 0
      fields:
        blacklist:
          <<: *kamTrunksDialplanBlacklist_Link
      fixedPositions: &kamTrunksDialplanFixedPositions_screenLink
        group0:
          colsPerRow: 2
          fields:
            pr: 1
            attrs: 1
            match_exp: 1
            repl_exp: 1
    kamTrunksDialplanEdit_screen: &kamTrunksDialplanEdit_screenLink 
      <<: *KamTrunksDialplan
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Transformation', 'Transformation(s)', 1), "[format| (%item%)]")
      filterField: TransformationRulesetGroupsTrunk
      fields:
        blacklist:
          <<: *kamTrunksDialplanBlacklist_Link
      fixedPositions:
        <<: *kamTrunksDialplanFixedPositions_screenLink
  dialogs: &kamTrunksDialplan_dialogsLink 
    kamTrunksDialplanDel_dialog: &kamTrunksDialplanDel_dialogLink 
      <<: *KamTrunksDialplan
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Transformation', 'Transformation(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Transformation', 'Transformation(s)', 1))
      message: _("%s successfully deleted.", ngettext('Transformation', 'Transformation(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
