production:
  class: \IvozProvider\Model\ApplicationServers
  entity: Core\Domain\Model\ApplicationServer\ApplicationServer
  fields:
    # brand:
      # title: _('Brand id')
      # type: select
      # required: true
      # source:
        # data: mapper
        # config:
          # mapperName: \IvozProvider\Mapper\Sql\Brands
          # fieldName:
            # fields:
              # - name
            # template: '%name%'
          # order: name
      # default: true
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
    ip:
      title: _('Ip')
      type: text
      trim: both
      required: true
    transport:
      title: _('Transport')
      type: text
      trim: both
      defaultValue: udp
    from_pattern:
      title: _('From pattern')
      type: text
      trim: both
    tag:
      title: _('Tag')
      type: text
      trim: both
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
