production:
  class: \IvozProvider\Model\Brands
  entity: Ivoz\Domain\Model\Brand\Brand
  fields:
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    nif:
      title: _('Nif')
      type: text
      trim: both
      required: true
      maxLength: 25
    domainUsers:
      title: _('SIP domain')
      type: text
      trim: both
      maxLength: 255
    defaultTimezoneId:
      title: _('Default timezone')
      type: select
      defaultValue: 145
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Timezones
          entity: \Ivoz\Domain\Model\Timezone\Timezone
          fieldName:
            fields:
              - tz
            template: '%tz%'
          order:
            Timezone.tz: asc
#    logo:
#      title: _('Logo')
#      type: file
#      source:
#        data: fso
#        size_limit: 20M
#        options:
#          hiddenName: true
#          download:
#            external: true
#            type: command
#            target: brandsLogoDownload_command
#            icon: ui-silk-bullet-disk
#            title: _("Download file")
#            onNull: hide
#          delete:
#            type: setNullFso
#            icon: ui-silk-bin
#            title: _("Delete file")
#            onNull: hide
#          upload:
#            type: command
#            target: brandsLogoUpload_command
#            title: _("Upload file")
#            class: qq-uploader
#            onNull: show
#          preview:
#            target: brandsLogoPreview_command
#            type: command
#            class: filePreview
#            external: 1
#            props:
#              width: 150
#              height: 150
#              crop: false
#            onNull: hide
#          previewList:
#            target: brandsLogoPreview_command
#            type: command
#            class: filePreview
#            listController: 1
#            external: 1
#            props:
#              width: 30
#              height: 30
#              crop: false
#            onNull: hide
    postalAddress:
      title: _('Postal address')
      type: text
      trim: both
      required: true
      maxLength: 255
    postalCode:
      title: ngettext('Postal code', 'Postal codes', 1)
      type: text
      trim: both
      required: true
      maxLength: 10
    town:
      title: _('Town')
      type: text
      trim: both
      required: true
      maxLength: 255
    province:
      title: ngettext('Province', 'Provinces', 1)
      type: text
      trim: both
      required: true
      maxLength: 255
    country:
      title: ngettext('Country', 'Countries', 1)
      type: text
      trim: both
      required: true
      maxLength: 255
    registryData:
      title: _('Registry data')
      type: text
      trim: both
      maxLength: 1024
      info:
        type: box
        position: left
        icon: help
        text: _("Información del registro mercantil de la marca que se incluirá en las facturas emitidas: e.g. 'Inscrita en el Registro Mercantil de Bizkaia, tomo XXXX, libro Y, folio ZZZ, hoja AA-BBBB'")
        label: _("Need help?")
    languageId:
      title: _('Language')
      type: select
      defaultValue: 1
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Languages
          entity: \Ivoz\Domain\Model\Language\Language
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Language.name.name: asc
    FromName:
      title: _('From name')
      trim: both
      maxLength: 255
      info:
        type: box
        position: left
        icon: help
        text: _("Name shown as source when sending mails (e.g. IvozProvider Notifications). Leave empty to disable.")
        label: _("Need help?")
    FromAddress:
      title: _('From address')
      type: text
      trim: both
      maxLength: 255
      info:
        type: box
        position: left
        icon: help
        text: _("Mail address shown as source when sending mails. MTA must allow this value.")
        label: _("Need help?")
    recordingsLimitMB:
      title: _("Max disk usage (in MB)")
      type: number
      source:
        control: Spinner
        min: 0
      info:
        type: box
        position: left
        icon: help
        text: _("Max disk usage in megabytes this brand can use. When limit has been reached, oldest brand's recordings will be removed. Set to zero to allow unlimited disk usage.")
        label: _("Need help?")
    recordingsDiskUsage:
      title: _('Disk usage')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_Recordings
        method: getBrandDiskUsage
    recordingsLimitEmail:
      title: _('Disk usage notification email')
      type: text
      maxLength: 250
      info:
        type: box
        position: left
        icon: help
        text: _("Email address that will be notified when 80% of the configured limit has been reached.")
        label: _("Need help?")
    relFeatures:
      title: _('Features')
      type: multiselect
      source:
        data: mapper
        config:
          extraDataAttributes:
            feature: id
          relation: \Ivoz\Domain\Model\FeaturesRelBrand\FeaturesRelBrand
          relationProperty: brand
          relatedProperty: feature
          related: \Ivoz\Domain\Model\Feature\Feature
          relatedFieldName:
            fields:
              - name
            template: '%name%'
          order:
            Feature.name: asc
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
