production: 
  class: \IvozProvider\Model\BrandServices
  entity: Core\Model\BrandService\BrandService
  fields: 
    service:
      title: _('Service id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Services
          entity: \Core\Model\Service\Service
          filterclass: IvozProvider_Klear_Filter_BrandServices
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Service.name: asc
      default: true
    brand:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    code:
      title: _('Code')
      type: text
      trim: both
      required: true
      maxLength: 3
      prefix: '<span class="asterisc">*</span>'
      pattern: '[#0-9*]+'
      info:
        type: box
        position: left
        icon: help
        text: _("Allowed characters are 0-9, * and #")
        label: _("Need help?")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
