production:
  class: \IvozProvider\Model\CallACL
  entity: Ivoz\Domain\Model\CallACL\CallACL
  fields:
    companyId:
      title: _('Company')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Ivoz\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    defaultPolicy:
      title: _('Default policy')
      type: select
      required: true
      source:
        data: inline
        values:
          'allow': _('allow')
          'deny': _('deny')
    CallACLRelPatternId:
      title: _('Call ACL Patterns')
      searchable: false
      type: ghost
      source:
        predefined: list
      data: mapper
      config:
#        mapperName: \IvozProvider\Mapper\Sql\CallACLRelPatterns
        entity: \Ivoz\Domain\Model\CallACLRelPattern\CallACLRelPattern
        filterField: CallACL
        showAsTable: true
        fieldName:
          fields:
            CallACLPattern:
              title: _("Name")
#              mapperName: \IvozProvider\Mapper\Sql\CallACLPatterns
              entity: \Ivoz\Domain\Model\CallACLPattern\CallACLPattern
              field:
                - name
              pattern: "%name%"
            priority:
              title: _("Priority")
            policy:
              title: _("Policy")
        order:
          CallACLRelPattern.priority: asc
        options:
          dialogs:
            callACLRelPatternsDel_dialog: true
          screens:
            callACLRelPatternsEdit_screen: true
          default: 
      options:
        screens:
          callACLRelPatternsNew_screen: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
