production:
  class: \IvozProvider\Model\CallACLRelPatterns
  entity: Ivoz\Domain\Model\CallACLRelPattern\CallACLRelPattern
  fields:
    CallACL:
      title: _('Call ACL')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\CallACL
          entity: \Ivoz\Domain\Model\CallACL\CallACL
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            CallACL.name: asc
      default: true
    CallACLPattern:
      title: _('Call ACL pattern')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\CallACLPatterns
          entity: \Ivoz\Domain\Model\CallACLPattern\CallACLPattern
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            CallACLPattern.name: asc
    priority:
      title: _('Priority')
      type: number
      required: true
      source:
        control: Spinner
    policy:
      title: _('Policy')
      type: select
      required: true
      source:
        data: inline
        values:
          'allow': _('allow')
          'deny': _('deny')
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
