production:
  class: \IvozProvider\Model\CallACLPatterns
  dto: Core\Application\DTO\CallACLPatternDTO
  entity: Core\Model\CallACLPattern\CallACLPattern
  fields:
    companyId:
      title: _('Company')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    regExp:
      title: _('Reg exp')
      type: text
      trim: both
      required: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
