production: 
  class: \IvozProvider\Model\CompanyAdmins
  entity: Core\Model\CompanyAdmin\CompanyAdmin
  fields: 
    companyId:
      title: _('Company id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
      default: true
    username:
      title: _('Username')
      type: text
      trim: both
      required: true
      maxLength: 65
    pass:
      title: _('Pass')
      type: password
      required: true
      adapter: Blowfish
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      trim: both
      defaultValue: 
      maxLength: 100
    active:
      title: _('Active')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    timezoneId:
      title: _('Timezone id')
      type: select
      required: true
      defaultValue: 145
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Timezones
          entity: \Core\Model\Timezone\Timezone
          fieldName: 
            fields: 
              - tz
            template: '%tz%'
          order:
            Timezone.tz: asc
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
    lastname: 
      title: _('Lastname')
      type: text
      trim: both
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
