#include ../conf.d/friendValueHelp.yaml

production:
  class: \IvozProvider\Model\DDIs
  entity: Core\Model\DDI\DDI
  fields:
    companyId:
      title: _('Company id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Model\Company\Company
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    DDI:
      title: _('DDI')
      type: text
      trim: both
      pattern: "^[0-9]+$"
      required: true
      default: true
    externalCallFilterId:
      title: _('External call filter id')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\ExternalCallFilters
          entity: \Core\Model\ExternalCallFilter\ExternalCallFilter
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            ExternalCallFilter.name: asc
        'null': _("Unassigned")
    routeType:
      title: _('Route type')
      type: select
      source:
        data: inline
        filterclass: IvozProvider_Klear_Filter_RouteTypes
        values:
          '__null__':
            title: _("Unassigned")
            visualFilter:
              show: [ ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "userId","faxId",
                "conferenceRoomId", "friendValue", "queueId", "retailAccountId"
              ]
          'user':
            title: _('user')
            visualFilter:
              show: ["userId" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "faxId",
                "conferenceRoomId", "friendValue", "queueId", "retailAccountId"
              ]
          'IVRCommon':
            title: _('IVRCommon')
            visualFilter:
              show: [ "IVRCommonId" ]
              hide: [
                "userId", "IVRCustomId", "huntGroupId", "faxId",
                "conferenceRoomId", "friendValue", "queueId", "retailAccountId"
              ]
          'IVRCustom':
            title: _('IVRCustom')
            visualFilter:
              show: [ "IVRCustomId" ]
              hide: [
                "IVRCommonId", "userId", "huntGroupId", "faxId",
                "conferenceRoomId", "friendValue", "queueId", "retailAccountId"
              ]
          'huntGroup':
            title: _('huntGroup')
            visualFilter:
              show: [ "huntGroupId" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "userId", "faxId",
                "conferenceRoomId", "friendValue", "queueId", "retailAccountId"
              ]
          'fax':
            title: _('fax')
            visualFilter:
              show: [ "faxId" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "userId",
                "conferenceRoomId", "recordCalls", "friendValue", "queueId",
                "retailAccountId"
              ]
          'conferenceRoom':
            title: _('ConferenceRoom')
            visualFilter:
              show: [ "conferenceRoomId" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "userId", "faxId",
                "friendValue", "queueId", "retailAccountId"
              ]
          'friend':
            title: _('Friend')
            visualFilter:
              show: [ "friendValue" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "userId", "faxId",
                "conferenceRoomId", "queueId", "retailAccountId"
              ]
          'queue':
            title: _('Queue')
            visualFilter:
              show: [ "queueId" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "userId", "faxId",
                "conferenceRoomId", "friendValue", "retailAccountId"
              ]
          'retailAccount':
            title: _('Retail Account')
            visualFilter:
              show: [ "retailAccountId", "recordCalls" ]
              hide: [
                "IVRCommonId", "IVRCustomId", "huntGroupId", "userId", "faxId",
                  "conferenceRoomId", "friendValue", "queueId"
              ]
    recordCalls:
      title: _('Record call')
      type: select
      defaultValue: none
      source:
        data: inline
        values:
          'none': _('none')
          'all': _('all')
          'inbound': _('inbound')
          'outbound': _('outbound')
      info:
        type: box
        position: left
        icon: error
        text: _("Local legislation may enforce to announce the call recording to both parties, act responsibly")
        label: _("Need help?")
    displayName:
      title: _('Displayname')
      type: text
      maxLength: 50
      info:
        type: box
        position: left
        icon: help
        text: _("This value will be displayed in the called terminals")
        label: _("Need help?")
    billInboundCalls:
      title: _('Bill inbound call')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
      info:
        type: box
        position: left
        icon: error
        text: _("This setting needs external tarification module")
        label: _("Need help?")
    userId:
      title: _('User id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Core\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    IVRCommonId:
      title: _('I v r common id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\IVRCommon
          entity: \Core\Model\IVRCommon\IVRCommon
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            IVRCommon.name: asc
        'null': _("Unassigned")
    IVRCustomId:
      title: _('I v r custom id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\IVRCustom
          entity: \Core\Model\IVRCustom\IVRCustom
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            IVRCustom.name: asc
        'null': _("Unassigned")
    huntGroupId:
      title: _('Hunt group id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\HuntGroups
          entity: \Core\Model\HuntGroup\HuntGroup
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            HuntGroup.name: asc
        'null': _("Unassigned")
    faxId:
      title: _('Fax id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Faxes
          entity: \Core\Model\Fax\Fax
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Fax.name: asc
        'null': _("Unassigned")
    conferenceRoomId:
      title: _('Conference room id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\ConferenceRooms
          entity: \Core\Model\ConferenceRoom\ConferenceRoom
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            ConferenceRoom.name: asc
        'null': _("Unassigned")
    retailAccountId:
      title: _('Retail Account')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\RetailAccounts
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    friendValue:
      title: _('Friend value')
      type: text
      maxLength: 25
      required: true
      <<: *friendValueHelp
    target:
      title: _('Target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DDITarget
        method: getData
    peeringContractId:
      title: _('Peering contract id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\PeeringContracts
          entity: \Core\Model\PeeringContract\PeeringContract
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            PeeringContract.description: asc
    countryId:
      title: _('Country id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Countries
          entity: \Core\Model\Country\Country
          fieldName:
            fields:
              - name
              - callingCode
            template: '%name% (+%callingCode%)'
          order:
            Country.name${ucLang}: asc
    languageId:
      title: _('Language')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Languages
          entity: \Core\Model\Language\Language
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Language.name: asc
        'null': _("Company's default")
    queueId:
      title: _('Queue')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Queues
          entity: \Core\Model\Queue\Queue
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Queue.name: asc
        'null': _("Unassigned")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
