production: 
  class: \IvozProvider\Model\Domains
  entity: Core\Domain\Model\Domain\Domain
  fields: 
    domain:
      title: _('Domain')
      type: text
      trim: both
      required: true
      maxLength: 255
      default: true
    scope:
      title: _('Scope')
      type: select
      defaultValue: global
      source: 
        data: inline
        values: 
          'global': 
            title: _("global")
            visualFilter:
              show: []
              hide: ["brandId","companyId"]
          'company': 
            title: _("company")
            visualFilter:
              show: ["companyId"]
              hide: ["brandId","pointsTo"]
          'brand': 
            title: _("brand")
            visualFilter:
              hide: ["companyId"]
              show: ["brandId", "pointsTo"]
    pointsTo:
      title: _('Points to')
      type: select
      defaultValue: proxyusers
      source: 
        data: inline
        values: 
          'proxyusers': _('proxyusers')
          'proxytrunks': _('proxytrunks')
    brandId:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    companyId:
      title: _('Company id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 500
    target:
      title: _('Scope')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DomainsScope
        method: getData
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
