production: 
  class: \IvozProvider\Model\EtagVersions
  entity: Core\Domain\Model\EtagVersion\EtagVersion
  fields: 
    table:
      title: _('Table')
      type: text
      maxLength: 55
      default: true
    etag:
      title: _('Etag')
      type: text
      maxLength: 255
    lastChange:
      title: _('Last change')
      type: picker
      source: 
        control: datetime
        settings: 
          disabled: 'false'
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
