production:
  class: \IvozProvider\Model\ExternalCallFilters
  entity: Core\Domain\Model\ExternalCallFilter\ExternalCallFilter
  fields:
    company:
      title: _('Company')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: Core\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    outOfScheduleTargetType:
      title: _('Out of schedule target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
          'number':
            title: _('number')
          'extension':
            title: _('extension')
          'voicemail':
            title: _('voicemail')
    outOfScheduleNumberValue:
      title: _('External Filter destination')
      type: text
      trim: both
      required: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
