#include ../conf.d/friendValueHelp.yaml

production:
  class: \IvozProvider\Model\Extensions
  entity: Core\Domain\Model\Extension\Extension
  fields:
    company:
      title: _('Company id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    number:
      title: _('Number')
      type: text
      trim: both
      pattern: "^[0-9].*$"
      required: true
      default: true
      info:
        type: box
        position: left
        icon: help
        text: _("Minimal length: 2")
        label: _("Need help?")
    routeType:
      title: _('Route type')
      type: select
      source:
        data: inline
        filterclass: IvozProvider_Klear_Filter_RouteTypes
        values:
          '__null__':
            title: _("Unassigned")
            visualFilter:
              show: [ ]
              hide: [
                "numberValue", "IVRCommonId", "IVRCustomId", "userId",
                "huntGroupId", "conferenceRoomId", "friendValue", "queueId"
              ]
          'user':
            title: _('user')
            visualFilter:
              show: [ "userId" ]
              hide: [
                "numberValue", "IVRCommonId", "IVRCustomId", "huntGroupId",
                "conferenceRoomId", "friendValue", "queueId"
              ]
          'IVRCommon':
            title: _('IVRCommon')
            visualFilter:
              show: [ "IVRCommonId" ]
              hide: [
                "numberValue", "userId", "IVRCustomId", "huntGroupId",
                "conferenceRoomId", "friendValue", "queueId"
              ]
          'IVRCustom':
            title: _('IVRCustom')
            visualFilter:
              show: [ "IVRCustomId" ]
              hide: [
                "numberValue", "IVRCommonId", "userId", "huntGroupId",
                "conferenceRoomId", "friendValue", "queueId"
              ]
          'huntGroup':
            title: _('huntGroup')
            visualFilter:
              show: [ "huntGroupId" ]
              hide: [
                "numberValue", "IVRCommonId", "IVRCustomId", "userId",
                "conferenceRoomId", "friendValue", "queueId"
              ]
          'conferenceRoom':
            title: _('Conference Room')
            visualFilter:
              show: [ "conferenceRoomId" ]
              hide: [
                "numberValue", "IVRCommonId", "IVRCustomId", "userId",
                "huntGroupId", "friendValue", "queueId"
              ]
          'number':
            title: _('number')
            visualFilter:
              show: [ "numberValue" ]
              hide: [
                "conferenceRoomId", "IVRCommonId", "IVRCustomId", "userId",
                "huntGroupId", "friendValue", "queueId"
              ]
          'friend':
            title: _('Friend')
            visualFilter:
              show: [ "friendValue" ]
              hide: [
                "conferenceRoomId", "IVRCommonId", "IVRCustomId", "userId",
                "huntGroupId", "numberValue", "queueId"
              ]
          'queue':
            title: _('Queue')
            visualFilter:
              show: [ "queueId" ]
              hide: [
                "friendValue", "conferenceRoomId", "IVRCommonId", "IVRCustomId",
                "userId", "huntGroupId", "numberValue"
              ]
    numberValue:
      title: _('Number value')
      type: text
      pattern: "^\\+?[0-9]+$"
      required: true
      maxLength: 25
      trim: both
    IVRCommon:
      title: _('I v r common id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\IVRCommon
          entity: \Core\Domain\Model\IVRCommon\IVRCommon
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            IVRCommon.name: asc
        'null': _("Unassigned")
    IVRCustom:
      title: _('I v r custom id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\IVRCustom
          entity: \Core\Domain\Model\IVRCustom\IVRCustom
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            IVRCustom.name: asc
        'null': _("Unassigned")
    huntGroup:
      title: _('Hunt group id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\HuntGroups
          entity: \Core\Domain\Model\HuntGroup\HuntGroup
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            HuntGroup.name: asc
        'null': _("Unassigned")
    conferenceRoom:
      title: _('Conference room id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\ConferenceRooms
          entity: \Core\Domain\Model\ConferenceRoom\ConferenceRoom
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            ConferenceRoom.name: asc
        'null': _("Unassigned")
    user:
      title: _('User')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Core\Domain\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    friendValue:
      title: _('Friend value')
      type: text
      maxLength: 25
      required: true
      <<: *friendValueHelp
    queue:
      title: _('Queue')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Queues
          entity: \Core\Domain\Model\Queue\Queue
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Queue.name: asc
        'null': _("Unassigned")
    target:
      title: _('Target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DDITarget
        method: getData
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
