production: 
  class: \IvozProvider\Model\Faxes
  entity: Core\Domain\Model\Fax\Fax
  fields: 
    company:
      title: _('Company id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      maxLength: 50
      default: true
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      trim: both
      required: true
      maxLength: 255
    sendByEmail:
      title: _('Send by email')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
            visualFilter:
              hide: ["email"]
          '1': 
            title: _("Yes")
            visualFilter:
              show: ["email"]
    outgoingDDI:
      title: _('Outgoing DDI')
      type: select
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\DDIs
          entity: \Core\Domain\Model\DDI\DDI
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName: 
            fields: 
              - ddie164
            template: '+%ddie164%'
          order:
            DDI.ddie164: asc
        'null': _("Company's default")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
