production: 
  class: \IvozProvider\Model\FixedCostsRelInvoices
  entity: Core\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice
  fields: 
    brand:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    fixedCost:
      title: _('Fixed cost')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\FixedCosts
          entity: \Core\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName: 
            fields:
              - name
              - cost
            template: '%name% - %cost% €'
          order:
            FixedCostsRelInvoice.description: asc
    invoice:
      title: _('Invoice id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Invoices
          entity: \Core\Domain\Model\Invoice\Invoice
          fieldName: 
            fields: 
              - number
            template: '%number%'
          order:
            Invoice.number: asc
    quantity:
      title: ngettext('Quantity', 'Quantities', 1)
      type: number
      defaultValue: 0
      source: 
        control: Spinner
        min: 0
        max: 100
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
