production: 
  class: \IvozProvider\Model\FixedCosts
  entity: Core\Model\FixedCost\FixedCost
  fields: 
    brandId:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      maxLength: 255
      required: true
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: textarea
    cost:
      title: _('Cost')
      type: text
      pattern: "^[0-9]{1,6}([.][0-9]{1,2})?$"
      sufix: "€"
      required: true
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
