#include ../conf.d/codecsHelp.yaml
#include ../conf.d/updateMethodHelp.yaml

production:
  class: \IvozProvider\Model\Friends
  entity: Ivoz\Domain\Model\Friend\Friend
  fields:
    company:
      title: _('Companyid')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Ivoz\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      pattern: "^[a-zA-Z0-9_]+$"
      trim: both
      maxLength: 100
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("Allowed characters are a-z, A-Z, 0-9 and underscore")
        label: _("Need help?")
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      defaultValue:
      maxLength: 500
    transport:
      title: _('Transport')
      type: select
      required: true
      source:
        data: inline
        values:
          'udp': _('udp')
          'tcp': _('tcp')
          'tls': _('tls')
    ip:
      title: _('Destination IP address')
      type: text
      pattern: "^[.0-9]+$"
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("e.g. 8.8.8.8")
        label: _("Need help?")
    port:
      title: _('Port')
      type: text
      pattern: "^[0-9]+$"
      defaultValue: 5060
    authNeeded:
      title: _('Auth needed')
      type: select
      defaultValue: 'no'
      source:
        data: inline
        values:
          'yes':
            title: _("yes")
            visualFilter:
              show: ["password"]
              hide: []
          'no':
            title: _("no")
            visualFilter:
              hide: ["password"]
              show: []
    password:
      title: ngettext('Password', 'Passwords', 1)
      type: text
      pattern: "^(?=.*[A-Z].*[A-Z].*[A-Z])(?=.*[+*_-])(?=.*[0-9].*[0-9].*[0-9])(?=.*[a-z].*[a-z].*[a-z]).{10,}$"
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("Minimal length 10, including 3 uppercase letters, 3 lowercase letters, 3 digits and one character in '+*_-'")
        label: _("Need help?")
      options:
        commands:
          generatePassword_command: true
    callACL:
      title: _('Call ACL')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\CallACL
          entity: \Ivoz\Domain\Model\CallACL\CallACL
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            CallACL.name: asc
        'null': _("Allow all outgoing calls")
    country:
      title: _('Country code')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Countries
          entity: \Ivoz\Domain\Model\Country\Country
          fieldName:
            fields:
              - name
              - callingCode
            template: '%name% (+%callingCode%)'
          order:
            Country.name_${lang}: asc
        'null': _("Company's default")
      info:
        type: box
        position: left
        icon: help
        text: _("Outgoing calls coming from Friend must have this country format")
        label: _("Need help?")
    areaCode:
      title: _('Areacode')
      type: text
      maxLength: 10
      info:
        type: box
        position: left
        icon: help
        text: _("Outgoing calls coming from Friend must have this area code format")
        label: _("Need help?")
    outgoingDDI:
      title: _('Fallback Outgoing DDI')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\DDIs
          entity: \Ivoz\Domain\Model\DDI\DDI
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - ddie164
            template: '+%ddie164%'
          order:
            DDI.ddie164: asc
        'null': _("Company's default")
      info:
        type: box
        position: left
        icon: help
        text: _("This DDI will be used if friend presented DDI doesn't match any of the company DDIs")
        label: _("Need help?")
    priority:
      title: _('Priority')
      type: number
      defaultValue: 1
      source:
        control: Spinner
    disallow:
      title: _('Disallowed codecs')
      type: text
      trim: both
      defaultValue: all
      maxLength: 100
      <<: *codecsHelp
    allow:
      title: _('Allowed codecs')
      type: select
      trim: both
      defaultValue: alaw
      maxLength: 100
      source:
        data: inline
        values:
            'alaw': 'alaw - G.711 a-law'
            'ulaw': 'ulaw - G.711 u-law'
            'gsm': 'gsm - GSM'
            'speex': 'speex - SpeeX 32khz'
            'g722': 'g722 - G.722'
            'g726': 'g726 - G.726 RFC3551'
            'g729': 'g729 - G.729A'
            'ilbc': 'ilbc - iLBC'
            'opus': 'opus - Opus codec'
    directMediaMethod:
      title: _('CallerID update method')
      type: select
      defaultValue: update
      source:
        data: inline
        values:
          'invite': 'invite'
          'update': 'update'
      <<: *updateMethodHelp
    calleridUpdateHeader:
      title: _('CallerID update header')
      type: select
      defaultValue: pai
      source:
        data: inline
        values:
          'pai': 'P-Asserted-Identity (PAI)'
          'rpid': 'Remote-Party-ID (RPID)'
    updateCaller:
      title: _('Update CallerID?')
      type: select
      defaultValue: yes
      source:
        data: inline
        values:
          'yes':
            title: _("yes")
            visualFilter:
              show: ["direct_media_method", "callerid_update_header"]
              hide: []
          'no':
            title: _("no")
            visualFilter:
              hide: ["direct_media_method", "callerid_update_header"]
              show: []
    fromDomain:
      title: _('From domain')
      type: text
      maxLength: 190
    directConnectivity:
      title: _('Direct connectivity')
      type: select
      defaultValue: yes
      source:
        data: inline
        values:
          'yes':
            title: _("yes")
            visualFilter:
              show: ["ip", "port", "transport", "auth_needed"]
              hide: []
          'no':
            title: _("no")
            visualFilter:
              hide: ["ip", "port", "transport", "auth_needed"]
              show: ["password"]
    language:
      title: _('Language')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Languages
          entity: \Ivoz\Domain\Model\Language\Language
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Language.name: asc
        'null': _("Company's default")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
