production: 
  class: \IvozProvider\Model\GenericCallACLPatterns
  entity: Core\Domain\Model\GenericCallACLPattern\GenericCallACLPattern
  fields: 
    brand:
      title: _('Brand')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Domain\Model\Brand\Brand
          fieldName:
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
    regExp:
      title: _('Reg exp')
      type: text
      trim: both
      required: true
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
