production: 
  class: \IvozProvider\Model\HolidayDates
  entity: Ivoz\Domain\Model\HolidayDate\HolidayDate
  fields: 
    calendarId:
      title: _('Calendar')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Calendars
          entity: \Ivoz\Domain\Model\Calendar\Calendar
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Calendar.name: asc
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    eventDate:
      title: _('Event date')
      type: picker
      required: true
      source: 
        control: date
        settings: 
          disabled: 'false'
#          dateFormat: dd-mm
    locutionId:
      title: _('Locution')
      type: select
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Locutions
          entity: \Ivoz\Domain\Model\Locution\Locution
          filterclass: IvozProvider_Klear_Filter_HolidayDateSelectLocution
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Locution.encodedFileMimeType: asc
        'null': _("Unassigned")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
