production:
  class: \IvozProvider\Model\IVRCustomEntries
  entity: Ivoz\Domain\Model\IVRCustomEntry\IVRCustomEntry
  fields:
    IVRCustom:
      title: _('I v r custom id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\IVRCustom
          entity: \Ivoz\Domain\Model\IVRCustom\IVRCustom
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            IVRCustom.name: asc
      default: true
    entry:
      title: _('Entry')
      type: text
      required: true
      maxLength: 40
      info:
        type: box
        position: left
        icon: help
        text: _("You can use regular expressions to define values this entry will match.")
        label: _("Need help?")
    welcomeLocution:
      title: _('Welcome locution id')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Locutions
          entity: \Ivoz\Domain\Model\Locution\Locution
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
        'null': _("Unassigned")
    targetType:
      title: _('Target type')
      type: select
      required: true
      source:
        data: inline
        values:
          'number':
            title: _('number')
            visualFilter:
              show: ["targetNumberValue"]
              hide: ["targetExtensionId", "targetVoiceMailUserId"]
          'extension':
            title: _('extension')
            visualFilter:
              show: ["targetExtensionId"]
              hide: ["targetNumberValue", "targetVoiceMailUserId"]
          'voicemail':
            title: _('voicemail')
            visualFilter:
              show: ["targetVoiceMailUserId"]
              hide: ["targetExtensionId", "targetNumberValue"]
    targetNumberValue:
      title: _('Target number value')
      type: text
      trim: both
      required: true
    targetExtension:
      title: _('Target extension id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Extensions
          entity: \Ivoz\Domain\Model\Extension\Extension
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
        'null': _("Unassigned")
    targetVoiceMailUser:
      title: _('Target voice mail user id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Ivoz\Domain\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    target:
      title: _('Target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_IVRCustomTarget
        method: getTargetData
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
