production: 
  class: \IvozProvider\Model\KamDispatcher
  dto: Kam\Application\DTO\KamDispatcherDTO
  entity: Kam\Model\KamDispatcher\KamDispatcher
  fields: 
    setid:
      title: _('Setid')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
      default: true
    destination:
      title: _('Destination')
      type: text
      trim: both
      defaultValue: 
      maxLength: 192
    flags:
      title: _('Flag')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
    priority:
      title: _('Priority')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
    attrs:
      title: _('Attr')
      type: text
      trim: both
      defaultValue: 
      maxLength: 128
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      trim: both
      defaultValue: 
      maxLength: 64
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
