production: 
  class: \IvozProvider\Model\PikeTrusted
  entity: Kam\Domain\Model\PikeTrusted\PikeTrusted
  fields: 
    srcIp:
      title: _('IP')
      type: text
      maxLength: 50
      default: true
    proto:
      title: _('Proto')
      type: text
      maxLength: 4
    fromPattern:
      title: _('From pattern')
      type: text
      maxLength: 64
    ruriPattern:
      title: _('Ruri pattern')
      type: text
      maxLength: 64
    tag:
      title: _('Description')
      type: text
      maxLength: 64
    priority:
      title: _('Priority')
      type: number
      defaultValue: 0
      source:
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
