production: 
  class: \IvozProvider\Model\KamTrunksLcrRule
  dto: Core\Application\DTO\KamTrunksLcrRuleDTO
  entity: Core\Model\KamTrunksLcrRule\KamTrunksLcrRule
  fields: 
    lcrId:
      title: _('Lcr id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    prefix:
      title: _('Prefix')
      type: text
      trim: both
    fromUri:
      title: _('From uri')
      type: text
      trim: both
    requestUri:
      title: _('Request uri')
      type: text
      trim: both
    stopper:
      title: _('Stopper')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
    enabled:
      title: _('Enabled')
      type: number
      defaultValue: 1
      source: 
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
