production: 
  class: \IvozProvider\Model\KamUsersDomainAttrs
  dto: Kam\Application\DTO\KamUsersDomainAttrDTO
  entity: Kam\Model\KamUsersDomainAttr\KamUsersDomainAttr
  fields: 
    did:
      title: _('Did')
      type: text
      required: true
      maxLength: 64
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 32
    type:
      title: ngettext('Type', 'Types', 1)
      type: number
      required: true
      source: 
        control: Spinner
    value:
      title: ngettext('Value', 'Values', 1)
      type: text
      required: true
      maxLength: 255
    lastModified:
      title: _('Last modified')
      type: picker
      defaultValue: 1900-01-01 00:00:01
      source: 
        control: datetime
        settings: 
          disabled: 'false'
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
