production:
  class: \IvozProvider\Model\LcrRules
  entity: Core\Domain\Model\LcrRule\LcrRule
  fields:
    brandId:
      title: _('Brand id')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Domain\Model\Brand\Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    prefix:
      title: _('Prefix')
      type: text
      trim: both
    from_uri:
      title: _('From uri')
      type: text
      trim: both
    request_uri:
      title: _('Pattern')
      required: true
      type: text
      trim: both
      pattern: "^:.*@$"
      maxLength: 64
      info:
        type: box
        position: left
        icon: help
        text: _("For this expression, use ':' instead of '^' and '@' instead of '$'")
        label: _("Need help?")
    stopper:
      title: _('Stopper')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    enabled:
      title: _('Enabled')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    tag:
      title: _('Tag')
      type: text
      trim: both
      required: true
      pattern: "^[a-zA-Z0-9_]+$"
      maxLength: 50
      info:
        type: box
        position: left
        icon: help
        text: _("Enter a label without spaces")
        label: _("Need help?")
    description:
      title: ngettext('Description', 'Descriptions', 1)
      required: true
      type: text
      trim: both
      defaultValue:
      maxLength: 500
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
