production: 
  class: \IvozProvider\Model\MediaRelaySets
  entity: Ivoz\Domain\Model\MediaRelaySet\MediaRelaySet
  fields: 
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      maxLength: 32
      required: true
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      trim: both
      maxLength: 200
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
