production: 
  class: \IvozProvider\Model\MusicOnHold
  entity: Core\Domain\Model\MusicOnHold\MusicOnHold
  fields: 
    company:
      title: _('Company')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
#    originalFile:
#      title: ngettext('Uploaded file', 'Uploaded files', 1)
#      type: file
#      source:
#        data: fso
#        size_limit: 20M
#        options:
#          download:
#            external: true
#            type: command
#            target: musicOnHold_FileDownload_command
#            icon: ui-silk-bullet-disk
#            title: _("Download file")
#            onNull: hide
#          upload:
#            type: command
#            target: musicOnHold_FileUpload_command
#            title: _("Upload file")
#            class: qq-uploader
#            onNull: show
#          mediaembed:
#            type: command
#            title: _("Listen to MoH")
#            class: jmedia
#            onNull: hide
#            target: musicOnHold_FileDownload_command
#    encodedFile:
#      title: ngettext('File for play', 'Files for play', 1)
#      type: file
#      source:
#        data: fso
#        size_limit: 20M
#        options:
#          download:
#            external: true
#            type: command
#            target: musicOnHold_FileDownload_command
#            icon: ui-silk-bullet-disk
#            title: _("Download file")
#            onNull: hide
#          mediaembed:
#            type: command
#            title: _("Listen to MoH")
#            class: jmedia
#            onNull: hide
#            target: musicOnHold_FileDownload_command
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
