production:
  class: \IvozProvider\Model\OutgoingRouting
  entity: Ivoz\Domain\Model\OutgoingRouting\OutgoingRouting
  fields:
    type:
      title: ngettext('Type', 'Types', 1)
      type: select
      defaultValue: pattern
      source:
        data: inline
        values:
          'pattern':
            title: _('Pattern')
            visualFilter:
              show: ["routingPatternId"]
              hide: ["routingPatternGroupId"]
          'group':
            title: _('Group')
            visualFilter:
              show: ["routingPatternGroupId" ]
              hide: ["routingPatternId"]
          'fax':
            title: _('Fax')
            visualFilter:
              hide: ["routingPatternId","routingPatternGroupId"]
      default: true
    routingPatternId:
      title: _('Select destination pattern')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\RoutingPatterns
          entity: \Ivoz\Domain\Model\RoutingPattern\RoutingPattern
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
              - description
              - regExp
            template: '%name% %description% (%regExp%)'
          order:
            RoutingPattern.name${ucLang}: asc
    routingPatternGroupId:
      title: _('Select destination group')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\RoutingPatternGroups
          entity: \Ivoz\Domain\Model\RoutingPatternGroup\RoutingPatternGroup
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            RoutingPatternGroup.name: asc
    peeringContractId:
      title: _('Peering contract')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\PeeringContracts
          entity: \Ivoz\Domain\Model\PeeringContract\PeeringContract
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            PeeringContract.name: asc
    priority:
      title: _('Priority')
      type: number
      defaultValue: 1
      required: true
      source:
        control: Spinner
        min: 1
        max: 254
    weight:
      title: _('Weight')
      type: number
      required: true
      defaultValue: 1
      source:
        control: Spinner
        min: 1
        max: 254
    companyId:
      title: _('Company')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Ivoz\Domain\Model\Company\Company
          filterclass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
        'null': _("Apply to all companies")
    target:
      title: _('Destination')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_OutgoingRouteType
        method: getData

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
