production: 
  class: \IvozProvider\Model\PeerServers
  entity: Core\Model\PeerServer\PeerServer
  fields: 
    peeringContractId:
      title: _('Peering contract')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\PeeringContracts
          entity: \Core\Model\PeeringContract\PeeringContract
          fieldName: 
            fields: 
              - description
            template: '%description%'
          order:
            PeeringContract.description: asc
      default: true
    ip:
      title: _('Destination IP address')
      type: text
      pattern: "^[.0-9]+$"
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Leave empty to send to Host field")
        label: _("Need help?")
    brandId:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    hostname:
      title: _('Host')
      type: text
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Use address or hostname")
        label: _("Need help?")
    port:
      title: _('Port')
      type: number
      defaultValue: 5060
      source: 
        control: Spinner
    params:
      title: _('R-URI params')
      type: text
      pattern: "^;.*$"
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Add this params to R-URI (must start with ';')")
        label: _("Need help?")
    uriScheme:
      title: _('Uri scheme')
      type: select
      defaultValue: 1
      source:
        data: inline
        values: 
          '1':
            title: _("sip")
          '2':
            title: _("sips")
    transport:
      title: _('Transport')
      type: select
      defaultValue: 1
      source:
        data: inline
        values: 
          '1':
            title: _("udp")
          '2':
            title: _("tcp")
          '3':
            title: _("tls")
    strip:
      title: _('Strip')
      type: number
      info:
        type: box
        position: left
        icon: help
        text: _("Strip N digits from the beginning of the callee")
        label: _("Need help?")
      source: 
        control: Spinner
    prefix:
      title: _('Prefix')
      type: text
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Prepend this field to callee")
        label: _("Need help?")
    sendPAI:
      title: _('Send PAI')
      type: checkbox
    sendRPID:
      title: _('Send RPID')
      type: checkbox
    authNeeded:
      title: _('Auth needed')
      type: select
      defaultValue: 'no'
      source:
        data: inline
        values:
          'yes':
            title: _("yes")
            visualFilter:
              show: ["auth_user", "auth_password"]
              hide: []
          'no':
            title: _("no")
            visualFilter:
              hide: ["auth_user", "auth_password"]
              show: []
    authUser:
      title: _('Auth user')
      type: text
      trim: both
      required: true
    authPassword:
      title: _('Auth password')
      type: password
      adapter: PlainText
      required: true
    sipProxy:
      title: _('SIP Proxy')
      type: text
      trim: both
      maxLength: 128
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("IP or domain name (port with ':')")
        label: _("Need help?")
    outboundProxy:
      title: _('Outbound Proxy')
      type: text
      trim: both
      maxLength: 128
      info:
        type: box
        position: left
        icon: help
        text: _("Send to IP[:PORT] instead of SIP Proxy address")
        label: _("Need help?")
    fromUser:
      title: _('From user')
      type: text
      maxLength: 64
      info:
        type: box
        position: left
        icon: help
        text: _("Use this instead in From header username")
        label: _("Need help?")
    fromDomain:
      title: _('From domain')
      type: text
      maxLength: 190
      info:
        type: box
        position: left
        icon: help
        text: _("Use this instead in From header domain")
        label: _("Need help?")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
