production: 
  class: \IvozProvider\Model\PickUpRelUsers
  entity: Core\Domain\Model\PickUpRelUser\PickUpRelUser
  fields: 
    pickUpGroup:
      title: _('Pick up group id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\PickUpGroups
          entity: \Core\Domain\Model\PickUpGroup\PickUpGroup
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            PickUpGroup.name: asc
      default: true
    user:
      title: _('User id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Core\Domain\Model\User\User
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            User.name: asc
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
