production: 
  class: \IvozProvider\Model\ProxyUsers
  entity: Core\Domain\Model\ProxyUser\ProxyUser
  fields: 
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      maxLength: 100
      default: true
    ip:
      title: _('Ip')
      type: text
      trim: both
      maxLength: 100
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
