production:
  class: \IvozProvider\Model\QueueMembers
  entity: Ivoz\Domain\Model\QueueMember\QueueMember
  fields:
    queueId:
      title: _('Queue')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Queues
          entity: \Ivoz\Domain\Model\Queue\Queue
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Queue.name: asc
        'null': _("Unassigned")
      default: true
    userId:
      title: _('User')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Ivoz\Domain\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    penalty:
      title: _('Penalty')
      type: number
      source:
        control: Spinner
        min: 1
      info:
        type: box
        position: left
        icon: help
        text: _("Members of lower penalty will be called first. Higher penalty members will be contacted if no members of current penalty are available")
        label: _("Need help?")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
