production: 
  class: \IvozProvider\Model\RoutingPatternGroups
  entity: Core\Domain\Model\RoutingPatternGroup\RoutingPatternGroup
  fields: 
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 55
      default: true
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      maxLength: 55
    brand:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    relPatterns:
      title: _('Destination patterns')
      type: multiselect
      source:
        data: mapper
        config:
          extraDataAttributes:
            brand: brandId
          relation:  \Core\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern
          relationProperty: routingPatternGroup
          relatedProperty: routingPattern
          related: \Core\Domain\Model\RoutingPattern\RoutingPattern
          relatedFieldName:
            fields:
              - name
              - description
              - regExp
            template: "%name% %description% (%regExp%)"

          filterclass: IvozProvider_Klear_Filter_Brand
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
