production:
  class: \IvozProvider\Model\RoutingPatterns
  entity: Core\Model\RoutingPattern\RoutingPattern
  fields: 
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      isMultilang: true
      required: true
      maxLength: 55
      default: true
    description:
      title: ngettext('Description', 'Descriptions', 1)
      isMultilang: true
      type: text
      maxLength: 55
    regExp:
      title: _('Reg exp / Prefix')
      type: text
      required: true
      maxLength: 80
      info:
        type: box
        position: left
        icon: help
        text: _("If you want a prefix, use only digits. Otherwise, define your regular expresion.")
        label: _("Need help?")
    brand:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
