production: 
  class: \IvozProvider\Model\RoutingPatternGroupsRelPatterns
  entity: Ivoz\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern
  fields: 
    routingPatternId:
      title: _('Routing pattern id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\RoutingPatterns
          entity: \Ivoz\Domain\Model\RoutingPattern\RoutingPattern
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            RoutingPattern.name${ucLang}: asc
      default: true
    routingPatternGroupId:
      title: _('Routing pattern group id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\RoutingPatternGroups
          entity: \Ivoz\Domain\Model\RoutingPatternGroup\RoutingPatternGroup
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            RoutingPatternGroup.name: asc
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
