production: 
  class: \IvozProvider\Model\Timezones
  entity: Core\Model\Timezone\Timezone
  fields: 
    country:
      title: _('Country id')
      type: select
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Countries
          entity: \Core\Model\Country\Country
          fieldName: 
            fields: 
              - code
            template: '%code%'
          order:
            Country.code: asc
        'null': _("Unassigned")
      default: true
    tz:
      title: _('Tz')
      type: text
      trim: both
      required: true
    comment:
      title: _('Comment')
      type: text
      trim: both
      defaultValue: 
    timeZoneLabel:
      title: _('Time zone label')
      type: text
      trim: both
      defaultValue: 
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
