production: 
  class: \IvozProvider\Model\TransformationRulesetGroups
  entity: Core\Model\TransformationRulesetGroup\TransformationRulesetGroup
  fields: 
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      maxLength: 100
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      trim: both
      defaultValue: 
      maxLength: 500
    brandId:
      title: _('Brand')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    callerIn:
      title: _('Caller in')
      type: number
      source: 
        control: Spinner
    calleeIn:
      title: _('Callee in')
      type: number
      source: 
        control: Spinner
    callerOut:
      title: _('Caller out')
      type: number
      source: 
        control: Spinner
    calleeOut:
      title: _('Callee out')
      type: number
      source: 
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
