production: 
  class: \IvozProvider\Model\TransformationRulesetGroupsTrunks
  entity: Core\Domain\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunk
  fields: 
    brand:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Core\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      maxLength: 100
    callerIn:
      title: _('Caller in')
      type: number
      source: 
        control: Spinner
    calleeIn:
      title: _('Callee in')
      type: number
      source: 
        control: Spinner
    callerOut:
      title: _('Caller out')
      type: number
      source: 
        control: Spinner
    calleeOut:
      title: _('Callee out')
      type: number
      source: 
        control: Spinner
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      trim: both
      defaultValue: 
      maxLength: 500
    automatic:
      title: _('Generate rules?')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
            visualFilter:
              show: []
              hide: ["countryId", "internationalCode"]
          '1': 
            title: _("Yes")
            visualFilter:
              show: ["countryId", "internationalCode"]
              hide: []
      info:
        type: box
        position: left
        icon: help
        text: _("Will create default rules for a given country. This rules can be modified later.")
        label: _("Need help?")
    country:
      title: _('Country code')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Countries
          entity: \Core\Domain\Model\Country\Country
          fieldName: 
            fields: 
              - name
              - callingCode
            template: '%name% (+%callingCode%)'
          order:
            Country.name${ucLang}: asc
      defaultValue: 70
    internationalCode:
      title: _('International Code')
      type: text
      pattern: "^[0-9]{2,10}$"
      maxLength: 10
      defaultValue: '00'
      info:
        type: box
        position: left
        icon: help
        text: _("Code used for internationals calls, usually 00.")
        label: _("Need help?")
    nationalNumLength:
      title: _('National number length')
      type: number
      defaultValue: 9
      source: 
        control: Spinner
      info:
        type: box
        position: left
        icon: help
        text: _("How long are the normal phone numbers called inside this country?")
        label: _("Need help?")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
