production:
  class: \IvozProvider\Model\Users
  entity: Ivoz\Domain\Model\User\User
  fields:
    company:
      title: _('Company')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Ivoz\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
        'null': _("Unassigned")
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
    lastname:
      title: _('Lastname')
      type: text
      trim: both
      required: true
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      maxLength: 100
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Used as voicemail reception and user portal credential")
        label: _("Need help?")
    pass:
      title: ngettext('Password', 'Passwords', 1)
      type: password
      adapter: PlainText
    active:
      title: _('Active')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              show: []
              hide: ["username", "pass"]
          '1':
            title: _("Yes")
            visualFilter:
              show: ["username", "pass"]
              hide: []
    timezone:
      title: _('Timezone')
      type: select
      defaultValue: 145
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Timezones
          entity: \Ivoz\Domain\Model\Timezone\Timezone
          fieldName:
            fields:
              - tz
            template: '%tz%'
          order:
            Timezone.tz: asc
    terminal:
      title: _('Terminal')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Terminals
          entity: \Ivoz\Domain\Model\Terminal\Terminal
          filterclass: IvozProvider_Klear_Filter_Terminals
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Terminal.name: asc
        'null': _("Unassigned")
    extension:
      title: _('Screen Extension')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Extensions
          entity: \Ivoz\Domain\Model\Extension\Extension
          filterclass: IvozProvider_Klear_Filter_Extensions
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
        'null': _("Unassigned")
    outgoingDDI:
      title: _('Outgoing DDI')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\DDIs
          entity: \Ivoz\Domain\Model\DDI\DDI
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - ddie164
            template: '+%ddie164%'
          order:
            DDI.ddie164: asc
        'null': _("Company's default")
    callACL:
      title: _('Call ACL')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\CallACL
          entity: \Ivoz\Domain\Model\CallACL\CallACL
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            CallACL.name: asc
        'null': _("Allow all outgoing calls")
    doNotDisturb:
      title: _('Do not disturb')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    isBoss:
      title: _('Is boss')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              show: []
              hide: ["bossAssistantId", "exceptionBoosAssistantRegExp"]
          '1':
            title: _("Yes")
            visualFilter:
              show: ["bossAssistantId", "exceptionBoosAssistantRegExp"]
              hide: []
    bossAssistant:
      title: _('Assistant')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Ivoz\Domain\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Bossassistant
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    exceptionBoosAssistantRegExp:
      title: _('Exception boos assistant reg exp')
      type: text
      trim: both
      maxLength: 255
    username:
      title: _('Username')
      type: text
      trim: both
      maxLength: 65
    maxCalls:
      title: _('Max calls')
      type: number
      defaultValue: 0
      source:
        control: Spinner
        min: 0
        max: 100
      info:
        type: box
        position: left
        icon: help
        text: _("Limits the number of received calls if the user is handling simultaneously (inbound and outbound) more than the number set. Set 0 for unlimited calls.")
        label: _("Need help?")
    voicemailEnabled:
      title: _('Voicemail enabled')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide: ["voicemailSendMail", "voicemailAttachSound"]
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show: ["voicemailSendMail", "voicemailAttachSound"]
              hide: []
    voicemailSendMail:
      title: _('Voicemail send mail')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide: ["voicemailAttachSound"]
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show: ["voicemailAttachSound"]
              hide: []
    voicemailAttachSound:
      title: _('Voicemail attach sound')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    PickUpRelUsers:
      title: _('Pick Up Groups')
      type: multiselect
      source:
        data: mapper
        config:
          extraDataAttributes:
            company: companyId
          relation: \Ivoz\Domain\Model\PickUpRelUser\PickUpRelUser
          relationProperty: user
          relatedProperty: pickUpGroup
          related: \Ivoz\Domain\Model\PickUpGroup\PickUpGroup
          relatedFieldName: name
          filterclass: IvozProvider_Klear_Filter_Company
    country:
      title: _('Country code')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Countries
          entity: \Ivoz\Domain\Model\Country\Country
          fieldName:
            fields:
              - name
              - callingCode
            template: '%name% (+%callingCode%)'
          order:
            Country.name${ucLang}: asc
        'null': _("Company's default")
    areaCode:
      title: _('Areacode')
      type: text
      maxLength: 10
      info:
        type: box
        position: left
        icon: help
        text: _("Calling a number within the same Area can omit Area Code")
        label: _("Need help?")
    HuntGroupsRelUsers:
      title: _('Hunt groups joined')
      searchable: false
      type: ghost
      source:
        predefined: list
      data: mapper
      config:
#        mapperName: \IvozProvider\Mapper\Sql\HuntGroupsRelUsers
        entity: \Ivoz\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUser
        filterField: HuntGroupsRelUser.User
        showAsTable: true
        fieldName:
          fields:
            huntGroup:
              title: _("Hunt group")
#              mapperName: \IvozProvider\Mapper\Sql\HuntGroups
              entity: \Ivoz\Domain\Model\HuntGroup\HuntGroup
              field:
                - name
              pattern: "%name%"
            timeoutTime:
              title: _("Time out time")
            priority:
              title: _("Priority")
        options:
          dialogs:
            huntGroupsRelUsersDel_dialog: true
          screens:
            huntGroupsRelUsersEdit_screen: true
          default:
      options:
        screens:
          huntGroupsRelUsersNew_screen: true
    language:
      title: _('Language')
      type: select
      defaultValue: 1
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Languages
          entity: \Ivoz\Domain\Model\Language\Language
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Language.name: asc
        'null': _("Company's default")
    externalIpCalls: 
      title: _('Calls from non-granted IPs')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("None")
          '1': 
            title: "1"
          '2': 
            title: "2"
          '3': 
            title: "3"
      info:
        type: box
        position: left
        icon: help
        text: _("Enable calling from non-granted IP addresses for this user. It limits the number of outgoing calls to avoid toll-fraud. 'None' value makes outgoing calls unlimited as long as company IP policy is fulfilled.")
        label: _("Need help?")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
