Ivoz\Domain\Model\BrandService\BrandService:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\BrandServiceDoctrineRepository
  type: entity
  table: BrandServices
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
