Ivoz\Domain\Model\CallACL\CallACLAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
  uniqueConstraints:
    companyId_2:
      columns:
        - companyId
        - name
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    defaultPolicy:
      type: string
      nullable: false
      length: 10
      options:
        fixed: false
        comment: '[enum:allow|deny]'
      column: defaultPolicy
  manyToOne:
    company:
      targetEntity: \Ivoz\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
