Ivoz\Domain\Model\CallACL\CallACL:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\CallACLDoctrineRepository
  type: entity
  table: CallACL
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
