Ivoz\Domain\Model\Country\Zone:
  type: embeddable
  fields:
    zone:
      type: string
      nullable: true
      length: 55
      options:
        fixed: false
        comment: '[ml]'
    en:
      type: string
      nullable: false
      length: 55
      options:
        fixed: false
        default: ''
      column: zone_en
    es:
      type: string
      nullable: false
      length: 55
      options:
        fixed: false
        default: ''
      column: zone_es
