Ivoz\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendarAbstract:
  type: mappedSuperclass
  indexes:
    filterId:
      columns:
        - filterId
    calendarId:
      columns:
        - calendarId
  manyToOne:
    filter:
      targetEntity: \Ivoz\Domain\Model\ExternalCallFilter\ExternalCallFilterInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        filterId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    calendar:
      targetEntity: \Ivoz\Domain\Model\Calendar\CalendarInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        calendarId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
