Ivoz\Domain\Model\FaxesInOut\File:
  type: embeddable
  fields:
    fileSize:
      type: integer
      nullable: true
      options:
        unsigned: true
        comment: '[FSO]'
      column: fileFileSize
    mimeType:
      type: string
      nullable: true
      length: 80
      options:
        fixed: false
      column: fileMimeType
    baseName:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: fileBaseName
