Ivoz\Domain\Model\FeaturesRelCompany\FeaturesRelCompanyAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
    featureId:
      columns:
        - featureId
  manyToOne:
    company:
      targetEntity: \Ivoz\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    feature:
      targetEntity: \Ivoz\Domain\Model\Feature\FeatureInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relFeatures
      joinColumns:
        featureId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
