Ivoz\Domain\Model\FriendsPattern\FriendsPattern:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\FriendsPatternDoctrineRepository
  type: entity
  table: FriendsPatterns
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
