Ivoz\Domain\Model\GenericMusicOnHold\GenericMusicOnHold:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\GenericMusicOnHoldDoctrineRepository
  type: entity
  table: GenericMusicOnHold
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
