Ivoz\Domain\Model\GenericCallACLPattern\GenericCallACLPatternAbstract:
  type: mappedSuperclass
  indexes:
    brandId:
      columns:
        - brandId
  uniqueConstraints:
    nameBrand:
      columns:
        - name
        - brandId
  fields:
    name:
      column: name
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    regExp:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: regExp
  manyToOne:
    brand:
      targetEntity: \Ivoz\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
