Ivoz\Domain\Model\HolidayDate\HolidayDate:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\HolidayDateDoctrineRepository
  type: entity
  table: HolidayDates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
