Ivoz\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUserAbstract:
  type: mappedSuperclass
  indexes:
    huntGroupId:
      columns:
        - huntGroupId
    userId:
      columns:
        - userId
  uniqueConstraints:
    userHuntgroup:
      columns:
        - userId
        - huntGroupId
    prioHuntgroup:
      columns:
        - priority
        - huntGroupId
  fields:
    timeoutTime:
      type: smallint
      nullable: true
      options:
        unsigned: false
      column: timeoutTime
    priority:
      type: smallint
      nullable: true
      options:
        unsigned: false
  manyToOne:
    huntGroup:
      targetEntity: \Ivoz\Domain\Model\HuntGroup\HuntGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        huntGroupId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    user:
      targetEntity: \Ivoz\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        userId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
