Ivoz\Domain\Model\InvoiceTemplate\InvoiceTemplate:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\InvoiceTemplateDoctrineRepository
  type: entity
  table: InvoiceTemplates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
