Ivoz\Domain\Model\IVRCustom\IVRCustom:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\IVRCustomDoctrineRepository
  type: entity
  table: IVRCustom
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
