Ivoz\Domain\Model\LcrRuleTarget\LcrRuleTarget:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\LcrRuleTargetDoctrineRepository
  type: entity
  table: LcrRuleTargets
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
