Ivoz\Domain\Model\Locution\EncodedFile:
  type: embeddable
  fields:
    fileSize:
      type: integer
      nullable: true
      options:
        unsigned: true
        comment: '[FSO:keepExtension]'
      column: encodedFileFileSize
    mimeType:
      type: string
      nullable: true
      length: 80
      options:
        fixed: false
      column: encodedFileMimeType
    baseName:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: encodedFileBaseName
