Ivoz\Domain\Model\MatchList\MatchListAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
  uniqueConstraints:
    matchName:
      columns:
        - companyId
        - name
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
  manyToOne:
    company:
      targetEntity: \Ivoz\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false