Ivoz\Domain\Model\MediaRelaySet\MediaRelaySetAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    name:
      columns:
        - name
  fields:
    name:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: '0'
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
