Ivoz\Domain\Model\OutgoingRouting\OutgoingRoutingAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
    brandId:
      columns:
        - brandId
    peeringContractId:
      columns:
        - peeringContractId
    routingPatternId:
      columns:
        - routingPatternId
    routingPatternGroupId:
      columns:
        - routingPatternGroupId
  fields:
    type:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: group
    priority:
      type: boolean
      nullable: false
      options:
        unsigned: true
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
  manyToOne:
    brand:
      targetEntity: \Ivoz\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
      orphanRemoval: false
    peeringContract:
      targetEntity: \Ivoz\Domain\Model\PeeringContract\PeeringContractInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        peeringContractId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    routingPattern:
      targetEntity: \Ivoz\Domain\Model\RoutingPattern\RoutingPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingPatternId:
          referencedColumnName: id
      orphanRemoval: false
    routingPatternGroup:
      targetEntity: \Ivoz\Domain\Model\RoutingPatternGroup\RoutingPatternGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingPatternGroupId:
          referencedColumnName: id
      orphanRemoval: false
