Ivoz\Domain\Model\PeeringContract\PeeringContractAbstract:
  type: mappedSuperclass
  indexes:
    brandId:
      columns:
        - brandId
    PeeringContracts_ibfk_2:
      columns:
        - transformationRulesetGroupsTrunksId
  uniqueConstraints:
    name_per_brand:
      columns:
        - name
        - brandId
  fields:
    description:
      type: string
      nullable: false
      length: 500
      options:
        fixed: false
        default: ''
    name:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
    externallyRated:
      type: boolean
      nullable: true
      options:
        default: '0'
      column: externallyRated
  manyToOne:
    brand:
      targetEntity: \Ivoz\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    transformationRulesetGroupsTrunk:
      targetEntity: \Ivoz\Domain\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunkInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        transformationRulesetGroupsTrunksId:
          referencedColumnName: id
      orphanRemoval: false
