Ivoz\Domain\Model\PricingPlansRelCompany\PricingPlansRelCompany:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\PricingPlansRelCompanyDoctrineRepository
  type: entity
  table: PricingPlansRelCompanies
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
