Ivoz\Domain\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPatternAbstract:
  type: mappedSuperclass
  indexes:
    targetPatternId:
      columns:
        - targetPatternId
    brandId:
      columns:
        - brandId
    IDX_CAD1B6B5EDF37044:
      columns:
        - pricingPlanId
  uniqueConstraints:
    pricingPlanId:
      columns:
        - pricingPlanId
        - targetPatternId
  fields:
    connectionCharge:
      type: decimal
      nullable: false
      precision: 10
      scale: 4
      column: connectionCharge
    periodTime:
      type: integer
      nullable: false
      options:
        unsigned: false
      column: periodTime
    perPeriodCharge:
      type: decimal
      nullable: false
      precision: 10
      scale: 4
      column: perPeriodCharge
  manyToOne:
    pricingPlan:
      targetEntity: \Ivoz\Domain\Model\PricingPlan\PricingPlanInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        pricingPlanId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    targetPattern:
      targetEntity: \Ivoz\Domain\Model\TargetPattern\TargetPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        targetPatternId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    brand:
      targetEntity: \Ivoz\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
