Ivoz\Domain\Model\ProxyUser\ProxyUser:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\ProxyUserDoctrineRepository
  type: entity
  table: ProxyUsers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
