Ivoz\Domain\Model\ProxyTrunk\ProxyTrunk:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\ProxyTrunkDoctrineRepository
  type: entity
  table: ProxyTrunks
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
