Ivoz\Domain\Model\Recording\RecordingAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
  embedded:
    recordedFile:
      class: RecordedFile
      columnPrefix: false
  fields:
    callid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    calldate:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
    type:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        comment: '[enum:ondemand|ddi]'
        default: ddi
    duration:
      type: float
      nullable: false
      precision: 10
      scale: 3
      options:
        default: '0.000'
    caller:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    callee:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    recorder:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
#    recordedFileFileSize:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        comment: '[FSO:keepExtension]'
#      column: recordedFileFileSize
#    recordedFileMimeType:
#      type: string
#      nullable: true
#      length: 80
#      options:
#        fixed: false
#      column: recordedFileMimeType
#    recordedFileBaseName:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: recordedFileBaseName
  manyToOne:
    company:
      targetEntity: \Ivoz\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: recordings
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
