Ivoz\Domain\Model\Service\Service:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\ServiceDoctrineRepository
  type: entity
  table: Services
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
