Ivoz\Domain\Model\XMLRPCLog\XMLRPCLog:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\XMLRPCLogDoctrineRepository
  type: entity
  table: XMLRPCLogs
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
