Core\Domain\Model\ApplicationServer\ApplicationServer:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ApplicationServerDoctrineRepository
  type: entity
  table: ApplicationServers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
