Core\Domain\Model\BrandURL\BrandURLAbstract:
  type: mappedSuperclass
  indexes:
    brandId:
      columns:
        - brandId
  uniqueConstraints:
    url:
      columns:
        - url
  embedded:
    logo:
      class: Logo
      columnPrefix: false
  fields:
    url:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    klearTheme:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
        default: ''
      column: klearTheme
    urlType:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        comment: '[enum:god|brand|admin|user]'
      column: urlType
    name:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
        default: ''
#    logoFileSize:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        comment: '[FSO]'
#      column: logoFileSize
#    logoMimeType:
#      type: string
#      nullable: true
#      length: 80
#      options:
#        fixed: false
#      column: logoMimeType
#    logoBaseName:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: logoBaseName
    userTheme:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
        default: ''
      column: userTheme
  manyToOne:
    brand:
      targetEntity: \Core\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: urls
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
