Core\Domain\Model\BrandOperator\BrandOperator:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\BrandOperatorDoctrineRepository
  type: entity
  table: BrandOperators
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
