Core\Model\Calendar\Calendar:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CalendarDoctrineRepository
  type: entity
  table: Calendars
  indexes:
    companyId:
      columns:
        - companyId
  uniqueConstraints:
    nameCompany:
      columns:
        - name
        - companyId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
  manyToOne:
    company:
      targetEntity: \Core\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
