Core\Domain\Model\Calendar\Calendar:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CalendarDoctrineRepository
  type: entity
  table: Calendars
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
