Core\Domain\Model\CallACL\CallACL:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CallACLDoctrineRepository
  type: entity
  table: CallACL
  indexes:
    companyId:
      columns:
        - companyId
  uniqueConstraints:
    companyId_2:
      columns:
        - companyId
        - name
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    defaultPolicy:
      type: string
      nullable: false
      length: 10
      options:
        fixed: false
        comment: '[enum:allow|deny]'
      column: defaultPolicy
  manyToOne:
    company:
      targetEntity: \Core\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
