Core\Model\CallACLRelPattern\CallACLRelPattern:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CallACLRelPatternDoctrineRepository
  type: entity
  table: CallACLRelPatterns
  indexes:
    CallACLId:
      columns:
        - CallACLId
    CallACLPatternId:
      columns:
        - CallACLPatternId
  uniqueConstraints:
    unique_callACLId_priority:
      columns:
        - CallACLId
        - priority
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    priority:
      type: smallint
      nullable: false
      options:
        unsigned: false
    policy:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        comment: '[enum:allow|deny]'
  manyToOne:
    callACL:
      targetEntity: \Core\Model\CallACL\CallACLInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        CallACLId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    callACLPattern:
      targetEntity: \Core\Model\CallACLPattern\CallACLPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        CallACLPatternId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
