Core\Domain\Model\CallACLPattern\CallACLPattern:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CallACLPatternDoctrineRepository
  type: entity
  table: CallACLPatterns
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
