Core\Domain\Model\ChangeHistory\ChangeHistory:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ChangeHistoryDoctrineRepository
  type: entity
  table: ChangeHistory
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
