Core\Domain\Model\ChangeHistory\ChangeHistoryAbstract:
  type: mappedSuperclass
  fields:
    user:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    date:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
    action:
      type: string
      nullable: false
      length: 15
      options:
        fixed: false
    table:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    objid:
      type: integer
      nullable: false
      options:
        unsigned: true
    field:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    oldValue:
      type: string
      nullable: true
      length: 250
      options:
        fixed: false
      column: old_value
    newValue:
      type: string
      nullable: true
      length: 250
      options:
        fixed: false
      column: new_value

