Core\Domain\Model\CompanyAdmin\CompanyAdmin:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CompanyAdminDoctrineRepository
  type: entity
  table: CompanyAdmins
  indexes:
    companyId:
      columns:
        - companyId
    timezoneId:
      columns:
        - timezoneId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    username:
      type: string
      nullable: false
      length: 65
      options:
        fixed: false
    pass:
      type: string
      nullable: false
      length: 80
      options:
        fixed: false
        comment: '[password]'
    email:
      type: string
      nullable: false
      length: 100
      options:
        fixed: false
        default: ''
    active:
      type: boolean
      nullable: true
      options:
        default: '1'
    name:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    lastname:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
  manyToOne:
    company:
      targetEntity: \Core\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    timezone:
      targetEntity: \Core\Domain\Model\Timezone\TimezoneInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        timezoneId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
