Core\Model\ConferenceRoom\ConferenceRoom:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ConferenceRoomDoctrineRepository
  type: entity
  table: ConferenceRooms
  indexes:
    companyId:
      columns:
        - companyId
  uniqueConstraints:
    ConferenceRoomsUniqueCompanyname:
      columns:
        - companyId
        - name
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    pinProtected:
      type: boolean
      nullable: false
      options:
        default: '0'
        unsigned: true
      column: pinProtected
    pinCode:
      type: string
      nullable: true
      length: 6
      options:
        fixed: false
      column: pinCode
    maxMembers:
      type: boolean
      nullable: false
      options:
        default: '0'
        unsigned: true
      column: maxMembers
  manyToOne:
    company:
      targetEntity: \Core\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
