Core\Domain\Model\Country\Country:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\CountryDoctrineRepository
  type: entity
  table: Countries
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
