Core\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ExternalCallFilterRelScheduleDoctrineRepository
  type: entity
  table: ExternalCallFilterRelSchedules
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
