Core\Model\Fax\Fax:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\FaxDoctrineRepository
  type: entity
  table: Faxes
  indexes:
    companyId:
      columns:
        - companyId
    outgoingDDIId:
      columns:
        - outgoingDDIId
  uniqueConstraints:
    FaxesUniqueCompanyfaxname:
      columns:
        - companyId
        - name
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      column: name
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    email:
      column: email
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    sendByEmail:
      type: boolean
      nullable: false
      options:
        default: '1'
        unsigned: true
      column: sendByEmail
  manyToOne:
    company:
      targetEntity: \Core\Model\Company\Company
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    outgoingDDI:
      targetEntity: \Core\Model\DDI\DDI
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        outgoingDDIId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
