Core\Domain\Model\Fax\Fax:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\FaxDoctrineRepository
  type: entity
  table: Faxes
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
