Core\Domain\Model\Fax\FaxAbstract:
  type: mappedSuperclass
  indexes:
    companyId:
      columns:
        - companyId
    outgoingDDIId:
      columns:
        - outgoingDDIId
  uniqueConstraints:
    FaxesUniqueCompanyfaxname:
      columns:
        - companyId
        - name
  fields:
    name:
      column: name
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    email:
      column: email
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    sendByEmail:
      type: boolean
      nullable: false
      options:
        default: '1'
        unsigned: true
      column: sendByEmail
  manyToOne:
    company:
      targetEntity: \Core\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    outgoingDDI:
      targetEntity: \Core\Domain\Model\DDI\DDIInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        outgoingDDIId:
          referencedColumnName: id
      orphanRemoval: false
