Core\Model\FeaturesRelBrand\FeaturesRelBrand:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\FeaturesRelBrandDoctrineRepository
  type: entity
  table: FeaturesRelBrands
  indexes:
    brandId:
      columns:
        - brandId
    featureId:
      columns:
        - featureId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  manyToOne:
    brand:
      targetEntity: \Core\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: featuresRels
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    feature:
      targetEntity: \Core\Model\Feature\FeatureInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        featureId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
