Core\Model\FeaturesRelCompany\FeaturesRelCompany:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\FeaturesRelCompanyDoctrineRepository
  type: entity
  table: FeaturesRelCompanies
  indexes:
    companyId:
      columns:
        - companyId
    featureId:
      columns:
        - featureId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  manyToOne:
    company:
      targetEntity: \Core\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    feature:
      targetEntity: \Core\Model\Feature\FeatureInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        featureId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
