Core\Domain\Model\FeaturesRelBrand\FeaturesRelBrand:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\FeaturesRelBrandDoctrineRepository
  type: entity
  table: FeaturesRelBrands
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
