Core\Domain\Model\FeaturesRelCompany\FeaturesRelCompany:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\FeaturesRelCompanyDoctrineRepository
  type: entity
  table: FeaturesRelCompanies
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
