Core\Domain\Model\HuntGroup\HuntGroup:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\HuntGroupDoctrineRepository
  type: entity
  table: HuntGroups
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
