Core\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUser:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\HuntGroupsRelUserDoctrineRepository
  type: entity
  table: HuntGroupsRelUsers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
