Core\Domain\Model\Invoice\Invoice:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\InvoiceDoctrineRepository
  type: entity
  table: Invoices
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
