Core\Domain\Model\Invoice\InvoiceAbstract:
  type: mappedSuperclass
  indexes:
    brandId:
      columns:
        - brandId
    companyId:
      columns:
        - companyId
    invoiceTemplateId:
      columns:
        - invoiceTemplateId
  uniqueConstraints:
    numberBrand:
      columns:
        - number
        - brandId
  embedded:
    pdf:
      class: Pdf
      columnPrefix: false
  fields:
    number:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
    inDate:
      type: datetime
      nullable: true
      column: inDate
    outDate:
      type: datetime
      nullable: true
      column: outDate
    total:
      type: decimal
      nullable: true
      precision: 10
      scale: 3
    taxRate:
      type: decimal
      nullable: true
      precision: 10
      scale: 3
      column: taxRate
    totalWithTax:
      type: decimal
      nullable: true
      precision: 10
      scale: 3
      column: totalWithTax
    status:
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
        comment: '[enum:waiting|processing|created|error]'
#    pdfFileFileSize:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        comment: '[FSO]'
#      column: pdfFileFileSize
#    pdfFileMimeType:
#      type: string
#      nullable: true
#      length: 80
#      options:
#        fixed: false
#      column: pdfFileMimeType
#    pdfFileBaseName:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: pdfFileBaseName
  manyToOne:
    brand:
      targetEntity: \Core\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    company:
      targetEntity: \Core\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    invoiceTemplate:
      targetEntity: \Core\Domain\Model\InvoiceTemplate\InvoiceTemplate
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        invoiceTemplateId:
          referencedColumnName: id
      orphanRemoval: false
