Core\Domain\Model\LcrGateway\LcrGateway:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\LcrGatewayDoctrineRepository
  type: entity
  table: LcrGateways
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
