Core\Domain\Model\LcrGateway\LcrGateway:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\LcrGatewayDoctrineRepository
  type: entity
  table: LcrGateways
  indexes:
    peerServerId:
      columns:
        - peerServerId
    lcr_id:
      columns:
        - lcr_id
  uniqueConstraints:
    peerServerIdUnique:
      columns:
        - peerServerId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    lcrId:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
      column: lcr_id
    gwName:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
      column: gw_name
    ip:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
    hostname:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    port:
      type: smallint
      nullable: true
      options:
        unsigned: true
    params:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    uriScheme:
      type: boolean
      nullable: true
      column: uri_scheme
      options:
        unsigned: true
    transport:
      type: boolean
      nullable: true
      options:
        unsigned: true
    strip:
      type: boolean
      nullable: true
      options:
        unsigned: true
    prefix:
      type: string
      nullable: true
      length: 16
      options:
        fixed: false
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    flags:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
    defunct:
      type: integer
      nullable: true
      options:
        unsigned: true
  manyToOne:
    peerServer:
      targetEntity: \Core\Domain\Model\PeerServer\PeerServerInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        peerServerId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
