Core\Model\LcrRuleTarget\LcrRuleTarget:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\LcrRuleTargetDoctrineRepository
  type: entity
  table: LcrRuleTargets
  indexes:
    rule_id:
      columns:
        - rule_id
    gw_id:
      columns:
        - gw_id
    outgoingRoutingId:
      columns:
        - outgoingRoutingId
    lcr_id:
      columns:
        - lcr_id
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    lcrId:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
      column: lcr_id
    priority:
      type: boolean
      nullable: false
      options:
        unsigned: true
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
  manyToOne:
    rule:
      targetEntity: \Core\Model\LcrRule\LcrRuleInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        rule_id:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    gw:
      targetEntity: \Core\Model\LcrGateway\LcrGatewayInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        gw_id:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    outgoingRouting:
      targetEntity: \Core\Model\OutgoingRouting\OutgoingRoutingInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        outgoingRoutingId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
