Core\Domain\Model\Locution\Locution:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\LocutionDoctrineRepository
  type: entity
  table: Locutions
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
