Core\Domain\Model\Locution\OriginalFile:
  type: embeddable
  fields:
    fileSize:
      type: integer
      nullable: true
      options:
        unsigned: true
        comment: '[FSO:keepExtension]'
      column: originalFileFileSize
    mimeType:
      type: string
      nullable: true
      length: 80
      options:
        fixed: false
      column: originalFileMimeType
    baseName:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: originalFileBaseName
