Core\Domain\Model\MainOperator\MainOperator:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\MainOperatorDoctrineRepository
  type: entity
  table: MainOperators
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
