Core\Domain\Model\MediaRelaySet\MediaRelaySet:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\MediaRelaySetDoctrineRepository
  type: entity
  table: MediaRelaySets
  uniqueConstraints:
    name:
      columns:
        - name
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: '0'
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
  lifecycleCallbacks: {  }
