Core\Model\OutgoingRouting\OutgoingRouting:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\OutgoingRoutingDoctrineRepository
  type: entity
  table: OutgoingRouting
  indexes:
    companyId:
      columns:
        - companyId
    brandId:
      columns:
        - brandId
    peeringContractId:
      columns:
        - peeringContractId
    routingPatternId:
      columns:
        - routingPatternId
    routingPatternGroupId:
      columns:
        - routingPatternGroupId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    type:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: group
    priority:
      type: boolean
      nullable: false
      options:
        unsigned: true
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
  manyToOne:
    brand:
      targetEntity: \Core\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    company:
      targetEntity: \Core\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
      orphanRemoval: false
    peeringContract:
      targetEntity: \Core\Model\PeeringContract\PeeringContractInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        peeringContractId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    routingPattern:
      targetEntity: \Core\Model\RoutingPattern\RoutingPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingPatternId:
          referencedColumnName: id
      orphanRemoval: false
    routingPatternGroup:
      targetEntity: \Core\Model\RoutingPatternGroup\RoutingPatternGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingPatternGroupId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
