Core\Domain\Model\ParsedCDR\ParsedCDR:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ParsedCDRDoctrineRepository
  type: entity
  table: ParsedCDRs
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
