Core\Domain\Model\PeerServer\PeerServer:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\PeerServerDoctrineRepository
  type: entity
  table: PeerServers
  indexes:
    peeringContractId:
      columns:
        - peeringContractId
    brandId:
      columns:
        - brandId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    ip:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
    name:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
    description:
      type: string
      nullable: false
      length: 500
      options:
        fixed: false
        default: ''
    hostname:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    port:
      type: smallint
      nullable: true
      options:
        unsigned: true
    params:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    uriScheme:
      type: boolean
      nullable: true
      column: uri_scheme
      options:
        unsigned: true
    transport:
      type: boolean
      nullable: true
      options:
        unsigned: true
    strip:
      type: boolean
      nullable: true
      options:
        unsigned: true
    prefix:
      type: string
      nullable: true
      length: 16
      options:
        fixed: false
    sendPAI:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
      column: sendPAI
    sendRPID:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
      column: sendRPID
    authNeeded:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        default: 'no'
      column: auth_needed
    authUser:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: auth_user
    authPassword:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: auth_password
    sipProxy:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: sip_proxy
    outboundProxy:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: outbound_proxy
    fromUser:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: from_user
    fromDomain:
      type: string
      nullable: true
      length: 190
      options:
        fixed: false
      column: from_domain
  manyToOne:
    peeringContract:
      targetEntity: \Core\Domain\Model\PeeringContract\PeeringContractInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        peeringContractId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    brand:
      targetEntity: \Core\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
