Core\Domain\Model\PricingPlan\Description:
  type: embeddable
  fields:
    description:
      type: string
      nullable: false
      length: 55
      options:
        fixed: false
        comment: '[ml]'
    en:
      type: string
      nullable: false
      length: 55
      options:
        fixed: false
      column: description_en
    es:
      type: string
      nullable: false
      length: 55
      options:
        fixed: false
      column: description_es
