Core\Domain\Model\ProxyTrunk\ProxyTrunk:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ProxyTrunkDoctrineRepository
  type: entity
  table: ProxyTrunks
  uniqueConstraints:
    ip:
      columns:
        - ip
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    ip:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
  lifecycleCallbacks: {  }
