Core\Domain\Model\QueueMember\QueueMemberAbstract:
  type: mappedSuperclass
  indexes:
    queueId:
      columns:
        - queueId
    userId:
      columns:
        - userId
  fields:
    penalty:
      type: integer
      nullable: true
      options:
        unsigned: false
  manyToOne:
    queue:
      targetEntity: \Core\Domain\Model\Queue\QueueInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        queueId:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: \Core\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        userId:
          referencedColumnName: id
      orphanRemoval: false
