Core\Domain\Model\QueueMember\QueueMember:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\QueueMemberDoctrineRepository
  type: entity
  table: QueueMembers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
