Core\Domain\Model\Recording\RecordedFile:
  type: embeddable
  fields:
    fileSize:
      type: integer
      nullable: true
      options:
        unsigned: true
        comment: '[FSO:keepExtension]'
      column: recordedFileFileSize
    mimeType:
      type: string
      nullable: true
      length: 80
      options:
        fixed: false
      column: recordedFileMimeType
    baseName:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: recordedFileBaseName
