Core\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPatternAbstract:
  type: mappedSuperclass
  indexes:
    routingPatternId:
      columns:
        - routingPatternId
    routingPatternGroupId:
      columns:
        - routingPatternGroupId
  uniqueConstraints:
    rel:
      columns:
        - routingPatternId
        - routingPatternGroupId
  manyToOne:
    routingPattern:
      targetEntity: \Core\Domain\Model\RoutingPattern\RoutingPatternInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        routingPatternId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    routingPatternGroup:
      targetEntity: \Core\Domain\Model\RoutingPatternGroup\RoutingPatternGroupInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relPatterns
      joinColumns:
        routingPatternGroupId:
          referencedColumnName: id
          unsigned: false
          nullable: false
      orphanRemoval: false
