Core\Model\Schedule\Schedule:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\ScheduleDoctrineRepository
  type: entity
  table: Schedules
  indexes:
    companyId:
      columns:
        - companyId
  uniqueConstraints:
    nameCompany:
      columns:
        - name
        - companyId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    timeIn:
      type: time
      nullable: false
      column: timeIn
    timeout:
      type: time
      nullable: false
    monday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
    tuesday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
    wednesday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
    thursday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
    friday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
    saturday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
    sunday:
      type: boolean
      nullable: true
      options:
        default: '0'
        unsigned: true
  manyToOne:
    company:
      targetEntity: \Core\Model\Company\Company
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
