Core\Domain\Model\TerminalModel\TerminalModel:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\TerminalModelDoctrineRepository
  type: entity
  table: TerminalModels
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
