Core\Domain\Model\Terminal\Terminal:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\TerminalDoctrineRepository
  type: entity
  table: Terminals
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
