Core\Domain\Model\TerminalModel\TerminalModel:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\TerminalModelDoctrineRepository
  type: entity
  table: TerminalModels
  indexes:
    TerminalManufacturerId:
      columns:
        - TerminalManufacturerId
  uniqueConstraints:
    iden:
      columns:
        - iden
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    iden:
      type: string
      nullable: false
      length: 100
      options:
        fixed: false
    name:
      type: string
      nullable: false
      length: 100
      options:
        fixed: false
        default: ''
    description:
      type: string
      nullable: false
      length: 500
      options:
        fixed: false
        default: ''
    genericTemplate:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: genericTemplate
    specificTemplate:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: specificTemplate
    genericUrlPattern:
      type: string
      nullable: true
      length: 225
      options:
        fixed: false
      column: genericUrlPattern
    specificUrlPattern:
      type: string
      nullable: true
      length: 225
      options:
        fixed: false
      column: specificUrlPattern
  manyToOne:
    TerminalManufacturer:
      targetEntity: \Core\Domain\Model\TerminalManufacturer\TerminalManufacturerInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        TerminalManufacturerId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
