Core\Domain\Model\Terminal\Terminal:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\TerminalDoctrineRepository
  type: entity
  table: Terminals
  indexes:
    TerminalModelId:
      columns:
        - TerminalModelId
    Terminals_CompanyId_ibfk_2:
      columns:
        - companyId
    name_domain_idx:
      columns:
        - name
        - domain
  uniqueConstraints:
    name_domain:
      columns:
        - name
        - domain
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: true
      length: 100
      options:
        fixed: false
    domain:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    disallow:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
        default: all
    allow_audio:
      type: string
      nullable: false
      length: 200
      options:
        fixed: false
        default: alaw
    allow_video:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
    directMediaMethod:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        comment: '[enum:update|invite|reinvite]'
        default: update
      column: direct_media_method
    password:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        comment: '[password]'
        default: ''
    mac:
      type: string
      nullable: true
      length: 12
      options:
        fixed: false
    lastProvisionDate:
      type: datetime
      nullable: true
      column: lastProvisionDate
  manyToOne:
    company:
      targetEntity: \Core\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    TerminalModel:
      targetEntity: \Core\Domain\Model\TerminalModel\TerminalModelInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        TerminalModelId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
