Core\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunk:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\TransformationRulesetGroupsTrunkDoctrineRepository
  type: entity
  table: TransformationRulesetGroupsTrunks
  indexes:
    brandId:
      columns:
        - brandId
    countryId:
      columns:
        - countryId
  uniqueConstraints:
    name_brand:
      columns:
        - name
        - brandId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 100
      options:
        fixed: false
    callerIn:
      type: integer
      nullable: true
      options:
        unsigned: false
      column: caller_in
    calleeIn:
      type: integer
      nullable: true
      options:
        unsigned: false
      column: callee_in
    callerOut:
      type: integer
      nullable: true
      options:
        unsigned: false
      column: caller_out
    calleeOut:
      type: integer
      nullable: true
      options:
        unsigned: false
      column: callee_out
    description:
      type: string
      nullable: false
      length: 500
      options:
        fixed: false
        default: ''
    automatic:
      type: boolean
      nullable: false
      options:
        default: '0'
        unsigned: true
    internationalCode:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
      column: internationalCode
    nationalNumLength:
      type: integer
      nullable: true
      options:
        unsigned: true
      column: nationalNumLength
  manyToOne:
    brand:
      targetEntity: \Core\Model\Brand\Brand
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    country:
      targetEntity: \Core\Model\Country\Country
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        countryId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
