Core\Domain\Model\User\User:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\UserDoctrineRepository
  type: entity
  table: Users
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
