Core\Domain\Model\XMLRPCLog\XMLRPCLog:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\XMLRPCLogDoctrineRepository
  type: entity
  table: XMLRPCLogs
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    proxy:
      type: string
      nullable: false
      length: 10
      options:
        fixed: false
    module:
      type: string
      nullable: false
      length: 10
      options:
        fixed: false
    method:
      type: string
      nullable: false
      length: 10
      options:
        fixed: false
    mapperName:
      type: string
      nullable: false
      length: 20
      options:
        fixed: false
      column: mapperName
    startDate:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: startDate
    execDate:
      type: datetime
      nullable: true
      column: execDate
    finishDate:
      type: datetime
      nullable: true
      column: finishDate
  lifecycleCallbacks: {  }
