Kam\Domain\Model\Dispatcher\DispatcherAbstract:
  type: mappedSuperclass
  indexes:
    applicationServerId:
      columns:
        - applicationServerId
  fields:
    setid:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    destination:
      type: string
      nullable: false
      length: 192
      options:
        fixed: false
        default: ''
    flags:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    priority:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    attrs:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
        default: ''
    description:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
  manyToOne:
    applicationServer:
      targetEntity: \Core\Domain\Model\ApplicationServer\ApplicationServerInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        applicationServerId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
