Kam\Model\KamAccCdr\KamAccCdr:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\KamAccCdrDoctrineRepository
  type: entity
  table: kam_acc_cdrs
  indexes:
    start_time_idx:
      columns:
        - start_time
    calldate_idx:
      columns:
        - end_time_utc
    callid_idx:
      columns:
        - callid
    xcallid_idx:
      columns:
        - xcallid
    peeringContractId_idx:
      columns:
        - peeringContractId
    pricingPlanId:
      columns:
        - pricingPlanId
    targetPatternId:
      columns:
        - targetPatternId
    invoiceId:
      columns:
        - invoiceId
    brandId:
      columns:
        - brandId
    companyId:
      columns:
        - companyId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    proxy:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    startTimeUtc:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: start_time_utc
    endTimeUtc:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: end_time_utc
    startTime:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: start_time
    endTime:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: end_time
    duration:
      type: float
      nullable: false
      precision: 10
      scale: 3
      options:
        default: '0.000'
    caller:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    callee:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    referee:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    referrer:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    asiden:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: asIden
    asaddress:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: asAddress
    callid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    callidhash:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: callidHash
    xcallid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    parsed:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        default: 'no'
    diversion:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    peeringcontractid:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: peeringContractId
    bounced:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
        default: 'no'
    externallyrated:
      type: boolean
      nullable: true
      column: externallyRated
    metered:
      type: boolean
      nullable: true
      options:
        default: '0'
    meteringdate:
      type: datetime
      nullable: true
      options:
        default: '0000-00-00 00:00:00'
      column: meteringDate
    pricingplanname:
      type: string
      nullable: true
      length: 55
      options:
        fixed: false
      column: pricingPlanName
    targetpatternname:
      type: string
      nullable: true
      length: 55
      options:
        fixed: false
      column: targetPatternName
    price:
      type: decimal
      nullable: true
      precision: 10
      scale: 4
    pricingplandetails:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: pricingPlanDetails
    direction:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
    remeteringdate:
      type: datetime
      nullable: true
      column: reMeteringDate
  manyToOne:
    pricingPlan:
      targetEntity: \Core\Model\PricingPlan\PricingPlan
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        pricingPlanId:
          referencedColumnName: id
      orphanRemoval: false
    targetPattern:
      targetEntity: \Core\Model\TargetPattern\TargetPattern
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        targetPatternId:
          referencedColumnName: id
      orphanRemoval: false
    invoice:
      targetEntity: \Core\Model\Invoice\Invoice
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        invoiceId:
          referencedColumnName: id
      orphanRemoval: false
    brand:
      targetEntity: \Core\Model\Brand\Brand
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
      orphanRemoval: false
    company:
      targetEntity: \Core\Model\Company\Company
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
