Kam\Model\KamUsersLocation\KamUsersLocation:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\KamUsersLocationDoctrineRepository
  type: entity
  table: kam_users_location
  indexes:
    account_contact_idx:
      columns:
        - username
        - domain
        - contact
    expires_idx:
      columns:
        - expires
  uniqueConstraints:
    ruid_idx:
      columns:
        - ruid
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    ruid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
    username:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
    domain:
      type: string
      nullable: true
      length: 190
      options:
        fixed: false
    contact:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    received:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    path:
      type: string
      nullable: true
      length: 512
      options:
        fixed: false
    expires:
      type: datetime
      nullable: false
      options:
        default: '2030-05-28 21:32:15'
    q:
      type: float
      nullable: false
      precision: 10
      scale: 2
      options:
        default: '1.00'
    callid:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: Default-Call-ID
    cseq:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '1'
    lastModified:
      type: datetime
      nullable: false
      options:
        default: '1900-01-01 00:00:01'
      column: last_modified
    flags:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    cflags:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    userAgent:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
      column: user_agent
    socket:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    methods:
      type: integer
      nullable: true
      options:
        unsigned: false
    instance:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    regId:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
      column: reg_id
    serverId:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
      column: server_id
    connectionId:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
      column: connection_id
    keepalive:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    partition:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
  lifecycleCallbacks: {  }
