Kam\Model\KamUsersXcap\KamUsersXcap:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\KamUsersXcapDoctrineRepository
  type: entity
  table: kam_users_xcap
  indexes:
    account_doc_type_idx:
      columns:
        - username
        - domain
        - doc_type
    account_doc_type_uri_idx:
      columns:
        - username
        - domain
        - doc_type
        - doc_uri
    account_doc_uri_idx:
      columns:
        - username
        - domain
        - doc_uri
  uniqueConstraints:
    doc_uri_idx:
      columns:
        - doc_uri
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    username:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    domain:
      type: string
      nullable: false
      length: 190
      options:
        fixed: false
    doc:
      type: blob
      nullable: false
      length: 16777215
      options:
        fixed: false
    docType:
      type: integer
      nullable: false
      options:
        unsigned: false
      column: doc_type
    etag:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    source:
      type: integer
      nullable: false
      options:
        unsigned: false
    docUri:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: doc_uri
    port:
      type: integer
      nullable: false
      options:
        unsigned: false
  lifecycleCallbacks: {  }
