Kam\Domain\Model\PikeTrusted\PikeTrusted:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\PikeTrustedDoctrineRepository
  type: entity
  table: kam_pike_trusted
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
