Kam\Domain\Model\Rtpproxy\RtpproxyAbstract:
  type: mappedSuperclass
  indexes:
    mediaRelaySetsId:
      columns:
        - mediaRelaySetsId
  fields:
    setid:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: '0'
    url:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
    flags:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
  manyToOne:
    mediaRelaySet:
      targetEntity: \Core\Domain\Model\MediaRelaySet\MediaRelaySetInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        mediaRelaySetsId:
          referencedColumnName: id
      orphanRemoval: false
