Kam\Domain\Model\TrunksDomainAttr\TrunksDomainAttrAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    domain_attrs_idx:
      columns:
        - did
        - name
        - value
  fields:
    did:
      type: string
      nullable: false
      length: 190
      options:
        fixed: false
    name:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
    type:
      type: integer
      nullable: false
      options:
        unsigned: true
    value:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    lastModified:
      type: datetime
      nullable: false
      options:
        default: '1900-01-01 00:00:01'
      column: last_modified
