Kam\Domain\Model\TrunksAddres\TrunksAddres:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\TrunksAddresDoctrineRepository
  type: entity
  table: kam_trunks_address
  uniqueConstraints:
    grp:
      columns:
        - grp
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    grp:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
    ipAddr:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: ip_addr
    mask:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '32'
    port:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
  lifecycleCallbacks: {  }
