Kam\Domain\Model\UsersMissedCall\UsersMissedCall:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\UsersMissedCallDoctrineRepository
  type: entity
  table: kam_users_missed_calls
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
