Kam\Model\UsersActiveWatcher\UsersActiveWatcher:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\UsersActiveWatcherDoctrineRepository
  type: entity
  table: kam_users_active_watchers
  indexes:
    kam_users_active_watchers_expires:
      columns:
        - expires
    kam_users_active_watchers_pres:
      columns:
        - presentity_uri
        - event
    updated_idx:
      columns:
        - updated
    updated_winfo_idx:
      columns:
        - updated_winfo
        - presentity_uri
  uniqueConstraints:
    kam_users_active_watchers_idx:
      columns:
        - callid
        - to_tag
        - from_tag
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    presentityUri:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
      column: presentity_uri
    watcherUsername:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: watcher_username
    watcherDomain:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: watcher_domain
    toUser:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: to_user
    toDomain:
      type: string
      nullable: false
      length: 190
      options:
        fixed: false
      column: to_domain
    event:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: presence
    eventId:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
      column: event_id
    toTag:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: to_tag
    fromTag:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: from_tag
    callid:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    localCseq:
      type: integer
      nullable: false
      options:
        unsigned: false
      column: local_cseq
    remoteCseq:
      type: integer
      nullable: false
      options:
        unsigned: false
      column: remote_cseq
    contact:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
    recordRoute:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: record_route
    expires:
      type: integer
      nullable: false
      options:
        unsigned: false
    status:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '2'
    reason:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
    version:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    socketInfo:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: socket_info
    localContact:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
      column: local_contact
    fromUser:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: from_user
    fromDomain:
      type: string
      nullable: false
      length: 190
      options:
        fixed: false
      column: from_domain
    updated:
      type: integer
      nullable: false
      options:
        unsigned: false
    updatedWinfo:
      type: integer
      nullable: false
      options:
        unsigned: false
      column: updated_winfo
    flags:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    userAgent:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
      column: user_agent
  lifecycleCallbacks: {  }
