Kam\Domain\Model\UsersLocationAttr\UsersLocationAttrAbstract:
  type: mappedSuperclass
  indexes:
    account_record_idx:
      columns:
        - username
        - domain
        - ruid
    last_modified_idx:
      columns:
        - last_modified
  fields:
    ruid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
    username:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
    domain:
      type: string
      nullable: true
      length: 190
      options:
        fixed: false
    aname:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
    atype:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    avalue:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    lastModified:
      type: datetime
      nullable: false
      options:
        default: '1900-01-01 00:00:01'
      column: last_modified
