Kam\Domain\Model\UsersPresentity\UsersPresentity:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\UsersPresentityDoctrineRepository
  type: entity
  table: kam_users_presentity
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
