Kam\Domain\Model\UsersAcc\UsersAcc:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\UsersAccDoctrineRepository
  type: entity
  table: kam_users_acc
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
