<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170626133147 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE PeeringContracts DROP FOREIGN KEY PeeringContracts_ibfk_1');
        $this->addSql('ALTER TABLE PeeringContracts DROP FOREIGN KEY PeeringContracts_ibfk_2');
        $this->addSql('ALTER TABLE PeeringContracts ADD CONSTRAINT FK_6E479B029CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE PeeringContracts ADD CONSTRAINT FK_6E479B022D92AF39 FOREIGN KEY (transformationRulesetGroupsTrunksId) REFERENCES TransformationRulesetGroupsTrunks (id)');
        $this->addSql('ALTER TABLE FriendsPatterns DROP FOREIGN KEY FriendsPatterns_ibfk_1');
        $this->addSql('ALTER TABLE FriendsPatterns ADD CONSTRAINT FK_933D96E5893BA339 FOREIGN KEY (friendId) REFERENCES Friends (id)');
        $this->addSql('ALTER TABLE FeaturesRelCompanies DROP FOREIGN KEY FeaturesRelCompanies_ibfk_1');
        $this->addSql('ALTER TABLE FeaturesRelCompanies DROP FOREIGN KEY FeaturesRelCompanies_ibfk_2');
        $this->addSql('ALTER TABLE FeaturesRelCompanies ADD CONSTRAINT FK_2C2CF4D92480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE FeaturesRelCompanies ADD CONSTRAINT FK_2C2CF4D9397515B7 FOREIGN KEY (featureId) REFERENCES Features (id)');
        $this->addSql('ALTER TABLE CompanyServices DROP FOREIGN KEY CompanyServices_ibfk_1');
        $this->addSql('ALTER TABLE CompanyServices DROP FOREIGN KEY CompanyServices_ibfk_2');
        $this->addSql('ALTER TABLE CompanyServices ADD CONSTRAINT FK_569B460B2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE CompanyServices ADD CONSTRAINT FK_569B460B89697FA8 FOREIGN KEY (serviceId) REFERENCES Services (id)');
        $this->addSql('ALTER TABLE LcrGateways DROP FOREIGN KEY LcrGateways_ibfk_2');
        $this->addSql('ALTER TABLE LcrGateways ADD CONSTRAINT FK_14A48EA095319D46 FOREIGN KEY (peerServerId) REFERENCES PeerServers (id)');
        $this->addSql('ALTER TABLE Terminals DROP FOREIGN KEY Terminals_CompanyId_ibfk_2');
        $this->addSql('ALTER TABLE Terminals DROP FOREIGN KEY Terminals_ibfk_1');
        $this->addSql('ALTER TABLE Terminals ADD CONSTRAINT FK_98AB47BB2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Terminals ADD CONSTRAINT FK_98AB47BB96B6775 FOREIGN KEY (TerminalModelId) REFERENCES TerminalModels (id)');
        $this->addSql('ALTER TABLE LcrRules DROP FOREIGN KEY LcrRules_ibfk_4');
        $this->addSql('ALTER TABLE LcrRules DROP FOREIGN KEY LcrRules_ibfk_5');
        $this->addSql('ALTER TABLE LcrRules ADD CONSTRAINT FK_69DDB35C6D661974 FOREIGN KEY (routingPatternId) REFERENCES RoutingPatterns (id)');
        $this->addSql('ALTER TABLE LcrRules ADD CONSTRAINT FK_69DDB35C3CDE892 FOREIGN KEY (outgoingRoutingId) REFERENCES OutgoingRouting (id)');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_1');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_2');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_3');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_4');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_5');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_6');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY Extensions_ibfk_7');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F792480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F796B600F71 FOREIGN KEY (IVRCommonId) REFERENCES IVRCommon (id)');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F79FEA4E4B0 FOREIGN KEY (IVRCustomId) REFERENCES IVRCustom (id)');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F79921B2343 FOREIGN KEY (huntGroupId) REFERENCES HuntGroups (id)');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F7923E42D0D FOREIGN KEY (conferenceRoomId) REFERENCES ConferenceRooms (id)');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F7964B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT FK_9AAD9F79A4D768C6 FOREIGN KEY (queueId) REFERENCES Queues (id)');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules DROP FOREIGN KEY ExternalCallFilterRelSchedules_ibfk_1');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules DROP FOREIGN KEY ExternalCallFilterRelSchedules_ibfk_2');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules ADD CONSTRAINT FK_9DD35E602E051C4F FOREIGN KEY (filterId) REFERENCES ExternalCallFilters (id)');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules ADD CONSTRAINT FK_9DD35E60B745014E FOREIGN KEY (scheduleId) REFERENCES Schedules (id)');
        $this->addSql('ALTER TABLE LcrRuleTargets DROP FOREIGN KEY LcrRuleTargets_ibfk_2');
        $this->addSql('ALTER TABLE LcrRuleTargets DROP FOREIGN KEY LcrRuleTargets_ibfk_3');
        $this->addSql('ALTER TABLE LcrRuleTargets DROP FOREIGN KEY LcrRuleTargets_ibfk_4');
        $this->addSql('ALTER TABLE LcrRuleTargets ADD CONSTRAINT FK_2EC3B847744E0351 FOREIGN KEY (rule_id) REFERENCES LcrRules (id)');
        $this->addSql('ALTER TABLE LcrRuleTargets ADD CONSTRAINT FK_2EC3B84782D8D847 FOREIGN KEY (gw_id) REFERENCES LcrGateways (id)');
        $this->addSql('ALTER TABLE LcrRuleTargets ADD CONSTRAINT FK_2EC3B8473CDE892 FOREIGN KEY (outgoingRoutingId) REFERENCES OutgoingRouting (id)');
        $this->addSql('ALTER TABLE TargetPatterns DROP FOREIGN KEY TargetPatterns_ibfk_1');
        $this->addSql('ALTER TABLE TargetPatterns ADD CONSTRAINT FK_9A9F9F489CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_1');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_2');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_3');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_4');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_5');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_6');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_7');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY ExternalCallFilters_ibfk_8');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED92480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED92ECAF600 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED99FB29831 FOREIGN KEY (holidayLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED9D4FFE2F7 FOREIGN KEY (outOfScheduleLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED9888E38DB FOREIGN KEY (holidayExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED9FAC21224 FOREIGN KEY (outOfScheduleExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED9DF7207AC FOREIGN KEY (holidayVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT FK_528CEED9D66AD272 FOREIGN KEY (outOfScheduleVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE Locutions DROP FOREIGN KEY Locutions_ibfk_1');
        $this->addSql('ALTER TABLE Locutions ADD CONSTRAINT FK_D5088942480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE RoutingPatterns DROP FOREIGN KEY RoutingPatterns_ibfk_1');
        $this->addSql('ALTER TABLE RoutingPatterns ADD CONSTRAINT FK_FA5E087B9CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE BrandURLs DROP FOREIGN KEY BrandURLs_ibfk_1');
        $this->addSql('ALTER TABLE BrandURLs ADD CONSTRAINT FK_8DBE74F59CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE TerminalModels DROP FOREIGN KEY TerminalModels_ibfk_1');
        $this->addSql('ALTER TABLE TerminalModels ADD CONSTRAINT FK_144DF7FCCFFDBE50 FOREIGN KEY (TerminalManufacturerId) REFERENCES TerminalManufacturers (id)');
        $this->addSql('ALTER TABLE Calendars DROP FOREIGN KEY Calendars_ibfk_1');
        $this->addSql('ALTER TABLE Calendars ADD CONSTRAINT FK_62E00AC2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE PeerServers DROP FOREIGN KEY PeerServers_ibfk_1');
        $this->addSql('ALTER TABLE PeerServers DROP FOREIGN KEY PeerServers_ibfk_2');
        $this->addSql('ALTER TABLE PeerServers ADD CONSTRAINT FK_C12DE2EF7DB780F8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id)');
        $this->addSql('ALTER TABLE PeerServers ADD CONSTRAINT FK_C12DE2EF9CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE CompanyAdmins DROP FOREIGN KEY CompanyAdmins_ibfk_1');
        $this->addSql('ALTER TABLE CompanyAdmins DROP FOREIGN KEY CompanyAdmins_ibfk_2');
        $this->addSql('ALTER TABLE CompanyAdmins ADD CONSTRAINT FK_DBFB15352480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE CompanyAdmins ADD CONSTRAINT FK_DBFB153531D2BA8E FOREIGN KEY (timezoneId) REFERENCES Timezones (id)');
        $this->addSql('ALTER TABLE RoutingPatternGroups DROP FOREIGN KEY RoutingPatternGroups_ibfk_1');
        $this->addSql('ALTER TABLE RoutingPatternGroups ADD CONSTRAINT FK_CE50E62B9CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY HuntGroups_ibfk_1');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY HuntGroups_ibfk_2');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY HuntGroups_ibfk_3');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY HuntGroups_ibfk_4');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT FK_4F9672EC2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT FK_4F9672ECED66ACCC FOREIGN KEY (noAnswerLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT FK_4F9672EC4BF0624E FOREIGN KEY (noAnswerExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT FK_4F9672EC87167A2E FOREIGN KEY (noAnswerVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE Domains DROP FOREIGN KEY Domains_ibfk_1');
        $this->addSql('ALTER TABLE Domains DROP FOREIGN KEY Domains_ibfk_2');
        $this->addSql('ALTER TABLE Domains ADD CONSTRAINT FK_43C686012480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Domains ADD CONSTRAINT FK_43C686019CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE PickUpRelUsers DROP FOREIGN KEY PickUpRelUsers_ibfk_1');
        $this->addSql('ALTER TABLE PickUpRelUsers DROP FOREIGN KEY PickUpRelUsers_ibfk_2');
        $this->addSql('ALTER TABLE PickUpRelUsers ADD CONSTRAINT FK_5EAA6699CB8F98DA FOREIGN KEY (pickUpGroupId) REFERENCES PickUpGroups (id)');
        $this->addSql('ALTER TABLE PickUpRelUsers ADD CONSTRAINT FK_5EAA669964B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE CallACL DROP FOREIGN KEY CallAcl_ibfk_1');
        $this->addSql('ALTER TABLE CallACL ADD CONSTRAINT FK_D37348182480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE ConferenceRooms DROP FOREIGN KEY ConferenceRooms_ibfk_1');
        $this->addSql('ALTER TABLE ConferenceRooms ADD CONSTRAINT FK_7CE925992480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE PickUpGroups DROP FOREIGN KEY PickUpGroups_ibfk_1');
        $this->addSql('ALTER TABLE PickUpGroups ADD CONSTRAINT FK_3F7C24B82480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars DROP FOREIGN KEY ExternalCallFilterRelCalendars_ibfk_1');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars DROP FOREIGN KEY ExternalCallFilterRelCalendars_ibfk_2');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars ADD CONSTRAINT FK_283700E12E051C4F FOREIGN KEY (filterId) REFERENCES ExternalCallFilters (id)');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars ADD CONSTRAINT FK_283700E12D4F56A6 FOREIGN KEY (calendarId) REFERENCES Calendars (id)');
        $this->addSql('ALTER TABLE CallACLRelPatterns DROP FOREIGN KEY CallACLRelPatterns_ibfk_1');
        $this->addSql('ALTER TABLE CallACLRelPatterns DROP FOREIGN KEY CallACLRelPatterns_ibfk_2');
        $this->addSql('ALTER TABLE CallACLRelPatterns ADD CONSTRAINT FK_93D1E457D0A1C17A FOREIGN KEY (CallACLId) REFERENCES CallACL (id)');
        $this->addSql('ALTER TABLE CallACLRelPatterns ADD CONSTRAINT FK_93D1E4571D0DF419 FOREIGN KEY (CallACLPatternId) REFERENCES CallACLPatterns (id)');
        $this->addSql('ALTER TABLE Timezones DROP FOREIGN KEY Timezones_ibfk_2');
        $this->addSql('ALTER TABLE Timezones ADD CONSTRAINT FK_F7A34AFDFBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE Brands DROP FOREIGN KEY Brands_ibfk_2');
        $this->addSql('ALTER TABLE Brands DROP FOREIGN KEY Brands_ibfk_3');
        $this->addSql('ALTER TABLE Brands ADD CONSTRAINT FK_790E4102940D8C7E FOREIGN KEY (languageId) REFERENCES Languages (id)');
        $this->addSql('ALTER TABLE Brands ADD CONSTRAINT FK_790E4102A27130E4 FOREIGN KEY (defaultTimezoneId) REFERENCES Timezones (id)');
        $this->addSql('ALTER TABLE BrandServices DROP FOREIGN KEY BrandServices_ibfk_1');
        $this->addSql('ALTER TABLE BrandServices DROP FOREIGN KEY BrandServices_ibfk_2');
        $this->addSql('ALTER TABLE BrandServices ADD CONSTRAINT FK_AA498CCC9CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE BrandServices ADD CONSTRAINT FK_AA498CCC89697FA8 FOREIGN KEY (serviceId) REFERENCES Services (id)');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_1');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_2');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_3');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_4');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_5');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_6');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_7');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_8');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY IVRCommon_ibfk_9');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E92480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E92ECAF600 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E9ED66ACCC FOREIGN KEY (noAnswerLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E922DAA5F5 FOREIGN KEY (errorLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E976587A80 FOREIGN KEY (successLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E9535464FB FOREIGN KEY (timeoutExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E9143A564F FOREIGN KEY (errorExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E97030598F FOREIGN KEY (timeoutVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT FK_E0B977E9D60923A6 FOREIGN KEY (errorVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY IVRCustomEntries_ibfk_1');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY IVRCustomEntries_ibfk_2');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY IVRCustomEntries_ibfk_3');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY IVRCustomEntries_ibfk_4');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT FK_E6693828FEA4E4B0 FOREIGN KEY (IVRCustomId) REFERENCES IVRCustom (id)');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT FK_E66938282ECAF600 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT FK_E6693828C590D85B FOREIGN KEY (targetExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT FK_E669382847E563C5 FOREIGN KEY (targetVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_1');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_10');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_11');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_12');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_13');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_14');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_2');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_3');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_4');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_5');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_6');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_7');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_8');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY DDIs_ibfk_9');
        $this->addSql('DROP INDEX Faxes_ibfk_8 ON DDIs');
        $this->addSql('DROP INDEX Faxes_ibfk_9 ON DDIs');
        $this->addSql('DROP INDEX DDIs_ibfk_10 ON DDIs');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A02480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A09CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A023E42D0D FOREIGN KEY (conferenceRoomId) REFERENCES ConferenceRooms (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0940D8C7E FOREIGN KEY (languageId) REFERENCES Languages (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0A4D768C6 FOREIGN KEY (queueId) REFERENCES Queues (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A058D52220 FOREIGN KEY (externalCallFilterId) REFERENCES ExternalCallFilters (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A064B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A06B600F71 FOREIGN KEY (IVRCommonId) REFERENCES IVRCommon (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0FEA4E4B0 FOREIGN KEY (IVRCustomId) REFERENCES IVRCustom (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0921B2343 FOREIGN KEY (huntGroupId) REFERENCES HuntGroups (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0624C8D73 FOREIGN KEY (faxId) REFERENCES Faxes (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A07DB780F8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0FBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A05EA9D64D FOREIGN KEY (retailAccountId) REFERENCES RetailAccounts (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_10 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_9 FOREIGN KEY (countryId) REFERENCES Countries (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX peeringContractId ON DDIs (peeringContractId)');
        $this->addSql('CREATE INDEX countryId ON DDIs (countryId)');
        $this->addSql('CREATE INDEX brandId ON DDIs (brandId)');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices DROP FOREIGN KEY FixedCostsRelInvoices_ibfk_1');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices DROP FOREIGN KEY FixedCostsRelInvoices_ibfk_2');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices DROP FOREIGN KEY FixedCostsRelInvoices_ibfk_3');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices ADD CONSTRAINT FK_1374A9A59CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices ADD CONSTRAINT FK_1374A9A581256364 FOREIGN KEY (fixedCostId) REFERENCES FixedCosts (id)');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices ADD CONSTRAINT FK_1374A9A53D7BDC51 FOREIGN KEY (invoiceId) REFERENCES Invoices (id)');
        $this->addSql('ALTER TABLE InvoiceTemplates DROP FOREIGN KEY InvoiceTemplates_ibfk_1');
        $this->addSql('ALTER TABLE InvoiceTemplates ADD CONSTRAINT FK_CB0E9B689CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE MusicOnHold DROP FOREIGN KEY MusicOnHold_ibfk_1');
        $this->addSql('ALTER TABLE MusicOnHold ADD CONSTRAINT FK_9C5FB5902480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_1');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_10');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_11');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_12');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_13');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_3');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_7');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_8');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY Users_ibfk_9');
        $this->addSql('ALTER TABLE Users CHANGE maxCalls maxCalls INT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AED2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AED525043D9 FOREIGN KEY (callACLId) REFERENCES CallACL (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AEDB5FEF91D FOREIGN KEY (bossAssistantId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AEDFBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AED940D8C7E FOREIGN KEY (languageId) REFERENCES Languages (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AEDAE025626 FOREIGN KEY (terminalId) REFERENCES Terminals (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AED12AB7F65 FOREIGN KEY (extensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AED31D2BA8E FOREIGN KEY (timezoneId) REFERENCES Timezones (id)');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT FK_D5428AEDC8F2AA6B FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id)');
        $this->addSql('ALTER TABLE CallACLPatterns DROP FOREIGN KEY CallACLPatterns_ibfk_1');
        $this->addSql('ALTER TABLE CallACLPatterns ADD CONSTRAINT FK_7382D4E02480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE BrandOperators DROP FOREIGN KEY BrandOperators_ibfk_3');
        $this->addSql('ALTER TABLE BrandOperators DROP FOREIGN KEY BrandOperators_ibfk_4');
        $this->addSql('ALTER TABLE BrandOperators ADD CONSTRAINT FK_2703F6109CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE BrandOperators ADD CONSTRAINT FK_2703F61031D2BA8E FOREIGN KEY (timezoneId) REFERENCES Timezones (id)');
        $this->addSql('ALTER TABLE GenericCallACLPatterns DROP FOREIGN KEY GenericCallACLPatterns_ibfk_1');
        $this->addSql('ALTER TABLE GenericCallACLPatterns ADD CONSTRAINT FK_E0792DFD9CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns DROP FOREIGN KEY RoutingPatternGroupsRelPatterns_ibfk_1');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns DROP FOREIGN KEY RoutingPatternGroupsRelPatterns_ibfk_2');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns ADD CONSTRAINT FK_C90A69B46D661974 FOREIGN KEY (routingPatternId) REFERENCES RoutingPatterns (id)');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns ADD CONSTRAINT FK_C90A69B486CE18CB FOREIGN KEY (routingPatternGroupId) REFERENCES RoutingPatternGroups (id)');
        $this->addSql('ALTER TABLE Invoices DROP FOREIGN KEY Invoices_ibfk_1');
        $this->addSql('ALTER TABLE Invoices DROP FOREIGN KEY Invoices_ibfk_2');
        $this->addSql('ALTER TABLE Invoices DROP FOREIGN KEY Invoices_ibfk_4');
        $this->addSql('ALTER TABLE Invoices ADD CONSTRAINT FK_93594DC3D07541BE FOREIGN KEY (invoiceTemplateId) REFERENCES InvoiceTemplates (id)');
        $this->addSql('ALTER TABLE Invoices ADD CONSTRAINT FK_93594DC39CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE Invoices ADD CONSTRAINT FK_93594DC32480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY Friends_ibfk_1');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY Friends_ibfk_2');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY Friends_ibfk_3');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY Friends_ibfk_4');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY Friends_ibfk_5');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT FK_EE5349F52480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT FK_EE5349F5FBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT FK_EE5349F5525043D9 FOREIGN KEY (callACLId) REFERENCES CallACL (id)');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT FK_EE5349F5C8F2AA6B FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id)');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT FK_EE5349F5940D8C7E FOREIGN KEY (languageId) REFERENCES Languages (id)');
        $this->addSql('ALTER TABLE FixedCosts DROP FOREIGN KEY FixedCosts_ibfk_1');
        $this->addSql('ALTER TABLE FixedCosts ADD CONSTRAINT FK_1D4E03F49CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies DROP FOREIGN KEY PricingPlansRelCompanies_ibfk_1');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies DROP FOREIGN KEY PricingPlansRelCompanies_ibfk_2');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies DROP FOREIGN KEY PricingPlansRelCompanies_ibfk_3');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies ADD CONSTRAINT FK_78F195D2EDF37044 FOREIGN KEY (pricingPlanId) REFERENCES PricingPlans (id)');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies ADD CONSTRAINT FK_78F195D22480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies ADD CONSTRAINT FK_78F195D29CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE GenericMusicOnHold DROP FOREIGN KEY fGenericMusicOnHold_ibfk_1');
        $this->addSql('ALTER TABLE GenericMusicOnHold ADD CONSTRAINT FK_F9FA93559CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE ParsedCDRs DROP FOREIGN KEY ParsedCDRs_ibfk_1');
        $this->addSql('ALTER TABLE ParsedCDRs DROP FOREIGN KEY ParsedCDRs_ibfk_2');
        $this->addSql('ALTER TABLE ParsedCDRs DROP FOREIGN KEY parsedCDRs_ibfk_6');
        $this->addSql('ALTER TABLE ParsedCDRs ADD CONSTRAINT FK_A94BA5799CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE ParsedCDRs ADD CONSTRAINT FK_A94BA5792480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE ParsedCDRs ADD CONSTRAINT FK_A94BA5797DB780F8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id)');
        $this->addSql('ALTER TABLE Faxes DROP FOREIGN KEY Faxes_ibfk_1');
        $this->addSql('ALTER TABLE Faxes DROP FOREIGN KEY Faxes_ibfk_2');
        $this->addSql('ALTER TABLE Faxes ADD CONSTRAINT FK_196F4C1E2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Faxes ADD CONSTRAINT FK_196F4C1EC8F2AA6B FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id)');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_1');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_2');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_3');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_4');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_5');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_6');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_7');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY Queues_ibfk_8');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A02480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A02CAE121C FOREIGN KEY (periodicAnnounceLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A0FE276E1B FOREIGN KEY (timeoutLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A0535464FB FOREIGN KEY (timeoutExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A07030598F FOREIGN KEY (timeoutVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A0DC78ACAF FOREIGN KEY (fullLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A09F7A4CAC FOREIGN KEY (fullExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT FK_C86607A08961FE7B FOREIGN KEY (fullVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_1');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_2');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_3');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_4');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_5');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_6');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_7');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_8');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY IVRCustom_ibfk_9');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D111232480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D111232ECAF600 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D11123ED66ACCC FOREIGN KEY (noAnswerLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D1112322DAA5F5 FOREIGN KEY (errorLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D1112376587A80 FOREIGN KEY (successLocutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D11123535464FB FOREIGN KEY (timeoutExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D11123143A564F FOREIGN KEY (errorExtensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D111237030598F FOREIGN KEY (timeoutVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT FK_F0D11123D60923A6 FOREIGN KEY (errorVoiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY RetailAccounts_ibfk_1');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY RetailAccounts_ibfk_2');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY RetailAccounts_ibfk_3');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY RetailAccounts_ibfk_4');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY RetailAccounts_ibfk_5');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT FK_732D92509CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT FK_732D92502480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT FK_732D9250FBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT FK_732D9250C8F2AA6B FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id)');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT FK_732D9250940D8C7E FOREIGN KEY (languageId) REFERENCES Languages (id)');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers DROP FOREIGN KEY HuntGroupsRelUsers_ibfk_1');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers DROP FOREIGN KEY HuntGroupsRelUsers_ibfk_2');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers ADD CONSTRAINT FK_79ED31AB921B2343 FOREIGN KEY (huntGroupId) REFERENCES HuntGroups (id)');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers ADD CONSTRAINT FK_79ED31AB64B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks DROP FOREIGN KEY TransformationRulesetGroupsTrunks_ibfk_1');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks DROP FOREIGN KEY TransformationRulesetGroupsTrunks_ibfk_2');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks ADD CONSTRAINT FK_F2AD690C9CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks ADD CONSTRAINT FK_F2AD690CFBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY OutgoingRouting_ibfk_1');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY OutgoingRouting_ibfk_2');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY OutgoingRouting_ibfk_5');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY OutgoingRouting_ibfk_6');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY OutgoingRouting_ibfk_7');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT FK_569314729CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT FK_569314722480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT FK_569314727DB780F8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id)');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT FK_569314726D661974 FOREIGN KEY (routingPatternId) REFERENCES RoutingPatterns (id)');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT FK_5693147286CE18CB FOREIGN KEY (routingPatternGroupId) REFERENCES RoutingPatternGroups (id)');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_10');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_11');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_12');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_13');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_4');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_5');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY Companies_ibfk_9');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B52899940D8C7E FOREIGN KEY (languageId) REFERENCES Languages (id)');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B52899C8555117 FOREIGN KEY (mediaRelaySetsId) REFERENCES MediaRelaySets (id)');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B52899A27130E4 FOREIGN KEY (defaultTimezoneId) REFERENCES Timezones (id)');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B528999CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B52899F862FFE7 FOREIGN KEY (applicationServerId) REFERENCES ApplicationServers (id)');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B52899FBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT FK_B52899C8F2AA6B FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id)');
        $this->addSql('ALTER TABLE Recordings DROP FOREIGN KEY Recordings_ibfk_1');
        $this->addSql('ALTER TABLE Recordings ADD CONSTRAINT FK_A68A9FBE2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE PricingPlans DROP FOREIGN KEY PricingPlans_ibfk_1');
        $this->addSql('ALTER TABLE PricingPlans ADD CONSTRAINT FK_9AA416889CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE QueueMembers DROP FOREIGN KEY QueueMembers_ibfk_1');
        $this->addSql('ALTER TABLE QueueMembers DROP FOREIGN KEY QueueMembers_ibfk_2');
        $this->addSql('ALTER TABLE QueueMembers ADD CONSTRAINT FK_51FEFDD1A4D768C6 FOREIGN KEY (queueId) REFERENCES Queues (id)');
        $this->addSql('ALTER TABLE QueueMembers ADD CONSTRAINT FK_51FEFDD164B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE CallForwardSettings DROP FOREIGN KEY CallForwardSettings_ibfk_1');
        $this->addSql('ALTER TABLE CallForwardSettings DROP FOREIGN KEY CallForwardSettings_ibfk_2');
        $this->addSql('ALTER TABLE CallForwardSettings DROP FOREIGN KEY CallForwardSettings_ibfk_3');
        $this->addSql('ALTER TABLE CallForwardSettings ADD CONSTRAINT FK_E71B58A464B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE CallForwardSettings ADD CONSTRAINT FK_E71B58A412AB7F65 FOREIGN KEY (extensionId) REFERENCES Extensions (id)');
        $this->addSql('ALTER TABLE CallForwardSettings ADD CONSTRAINT FK_E71B58A4AF230FFD FOREIGN KEY (voiceMailUserId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE HolidayDates DROP FOREIGN KEY HolidayDates_ibfk_1');
        $this->addSql('ALTER TABLE HolidayDates DROP FOREIGN KEY HolidayDates_ibfk_2');
        $this->addSql('ALTER TABLE HolidayDates ADD CONSTRAINT FK_4C5712802D4F56A6 FOREIGN KEY (calendarId) REFERENCES Calendars (id)');
        $this->addSql('ALTER TABLE HolidayDates ADD CONSTRAINT FK_4C57128054690B0 FOREIGN KEY (locutionId) REFERENCES Locutions (id)');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns DROP FOREIGN KEY PricingPlansRelTargetPatterns_ibfk_1');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns DROP FOREIGN KEY PricingPlansRelTargetPatterns_ibfk_2');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns DROP FOREIGN KEY PricingPlansRelTargetPatterns_ibfk_3');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns ADD CONSTRAINT FK_CAD1B6B5EDF37044 FOREIGN KEY (pricingPlanId) REFERENCES PricingPlans (id)');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns ADD CONSTRAINT FK_CAD1B6B54D2CFC16 FOREIGN KEY (targetPatternId) REFERENCES TargetPatterns (id)');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns ADD CONSTRAINT FK_CAD1B6B59CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE FeaturesRelBrands DROP FOREIGN KEY FeaturesRelBrands_ibfk_1');
        $this->addSql('ALTER TABLE FeaturesRelBrands DROP FOREIGN KEY FeaturesRelBrands_ibfk_2');
        $this->addSql('ALTER TABLE FeaturesRelBrands ADD CONSTRAINT FK_6BA104879CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE FeaturesRelBrands ADD CONSTRAINT FK_6BA10487397515B7 FOREIGN KEY (featureId) REFERENCES Features (id)');
        $this->addSql('ALTER TABLE MainOperators DROP FOREIGN KEY MainOperators_ibfk_1');
        $this->addSql('ALTER TABLE MainOperators ADD CONSTRAINT FK_470B475931D2BA8E FOREIGN KEY (timezoneId) REFERENCES Timezones (id)');
        $this->addSql('ALTER TABLE Schedules DROP FOREIGN KEY Schedules_ibfk_1');
        $this->addSql('ALTER TABLE Schedules ADD CONSTRAINT FK_B3CA5E2D2480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE FaxesInOut DROP FOREIGN KEY FaxesInOut_ibfk_2');
        $this->addSql('ALTER TABLE FaxesInOut ADD CONSTRAINT FK_E047541D624C8D73 FOREIGN KEY (faxId) REFERENCES Faxes (id)');
        $this->addSql('ALTER TABLE ast_ps_aors DROP FOREIGN KEY ast_ps_aors_ibfk_1');
        $this->addSql('ALTER TABLE ast_voicemail DROP FOREIGN KEY ast_voicemail_ibfk_1');
        $this->addSql('ALTER TABLE ast_voicemail ADD CONSTRAINT FK_B2AD1D0A64B64DCC FOREIGN KEY (userId) REFERENCES Users (id)');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY ast_ps_endpoints_ibfk_1');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY ast_ps_endpoints_ibfk_2');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY ast_ps_endpoints_ibfk_3');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT FK_800B6051AE025626 FOREIGN KEY (terminalId) REFERENCES Terminals (id)');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT FK_800B6051893BA339 FOREIGN KEY (friendId) REFERENCES Friends (id)');
        $this->addSql('DROP INDEX retailAccountId ON ast_ps_endpoints');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT FK_800B60515EA9D64D FOREIGN KEY (retailAccountId) REFERENCES RetailAccounts (id)');
        $this->addSql('CREATE INDEX IDX_800B60515EA9D64D ON ast_ps_endpoints (retailAccountId)');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT ast_ps_endpoints_ibfk_3 FOREIGN KEY (retailAccountId) REFERENCES RetailAccounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ast_queues DROP FOREIGN KEY ast_queues_ibfk_1');
        $this->addSql('ALTER TABLE ast_queues ADD CONSTRAINT FK_970E5D29A4D768C6 FOREIGN KEY (queueId) REFERENCES Queues (id)');
        $this->addSql('ALTER TABLE ast_queue_members DROP FOREIGN KEY ast_queue_members_ibfk_1');
        $this->addSql('ALTER TABLE ast_queue_members ADD CONSTRAINT FK_9EEBA5FCFF8FC3FF FOREIGN KEY (queueMemberId) REFERENCES QueueMembers (id)');
        $this->addSql('ALTER TABLE kam_trunks_dialplan DROP FOREIGN KEY kam_trunks_dialplan_ibfk_2');
        $this->addSql('ALTER TABLE kam_trunks_dialplan ADD CONSTRAINT FK_3F0091CF2D92AF39 FOREIGN KEY (transformationRulesetGroupsTrunksId) REFERENCES TransformationRulesetGroupsTrunks (id)');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY kam_acc_cdrs_ibfk_1');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY kam_acc_cdrs_ibfk_2');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY kam_acc_cdrs_ibfk_3');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY kam_acc_cdrs_ibfk_4');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY kam_acc_cdrs_ibfk_5');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT FK_1AC995A6EDF37044 FOREIGN KEY (pricingPlanId) REFERENCES PricingPlans (id)');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT FK_1AC995A64D2CFC16 FOREIGN KEY (targetPatternId) REFERENCES TargetPatterns (id)');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT FK_1AC995A63D7BDC51 FOREIGN KEY (invoiceId) REFERENCES Invoices (id)');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT FK_1AC995A69CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT FK_1AC995A62480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE kam_rtpproxy DROP FOREIGN KEY kam_rtpproxy_ibfk_1');
        $this->addSql('ALTER TABLE kam_rtpproxy ADD CONSTRAINT FK_729D1741C8555117 FOREIGN KEY (mediaRelaySetsId) REFERENCES MediaRelaySets (id)');
        $this->addSql('ALTER TABLE kam_users_domain_attrs DROP FOREIGN KEY kam_users_domain_attrs_ibfk_1');
        $this->addSql('ALTER TABLE kam_users_domain_attrs ADD CONSTRAINT FK_F444738D4E7FCF41 FOREIGN KEY (did) REFERENCES Companies (domain_users)');
        $this->addSql('ALTER TABLE kam_trunks_uacreg DROP FOREIGN KEY kam_trunks_uacreg_ibfk_1');
        $this->addSql('ALTER TABLE kam_trunks_uacreg DROP FOREIGN KEY kam_trunks_uacreg_ibfk_2');
        $this->addSql('ALTER TABLE kam_trunks_uacreg ADD CONSTRAINT FK_C61278219CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE kam_trunks_uacreg ADD CONSTRAINT FK_C61278217DB780F8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id)');
        $this->addSql('ALTER TABLE kam_users_address DROP FOREIGN KEY kam_users_address_ibfk_1');
        $this->addSql('ALTER TABLE kam_users_address ADD CONSTRAINT FK_A53CBBF22480E723 FOREIGN KEY (companyId) REFERENCES Companies (id)');
        $this->addSql('ALTER TABLE kam_dispatcher DROP FOREIGN KEY kam_dispatcher_ibfk_1');
        $this->addSql('ALTER TABLE kam_dispatcher ADD CONSTRAINT FK_7CD78806F862FFE7 FOREIGN KEY (applicationServerId) REFERENCES ApplicationServers (id)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE BrandOperators DROP FOREIGN KEY FK_2703F6109CBEC244');
        $this->addSql('ALTER TABLE BrandOperators DROP FOREIGN KEY FK_2703F61031D2BA8E');
        $this->addSql('ALTER TABLE BrandOperators ADD CONSTRAINT BrandOperators_ibfk_3 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE BrandOperators ADD CONSTRAINT BrandOperators_ibfk_4 FOREIGN KEY (timezoneId) REFERENCES Timezones (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE BrandServices DROP FOREIGN KEY FK_AA498CCC9CBEC244');
        $this->addSql('ALTER TABLE BrandServices DROP FOREIGN KEY FK_AA498CCC89697FA8');
        $this->addSql('ALTER TABLE BrandServices ADD CONSTRAINT BrandServices_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE BrandServices ADD CONSTRAINT BrandServices_ibfk_2 FOREIGN KEY (serviceId) REFERENCES Services (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE BrandURLs DROP FOREIGN KEY FK_8DBE74F59CBEC244');
        $this->addSql('ALTER TABLE BrandURLs ADD CONSTRAINT BrandURLs_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Brands DROP FOREIGN KEY FK_790E4102940D8C7E');
        $this->addSql('ALTER TABLE Brands DROP FOREIGN KEY FK_790E4102A27130E4');
        $this->addSql('ALTER TABLE Brands ADD CONSTRAINT Brands_ibfk_2 FOREIGN KEY (languageId) REFERENCES Languages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Brands ADD CONSTRAINT Brands_ibfk_3 FOREIGN KEY (defaultTimezoneId) REFERENCES Timezones (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Calendars DROP FOREIGN KEY FK_62E00AC2480E723');
        $this->addSql('ALTER TABLE Calendars ADD CONSTRAINT Calendars_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallACL DROP FOREIGN KEY FK_D37348182480E723');
        $this->addSql('ALTER TABLE CallACL ADD CONSTRAINT CallAcl_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallACLPatterns DROP FOREIGN KEY FK_7382D4E02480E723');
        $this->addSql('ALTER TABLE CallACLPatterns ADD CONSTRAINT CallACLPatterns_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallACLRelPatterns DROP FOREIGN KEY FK_93D1E457D0A1C17A');
        $this->addSql('ALTER TABLE CallACLRelPatterns DROP FOREIGN KEY FK_93D1E4571D0DF419');
        $this->addSql('ALTER TABLE CallACLRelPatterns ADD CONSTRAINT CallACLRelPatterns_ibfk_1 FOREIGN KEY (CallACLId) REFERENCES CallACL (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallACLRelPatterns ADD CONSTRAINT CallACLRelPatterns_ibfk_2 FOREIGN KEY (CallACLPatternId) REFERENCES CallACLPatterns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallForwardSettings DROP FOREIGN KEY FK_E71B58A464B64DCC');
        $this->addSql('ALTER TABLE CallForwardSettings DROP FOREIGN KEY FK_E71B58A412AB7F65');
        $this->addSql('ALTER TABLE CallForwardSettings DROP FOREIGN KEY FK_E71B58A4AF230FFD');
        $this->addSql('ALTER TABLE CallForwardSettings ADD CONSTRAINT CallForwardSettings_ibfk_1 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallForwardSettings ADD CONSTRAINT CallForwardSettings_ibfk_2 FOREIGN KEY (extensionId) REFERENCES Extensions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CallForwardSettings ADD CONSTRAINT CallForwardSettings_ibfk_3 FOREIGN KEY (voiceMailUserId) REFERENCES Users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B52899940D8C7E');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B52899C8555117');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B52899A27130E4');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B528999CBEC244');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B52899F862FFE7');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B52899FBA2A6B4');
        $this->addSql('ALTER TABLE Companies DROP FOREIGN KEY FK_B52899C8F2AA6B');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_10 FOREIGN KEY (languageId) REFERENCES Languages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_11 FOREIGN KEY (mediaRelaySetsId) REFERENCES MediaRelaySets (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_12 FOREIGN KEY (defaultTimezoneId) REFERENCES Timezones (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_13 FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_4 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_5 FOREIGN KEY (applicationServerId) REFERENCES ApplicationServers (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Companies ADD CONSTRAINT Companies_ibfk_9 FOREIGN KEY (countryId) REFERENCES Countries (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE CompanyAdmins DROP FOREIGN KEY FK_DBFB15352480E723');
        $this->addSql('ALTER TABLE CompanyAdmins DROP FOREIGN KEY FK_DBFB153531D2BA8E');
        $this->addSql('ALTER TABLE CompanyAdmins ADD CONSTRAINT CompanyAdmins_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CompanyAdmins ADD CONSTRAINT CompanyAdmins_ibfk_2 FOREIGN KEY (timezoneId) REFERENCES Timezones (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE CompanyServices DROP FOREIGN KEY FK_569B460B2480E723');
        $this->addSql('ALTER TABLE CompanyServices DROP FOREIGN KEY FK_569B460B89697FA8');
        $this->addSql('ALTER TABLE CompanyServices ADD CONSTRAINT CompanyServices_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CompanyServices ADD CONSTRAINT CompanyServices_ibfk_2 FOREIGN KEY (serviceId) REFERENCES Services (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ConferenceRooms DROP FOREIGN KEY FK_7CE925992480E723');
        $this->addSql('ALTER TABLE ConferenceRooms ADD CONSTRAINT ConferenceRooms_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A02480E723');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A09CBEC244');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A023E42D0D');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0940D8C7E');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0A4D768C6');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A058D52220');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A064B64DCC');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A06B600F71');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0FEA4E4B0');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0921B2343');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0624C8D73');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A07DB780F8');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0FBA2A6B4');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A05EA9D64D');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A09CBEC244');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A07DB780F8');
        $this->addSql('ALTER TABLE DDIs DROP FOREIGN KEY FK_AA16E1A0FBA2A6B4');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_11 FOREIGN KEY (conferenceRoomId) REFERENCES ConferenceRooms (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_12 FOREIGN KEY (languageId) REFERENCES Languages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_13 FOREIGN KEY (queueId) REFERENCES Queues (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_14 FOREIGN KEY (retailAccountId) REFERENCES RetailAccounts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_2 FOREIGN KEY (externalCallFilterId) REFERENCES ExternalCallFilters (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_3 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_4 FOREIGN KEY (IVRCommonId) REFERENCES IVRCommon (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_5 FOREIGN KEY (IVRCustomId) REFERENCES IVRCustom (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_6 FOREIGN KEY (huntGroupId) REFERENCES HuntGroups (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT DDIs_ibfk_7 FOREIGN KEY (faxId) REFERENCES Faxes (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX peeringcontractid ON DDIs');
        $this->addSql('CREATE INDEX Faxes_ibfk_8 ON DDIs (peeringContractId)');
        $this->addSql('DROP INDEX countryid ON DDIs');
        $this->addSql('CREATE INDEX Faxes_ibfk_9 ON DDIs (countryId)');
        $this->addSql('DROP INDEX brandid ON DDIs');
        $this->addSql('CREATE INDEX DDIs_ibfk_10 ON DDIs (brandId)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A09CBEC244 FOREIGN KEY (brandId) REFERENCES Brands (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A07DB780F8 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id)');
        $this->addSql('ALTER TABLE DDIs ADD CONSTRAINT FK_AA16E1A0FBA2A6B4 FOREIGN KEY (countryId) REFERENCES Countries (id)');
        $this->addSql('ALTER TABLE Domains DROP FOREIGN KEY FK_43C686012480E723');
        $this->addSql('ALTER TABLE Domains DROP FOREIGN KEY FK_43C686019CBEC244');
        $this->addSql('ALTER TABLE Domains ADD CONSTRAINT Domains_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Domains ADD CONSTRAINT Domains_ibfk_2 FOREIGN KEY (brandId) REFERENCES Brands (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F792480E723');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F796B600F71');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F79FEA4E4B0');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F79921B2343');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F7923E42D0D');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F7964B64DCC');
        $this->addSql('ALTER TABLE Extensions DROP FOREIGN KEY FK_9AAD9F79A4D768C6');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_2 FOREIGN KEY (IVRCommonId) REFERENCES IVRCommon (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_3 FOREIGN KEY (IVRCustomId) REFERENCES IVRCustom (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_4 FOREIGN KEY (huntGroupId) REFERENCES HuntGroups (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_5 FOREIGN KEY (conferenceRoomId) REFERENCES ConferenceRooms (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_6 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Extensions ADD CONSTRAINT Extensions_ibfk_7 FOREIGN KEY (queueId) REFERENCES Queues (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars DROP FOREIGN KEY FK_283700E12E051C4F');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars DROP FOREIGN KEY FK_283700E12D4F56A6');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars ADD CONSTRAINT ExternalCallFilterRelCalendars_ibfk_1 FOREIGN KEY (filterId) REFERENCES ExternalCallFilters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ExternalCallFilterRelCalendars ADD CONSTRAINT ExternalCallFilterRelCalendars_ibfk_2 FOREIGN KEY (calendarId) REFERENCES Calendars (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules DROP FOREIGN KEY FK_9DD35E602E051C4F');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules DROP FOREIGN KEY FK_9DD35E60B745014E');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules ADD CONSTRAINT ExternalCallFilterRelSchedules_ibfk_1 FOREIGN KEY (filterId) REFERENCES ExternalCallFilters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ExternalCallFilterRelSchedules ADD CONSTRAINT ExternalCallFilterRelSchedules_ibfk_2 FOREIGN KEY (scheduleId) REFERENCES Schedules (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED92480E723');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED92ECAF600');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED99FB29831');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED9D4FFE2F7');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED9888E38DB');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED9FAC21224');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED9DF7207AC');
        $this->addSql('ALTER TABLE ExternalCallFilters DROP FOREIGN KEY FK_528CEED9D66AD272');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_2 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_3 FOREIGN KEY (holidayLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_4 FOREIGN KEY (outOfScheduleLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_5 FOREIGN KEY (holidayExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_6 FOREIGN KEY (outOfScheduleExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_7 FOREIGN KEY (holidayVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ExternalCallFilters ADD CONSTRAINT ExternalCallFilters_ibfk_8 FOREIGN KEY (outOfScheduleVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Faxes DROP FOREIGN KEY FK_196F4C1E2480E723');
        $this->addSql('ALTER TABLE Faxes DROP FOREIGN KEY FK_196F4C1EC8F2AA6B');
        $this->addSql('ALTER TABLE Faxes ADD CONSTRAINT Faxes_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Faxes ADD CONSTRAINT Faxes_ibfk_2 FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE FaxesInOut DROP FOREIGN KEY FK_E047541D624C8D73');
        $this->addSql('ALTER TABLE FaxesInOut ADD CONSTRAINT FaxesInOut_ibfk_2 FOREIGN KEY (faxId) REFERENCES Faxes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FeaturesRelBrands DROP FOREIGN KEY FK_6BA104879CBEC244');
        $this->addSql('ALTER TABLE FeaturesRelBrands DROP FOREIGN KEY FK_6BA10487397515B7');
        $this->addSql('ALTER TABLE FeaturesRelBrands ADD CONSTRAINT FeaturesRelBrands_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FeaturesRelBrands ADD CONSTRAINT FeaturesRelBrands_ibfk_2 FOREIGN KEY (featureId) REFERENCES Features (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FeaturesRelCompanies DROP FOREIGN KEY FK_2C2CF4D92480E723');
        $this->addSql('ALTER TABLE FeaturesRelCompanies DROP FOREIGN KEY FK_2C2CF4D9397515B7');
        $this->addSql('ALTER TABLE FeaturesRelCompanies ADD CONSTRAINT FeaturesRelCompanies_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FeaturesRelCompanies ADD CONSTRAINT FeaturesRelCompanies_ibfk_2 FOREIGN KEY (featureId) REFERENCES Features (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FixedCosts DROP FOREIGN KEY FK_1D4E03F49CBEC244');
        $this->addSql('ALTER TABLE FixedCosts ADD CONSTRAINT FixedCosts_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices DROP FOREIGN KEY FK_1374A9A59CBEC244');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices DROP FOREIGN KEY FK_1374A9A581256364');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices DROP FOREIGN KEY FK_1374A9A53D7BDC51');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices ADD CONSTRAINT FixedCostsRelInvoices_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices ADD CONSTRAINT FixedCostsRelInvoices_ibfk_2 FOREIGN KEY (fixedCostId) REFERENCES FixedCosts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE FixedCostsRelInvoices ADD CONSTRAINT FixedCostsRelInvoices_ibfk_3 FOREIGN KEY (invoiceId) REFERENCES Invoices (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY FK_EE5349F52480E723');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY FK_EE5349F5FBA2A6B4');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY FK_EE5349F5525043D9');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY FK_EE5349F5C8F2AA6B');
        $this->addSql('ALTER TABLE Friends DROP FOREIGN KEY FK_EE5349F5940D8C7E');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT Friends_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT Friends_ibfk_2 FOREIGN KEY (countryId) REFERENCES Countries (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT Friends_ibfk_3 FOREIGN KEY (callACLId) REFERENCES CallACL (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT Friends_ibfk_4 FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Friends ADD CONSTRAINT Friends_ibfk_5 FOREIGN KEY (languageId) REFERENCES Languages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE FriendsPatterns DROP FOREIGN KEY FK_933D96E5893BA339');
        $this->addSql('ALTER TABLE FriendsPatterns ADD CONSTRAINT FriendsPatterns_ibfk_1 FOREIGN KEY (friendId) REFERENCES Friends (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE GenericCallACLPatterns DROP FOREIGN KEY FK_E0792DFD9CBEC244');
        $this->addSql('ALTER TABLE GenericCallACLPatterns ADD CONSTRAINT GenericCallACLPatterns_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE GenericMusicOnHold DROP FOREIGN KEY FK_F9FA93559CBEC244');
        $this->addSql('ALTER TABLE GenericMusicOnHold ADD CONSTRAINT fGenericMusicOnHold_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE HolidayDates DROP FOREIGN KEY FK_4C5712802D4F56A6');
        $this->addSql('ALTER TABLE HolidayDates DROP FOREIGN KEY FK_4C57128054690B0');
        $this->addSql('ALTER TABLE HolidayDates ADD CONSTRAINT HolidayDates_ibfk_1 FOREIGN KEY (calendarId) REFERENCES Calendars (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE HolidayDates ADD CONSTRAINT HolidayDates_ibfk_2 FOREIGN KEY (locutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY FK_4F9672EC2480E723');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY FK_4F9672ECED66ACCC');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY FK_4F9672EC4BF0624E');
        $this->addSql('ALTER TABLE HuntGroups DROP FOREIGN KEY FK_4F9672EC87167A2E');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT HuntGroups_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT HuntGroups_ibfk_2 FOREIGN KEY (noAnswerLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT HuntGroups_ibfk_3 FOREIGN KEY (noAnswerExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE HuntGroups ADD CONSTRAINT HuntGroups_ibfk_4 FOREIGN KEY (noAnswerVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers DROP FOREIGN KEY FK_79ED31AB921B2343');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers DROP FOREIGN KEY FK_79ED31AB64B64DCC');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers ADD CONSTRAINT HuntGroupsRelUsers_ibfk_1 FOREIGN KEY (huntGroupId) REFERENCES HuntGroups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE HuntGroupsRelUsers ADD CONSTRAINT HuntGroupsRelUsers_ibfk_2 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E92480E723');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E92ECAF600');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E9ED66ACCC');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E922DAA5F5');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E976587A80');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E9535464FB');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E9143A564F');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E97030598F');
        $this->addSql('ALTER TABLE IVRCommon DROP FOREIGN KEY FK_E0B977E9D60923A6');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_2 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_3 FOREIGN KEY (noAnswerLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_4 FOREIGN KEY (errorLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_5 FOREIGN KEY (successLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_6 FOREIGN KEY (timeoutExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_7 FOREIGN KEY (errorExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_8 FOREIGN KEY (timeoutVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCommon ADD CONSTRAINT IVRCommon_ibfk_9 FOREIGN KEY (errorVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D111232480E723');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D111232ECAF600');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D11123ED66ACCC');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D1112322DAA5F5');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D1112376587A80');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D11123535464FB');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D11123143A564F');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D111237030598F');
        $this->addSql('ALTER TABLE IVRCustom DROP FOREIGN KEY FK_F0D11123D60923A6');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_2 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_3 FOREIGN KEY (noAnswerLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_4 FOREIGN KEY (errorLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_5 FOREIGN KEY (successLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_6 FOREIGN KEY (timeoutExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_7 FOREIGN KEY (errorExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_8 FOREIGN KEY (timeoutVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustom ADD CONSTRAINT IVRCustom_ibfk_9 FOREIGN KEY (errorVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY FK_E6693828FEA4E4B0');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY FK_E66938282ECAF600');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY FK_E6693828C590D85B');
        $this->addSql('ALTER TABLE IVRCustomEntries DROP FOREIGN KEY FK_E669382847E563C5');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT IVRCustomEntries_ibfk_1 FOREIGN KEY (IVRCustomId) REFERENCES IVRCustom (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT IVRCustomEntries_ibfk_2 FOREIGN KEY (welcomeLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT IVRCustomEntries_ibfk_3 FOREIGN KEY (targetExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE IVRCustomEntries ADD CONSTRAINT IVRCustomEntries_ibfk_4 FOREIGN KEY (targetVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE InvoiceTemplates DROP FOREIGN KEY FK_CB0E9B689CBEC244');
        $this->addSql('ALTER TABLE InvoiceTemplates ADD CONSTRAINT InvoiceTemplates_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Invoices DROP FOREIGN KEY FK_93594DC3D07541BE');
        $this->addSql('ALTER TABLE Invoices DROP FOREIGN KEY FK_93594DC39CBEC244');
        $this->addSql('ALTER TABLE Invoices DROP FOREIGN KEY FK_93594DC32480E723');
        $this->addSql('ALTER TABLE Invoices ADD CONSTRAINT Invoices_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Invoices ADD CONSTRAINT Invoices_ibfk_2 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Invoices ADD CONSTRAINT Invoices_ibfk_4 FOREIGN KEY (invoiceTemplateId) REFERENCES InvoiceTemplates (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE LcrGateways DROP FOREIGN KEY FK_14A48EA095319D46');
        $this->addSql('ALTER TABLE LcrGateways ADD CONSTRAINT LcrGateways_ibfk_2 FOREIGN KEY (peerServerId) REFERENCES PeerServers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LcrRuleTargets DROP FOREIGN KEY FK_2EC3B847744E0351');
        $this->addSql('ALTER TABLE LcrRuleTargets DROP FOREIGN KEY FK_2EC3B84782D8D847');
        $this->addSql('ALTER TABLE LcrRuleTargets DROP FOREIGN KEY FK_2EC3B8473CDE892');
        $this->addSql('ALTER TABLE LcrRuleTargets ADD CONSTRAINT LcrRuleTargets_ibfk_2 FOREIGN KEY (rule_id) REFERENCES LcrRules (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LcrRuleTargets ADD CONSTRAINT LcrRuleTargets_ibfk_3 FOREIGN KEY (gw_id) REFERENCES LcrGateways (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LcrRuleTargets ADD CONSTRAINT LcrRuleTargets_ibfk_4 FOREIGN KEY (outgoingRoutingId) REFERENCES OutgoingRouting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LcrRules DROP FOREIGN KEY FK_69DDB35C6D661974');
        $this->addSql('ALTER TABLE LcrRules DROP FOREIGN KEY FK_69DDB35C3CDE892');
        $this->addSql('ALTER TABLE LcrRules ADD CONSTRAINT LcrRules_ibfk_4 FOREIGN KEY (routingPatternId) REFERENCES RoutingPatterns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE LcrRules ADD CONSTRAINT LcrRules_ibfk_5 FOREIGN KEY (outgoingRoutingId) REFERENCES OutgoingRouting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Locutions DROP FOREIGN KEY FK_D5088942480E723');
        $this->addSql('ALTER TABLE Locutions ADD CONSTRAINT Locutions_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE MainOperators DROP FOREIGN KEY FK_470B475931D2BA8E');
        $this->addSql('ALTER TABLE MainOperators ADD CONSTRAINT MainOperators_ibfk_1 FOREIGN KEY (timezoneId) REFERENCES Timezones (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE MusicOnHold DROP FOREIGN KEY FK_9C5FB5902480E723');
        $this->addSql('ALTER TABLE MusicOnHold ADD CONSTRAINT MusicOnHold_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY FK_569314729CBEC244');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY FK_569314722480E723');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY FK_569314727DB780F8');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY FK_569314726D661974');
        $this->addSql('ALTER TABLE OutgoingRouting DROP FOREIGN KEY FK_5693147286CE18CB');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT OutgoingRouting_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT OutgoingRouting_ibfk_2 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT OutgoingRouting_ibfk_5 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT OutgoingRouting_ibfk_6 FOREIGN KEY (routingPatternId) REFERENCES RoutingPatterns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE OutgoingRouting ADD CONSTRAINT OutgoingRouting_ibfk_7 FOREIGN KEY (routingPatternGroupId) REFERENCES RoutingPatternGroups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ParsedCDRs DROP FOREIGN KEY FK_A94BA5799CBEC244');
        $this->addSql('ALTER TABLE ParsedCDRs DROP FOREIGN KEY FK_A94BA5792480E723');
        $this->addSql('ALTER TABLE ParsedCDRs DROP FOREIGN KEY FK_A94BA5797DB780F8');
        $this->addSql('ALTER TABLE ParsedCDRs ADD CONSTRAINT ParsedCDRs_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ParsedCDRs ADD CONSTRAINT ParsedCDRs_ibfk_2 FOREIGN KEY (companyId) REFERENCES Companies (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ParsedCDRs ADD CONSTRAINT parsedCDRs_ibfk_6 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE PeerServers DROP FOREIGN KEY FK_C12DE2EF7DB780F8');
        $this->addSql('ALTER TABLE PeerServers DROP FOREIGN KEY FK_C12DE2EF9CBEC244');
        $this->addSql('ALTER TABLE PeerServers ADD CONSTRAINT PeerServers_ibfk_1 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PeerServers ADD CONSTRAINT PeerServers_ibfk_2 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PeeringContracts DROP FOREIGN KEY FK_6E479B029CBEC244');
        $this->addSql('ALTER TABLE PeeringContracts DROP FOREIGN KEY FK_6E479B022D92AF39');
        $this->addSql('ALTER TABLE PeeringContracts ADD CONSTRAINT PeeringContracts_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PeeringContracts ADD CONSTRAINT PeeringContracts_ibfk_2 FOREIGN KEY (transformationRulesetGroupsTrunksId) REFERENCES TransformationRulesetGroupsTrunks (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE PickUpGroups DROP FOREIGN KEY FK_3F7C24B82480E723');
        $this->addSql('ALTER TABLE PickUpGroups ADD CONSTRAINT PickUpGroups_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PickUpRelUsers DROP FOREIGN KEY FK_5EAA6699CB8F98DA');
        $this->addSql('ALTER TABLE PickUpRelUsers DROP FOREIGN KEY FK_5EAA669964B64DCC');
        $this->addSql('ALTER TABLE PickUpRelUsers ADD CONSTRAINT PickUpRelUsers_ibfk_1 FOREIGN KEY (pickUpGroupId) REFERENCES PickUpGroups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PickUpRelUsers ADD CONSTRAINT PickUpRelUsers_ibfk_2 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlans DROP FOREIGN KEY FK_9AA416889CBEC244');
        $this->addSql('ALTER TABLE PricingPlans ADD CONSTRAINT PricingPlans_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies DROP FOREIGN KEY FK_78F195D2EDF37044');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies DROP FOREIGN KEY FK_78F195D22480E723');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies DROP FOREIGN KEY FK_78F195D29CBEC244');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies ADD CONSTRAINT PricingPlansRelCompanies_ibfk_1 FOREIGN KEY (pricingPlanId) REFERENCES PricingPlans (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies ADD CONSTRAINT PricingPlansRelCompanies_ibfk_2 FOREIGN KEY (companyId) REFERENCES Companies (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlansRelCompanies ADD CONSTRAINT PricingPlansRelCompanies_ibfk_3 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns DROP FOREIGN KEY FK_CAD1B6B5EDF37044');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns DROP FOREIGN KEY FK_CAD1B6B54D2CFC16');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns DROP FOREIGN KEY FK_CAD1B6B59CBEC244');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns ADD CONSTRAINT PricingPlansRelTargetPatterns_ibfk_1 FOREIGN KEY (pricingPlanId) REFERENCES PricingPlans (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns ADD CONSTRAINT PricingPlansRelTargetPatterns_ibfk_2 FOREIGN KEY (targetPatternId) REFERENCES TargetPatterns (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PricingPlansRelTargetPatterns ADD CONSTRAINT PricingPlansRelTargetPatterns_ibfk_3 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE QueueMembers DROP FOREIGN KEY FK_51FEFDD1A4D768C6');
        $this->addSql('ALTER TABLE QueueMembers DROP FOREIGN KEY FK_51FEFDD164B64DCC');
        $this->addSql('ALTER TABLE QueueMembers ADD CONSTRAINT QueueMembers_ibfk_1 FOREIGN KEY (queueId) REFERENCES Queues (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE QueueMembers ADD CONSTRAINT QueueMembers_ibfk_2 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A02480E723');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A02CAE121C');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A0FE276E1B');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A0535464FB');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A07030598F');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A0DC78ACAF');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A09F7A4CAC');
        $this->addSql('ALTER TABLE Queues DROP FOREIGN KEY FK_C86607A08961FE7B');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_2 FOREIGN KEY (periodicAnnounceLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_3 FOREIGN KEY (timeoutLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_4 FOREIGN KEY (timeoutExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_5 FOREIGN KEY (timeoutVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_6 FOREIGN KEY (fullLocutionId) REFERENCES Locutions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_7 FOREIGN KEY (fullExtensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Queues ADD CONSTRAINT Queues_ibfk_8 FOREIGN KEY (fullVoiceMailUserId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Recordings DROP FOREIGN KEY FK_A68A9FBE2480E723');
        $this->addSql('ALTER TABLE Recordings ADD CONSTRAINT Recordings_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY FK_732D92509CBEC244');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY FK_732D92502480E723');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY FK_732D9250FBA2A6B4');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY FK_732D9250C8F2AA6B');
        $this->addSql('ALTER TABLE RetailAccounts DROP FOREIGN KEY FK_732D9250940D8C7E');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT RetailAccounts_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT RetailAccounts_ibfk_2 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT RetailAccounts_ibfk_3 FOREIGN KEY (countryId) REFERENCES Countries (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT RetailAccounts_ibfk_4 FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE RetailAccounts ADD CONSTRAINT RetailAccounts_ibfk_5 FOREIGN KEY (languageId) REFERENCES Languages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE RoutingPatternGroups DROP FOREIGN KEY FK_CE50E62B9CBEC244');
        $this->addSql('ALTER TABLE RoutingPatternGroups ADD CONSTRAINT RoutingPatternGroups_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns DROP FOREIGN KEY FK_C90A69B46D661974');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns DROP FOREIGN KEY FK_C90A69B486CE18CB');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns ADD CONSTRAINT RoutingPatternGroupsRelPatterns_ibfk_1 FOREIGN KEY (routingPatternId) REFERENCES RoutingPatterns (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE RoutingPatternGroupsRelPatterns ADD CONSTRAINT RoutingPatternGroupsRelPatterns_ibfk_2 FOREIGN KEY (routingPatternGroupId) REFERENCES RoutingPatternGroups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE RoutingPatterns DROP FOREIGN KEY FK_FA5E087B9CBEC244');
        $this->addSql('ALTER TABLE RoutingPatterns ADD CONSTRAINT RoutingPatterns_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Schedules DROP FOREIGN KEY FK_B3CA5E2D2480E723');
        $this->addSql('ALTER TABLE Schedules ADD CONSTRAINT Schedules_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE TargetPatterns DROP FOREIGN KEY FK_9A9F9F489CBEC244');
        $this->addSql('ALTER TABLE TargetPatterns ADD CONSTRAINT TargetPatterns_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE TerminalModels DROP FOREIGN KEY FK_144DF7FCCFFDBE50');
        $this->addSql('ALTER TABLE TerminalModels ADD CONSTRAINT TerminalModels_ibfk_1 FOREIGN KEY (TerminalManufacturerId) REFERENCES TerminalManufacturers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Terminals DROP FOREIGN KEY FK_98AB47BB2480E723');
        $this->addSql('ALTER TABLE Terminals DROP FOREIGN KEY FK_98AB47BB96B6775');
        $this->addSql('ALTER TABLE Terminals ADD CONSTRAINT Terminals_CompanyId_ibfk_2 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Terminals ADD CONSTRAINT Terminals_ibfk_1 FOREIGN KEY (TerminalModelId) REFERENCES TerminalModels (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Timezones DROP FOREIGN KEY FK_F7A34AFDFBA2A6B4');
        $this->addSql('ALTER TABLE Timezones ADD CONSTRAINT Timezones_ibfk_2 FOREIGN KEY (countryId) REFERENCES Countries (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks DROP FOREIGN KEY FK_F2AD690C9CBEC244');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks DROP FOREIGN KEY FK_F2AD690CFBA2A6B4');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks ADD CONSTRAINT TransformationRulesetGroupsTrunks_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE TransformationRulesetGroupsTrunks ADD CONSTRAINT TransformationRulesetGroupsTrunks_ibfk_2 FOREIGN KEY (countryId) REFERENCES Countries (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AED2480E723');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AED525043D9');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AEDB5FEF91D');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AEDFBA2A6B4');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AED940D8C7E');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AEDAE025626');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AED12AB7F65');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AED31D2BA8E');
        $this->addSql('ALTER TABLE Users DROP FOREIGN KEY FK_D5428AEDC8F2AA6B');
        $this->addSql('ALTER TABLE Users CHANGE maxCalls maxCalls SMALLINT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_10 FOREIGN KEY (callACLId) REFERENCES CallACL (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_11 FOREIGN KEY (bossAssistantId) REFERENCES Users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_12 FOREIGN KEY (countryId) REFERENCES Countries (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_13 FOREIGN KEY (languageId) REFERENCES Languages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_3 FOREIGN KEY (terminalId) REFERENCES Terminals (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_7 FOREIGN KEY (extensionId) REFERENCES Extensions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_8 FOREIGN KEY (timezoneId) REFERENCES Timezones (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Users ADD CONSTRAINT Users_ibfk_9 FOREIGN KEY (outgoingDDIId) REFERENCES DDIs (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ast_ps_aors ADD CONSTRAINT ast_ps_aors_ibfk_1 FOREIGN KEY (id) REFERENCES ast_ps_endpoints (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY FK_800B6051AE025626');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY FK_800B6051893BA339');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY FK_800B60515EA9D64D');
        $this->addSql('ALTER TABLE ast_ps_endpoints DROP FOREIGN KEY FK_800B60515EA9D64D');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT ast_ps_endpoints_ibfk_1 FOREIGN KEY (terminalId) REFERENCES Terminals (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT ast_ps_endpoints_ibfk_2 FOREIGN KEY (friendId) REFERENCES Friends (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT ast_ps_endpoints_ibfk_3 FOREIGN KEY (retailAccountId) REFERENCES RetailAccounts (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_800b60515ea9d64d ON ast_ps_endpoints');
        $this->addSql('CREATE INDEX retailAccountId ON ast_ps_endpoints (retailAccountId)');
        $this->addSql('ALTER TABLE ast_ps_endpoints ADD CONSTRAINT FK_800B60515EA9D64D FOREIGN KEY (retailAccountId) REFERENCES RetailAccounts (id)');
        $this->addSql('ALTER TABLE ast_queue_members DROP FOREIGN KEY FK_9EEBA5FCFF8FC3FF');
        $this->addSql('ALTER TABLE ast_queue_members ADD CONSTRAINT ast_queue_members_ibfk_1 FOREIGN KEY (queueMemberId) REFERENCES QueueMembers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ast_queues DROP FOREIGN KEY FK_970E5D29A4D768C6');
        $this->addSql('ALTER TABLE ast_queues ADD CONSTRAINT ast_queues_ibfk_1 FOREIGN KEY (queueId) REFERENCES Queues (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ast_voicemail DROP FOREIGN KEY FK_B2AD1D0A64B64DCC');
        $this->addSql('ALTER TABLE ast_voicemail ADD CONSTRAINT ast_voicemail_ibfk_1 FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY FK_1AC995A6EDF37044');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY FK_1AC995A64D2CFC16');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY FK_1AC995A63D7BDC51');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY FK_1AC995A69CBEC244');
        $this->addSql('ALTER TABLE kam_acc_cdrs DROP FOREIGN KEY FK_1AC995A62480E723');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT kam_acc_cdrs_ibfk_1 FOREIGN KEY (pricingPlanId) REFERENCES PricingPlans (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT kam_acc_cdrs_ibfk_2 FOREIGN KEY (targetPatternId) REFERENCES TargetPatterns (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT kam_acc_cdrs_ibfk_3 FOREIGN KEY (invoiceId) REFERENCES Invoices (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT kam_acc_cdrs_ibfk_4 FOREIGN KEY (companyId) REFERENCES Companies (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_acc_cdrs ADD CONSTRAINT kam_acc_cdrs_ibfk_5 FOREIGN KEY (brandId) REFERENCES Brands (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_dispatcher DROP FOREIGN KEY FK_7CD78806F862FFE7');
        $this->addSql('ALTER TABLE kam_dispatcher ADD CONSTRAINT kam_dispatcher_ibfk_1 FOREIGN KEY (applicationServerId) REFERENCES ApplicationServers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_rtpproxy DROP FOREIGN KEY FK_729D1741C8555117');
        $this->addSql('ALTER TABLE kam_rtpproxy ADD CONSTRAINT kam_rtpproxy_ibfk_1 FOREIGN KEY (mediaRelaySetsId) REFERENCES MediaRelaySets (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_trunks_dialplan DROP FOREIGN KEY FK_3F0091CF2D92AF39');
        $this->addSql('ALTER TABLE kam_trunks_dialplan ADD CONSTRAINT kam_trunks_dialplan_ibfk_2 FOREIGN KEY (transformationRulesetGroupsTrunksId) REFERENCES TransformationRulesetGroupsTrunks (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_trunks_uacreg DROP FOREIGN KEY FK_C61278219CBEC244');
        $this->addSql('ALTER TABLE kam_trunks_uacreg DROP FOREIGN KEY FK_C61278217DB780F8');
        $this->addSql('ALTER TABLE kam_trunks_uacreg ADD CONSTRAINT kam_trunks_uacreg_ibfk_1 FOREIGN KEY (brandId) REFERENCES Brands (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_trunks_uacreg ADD CONSTRAINT kam_trunks_uacreg_ibfk_2 FOREIGN KEY (peeringContractId) REFERENCES PeeringContracts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_users_address DROP FOREIGN KEY FK_A53CBBF22480E723');
        $this->addSql('ALTER TABLE kam_users_address ADD CONSTRAINT kam_users_address_ibfk_1 FOREIGN KEY (companyId) REFERENCES Companies (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kam_users_domain_attrs DROP FOREIGN KEY FK_F444738D4E7FCF41');
        $this->addSql('ALTER TABLE kam_users_domain_attrs ADD CONSTRAINT kam_users_domain_attrs_ibfk_1 FOREIGN KEY (did) REFERENCES Domains (domain) ON UPDATE CASCADE ON DELETE CASCADE');
    }
}
