<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\AccCdr\AccCdrRepository;

/**
 * AccCdrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccCdrDoctrineRepository extends EntityRepository implements AccCdrRepository
{
}
