<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\Dispatcher\DispatcherRepository;

/**
 * DispatcherDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispatcherDoctrineRepository extends EntityRepository implements DispatcherRepository
{
}
