<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamDispatcher\KamDispatcherRepository;

/**
 * KamDispatcherDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamDispatcherDoctrineRepository extends EntityRepository implements KamDispatcherRepository
{
}
