<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamPikeTrusted\KamPikeTrustedRepository;

/**
 * KamPikeTrustedDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamPikeTrustedDoctrineRepository extends EntityRepository implements KamPikeTrustedRepository
{
}
