<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamUsersAddres\KamUsersAddresRepository;

/**
 * KamUsersAddresDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersAddresDoctrineRepository extends EntityRepository implements KamUsersAddresRepository
{
}
