<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamUsersHtable\KamUsersHtableRepository;

/**
 * KamUsersHtableDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersHtableDoctrineRepository extends EntityRepository implements KamUsersHtableRepository
{
}
