<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamUsersPua\KamUsersPuaRepository;

/**
 * KamUsersPuaDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersPuaDoctrineRepository extends EntityRepository implements KamUsersPuaRepository
{
}
