<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamUsersActiveWatcher\KamUsersActiveWatcherRepository;

/**
 * KamUsersActiveWatcherDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersActiveWatcherDoctrineRepository extends EntityRepository implements KamUsersActiveWatcherRepository
{
}
