<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\KamUsersXcap\KamUsersXcapRepository;

/**
 * KamUsersXcapDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersXcapDoctrineRepository extends EntityRepository implements KamUsersXcapRepository
{
}
