<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\PikeTrusted\PikeTrustedRepository;

/**
 * PikeTrustedDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PikeTrustedDoctrineRepository extends EntityRepository implements PikeTrustedRepository
{
}
