<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\Rtpproxy\RtpproxyRepository;

/**
 * RtpproxyDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RtpproxyDoctrineRepository extends EntityRepository implements RtpproxyRepository
{
}
