<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\TrunksAddres\TrunksAddresRepository;

/**
 * TrunksAddresDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrunksAddresDoctrineRepository extends EntityRepository implements TrunksAddresRepository
{
}
