<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\TrunksUacreg\TrunksUacregRepository;

/**
 * TrunksUacregDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrunksUacregDoctrineRepository extends EntityRepository implements TrunksUacregRepository
{
}
