<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\KamTrunksAcc\KamTrunksAccRepository;

/**
 * KamTrunksAccDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrunksAccDoctrineRepository extends EntityRepository implements TrunksAccRepository
{
}
