<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\TrunksDomainAttr\TrunksDomainAttrRepository;

/**
 * TrunksDomainAttrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrunksDomainAttrDoctrineRepository extends EntityRepository implements TrunksDomainAttrRepository
{
}
