<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersWatcher\UsersWatcherRepository;

/**
 * UsersWatcherDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersWatcherDoctrineRepository extends EntityRepository implements UsersWatcherRepository
{
}
