<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersAddres\UsersAddresRepository;

/**
 * UsersAddresDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAddresDoctrineRepository extends EntityRepository implements UsersAddresRepository
{
}
