<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersMissedCall\UsersMissedCallRepository;

/**
 * UsersMissedCallDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersMissedCallDoctrineRepository extends EntityRepository implements UsersMissedCallRepository
{
}
