<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\UsersPua\UsersPuaRepository;

/**
 * UsersPuaDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersPuaDoctrineRepository extends EntityRepository implements UsersPuaRepository
{
}
