<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersActiveWatcher\UsersActiveWatcherRepository;

/**
 * UsersActiveWatcherDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersActiveWatcherDoctrineRepository extends EntityRepository implements UsersActiveWatcherRepository
{
}
