<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersPresentity\UsersPresentityRepository;

/**
 * UsersPresentityDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersPresentityDoctrineRepository extends EntityRepository implements UsersPresentityRepository
{
}
