<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersHtable\UsersHtableRepository;

/**
 * UsersHtableDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersHtableDoctrineRepository extends EntityRepository implements UsersHtableRepository
{
}
