<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersDomainAttr\UsersDomainAttrRepository;

/**
 * UsersDomainAttrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersDomainAttrDoctrineRepository extends EntityRepository implements UsersDomainAttrRepository
{
}
