<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Model\UsersXcap\UsersXcapRepository;

/**
 * UsersXcapDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersXcapDoctrineRepository extends EntityRepository implements UsersXcapRepository
{
}
