<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\UsersAcc\UsersAccRepository;

/**
 * UsersAccDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAccDoctrineRepository extends EntityRepository implements UsersAccRepository
{
}
