<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\UsersLocationAttr\UsersLocationAttrRepository;

/**
 * UsersLocationAttrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersLocationAttrDoctrineRepository extends EntityRepository implements UsersLocationAttrRepository
{
}
