# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: "@ZfBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }

parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: CoreBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
