<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\AstPsEndpoint\AstPsEndpointRepository;

/**
 * AstPsEndpointDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstPsEndpointDoctrineRepository extends EntityRepository implements AstPsEndpointRepository
{
}
