<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\AstVoicemail\AstVoicemailRepository;

/**
 * AstVoicemailDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstVoicemailDoctrineRepository extends EntityRepository implements AstVoicemailRepository
{
}
