<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\BrandOperator\BrandOperatorRepository;

/**
 * BrandOperatorDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandOperatorDoctrineRepository extends EntityRepository implements BrandOperatorRepository
{
}
