<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\BrandURL\BrandURLRepository;

/**
 * BrandURLDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandURLDoctrineRepository extends EntityRepository implements BrandURLRepository
{
}
