<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\CallACL\CallACLRepository;

/**
 * CallACLDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallACLDoctrineRepository extends EntityRepository implements CallACLRepository
{
}
