<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\CallACLRelPattern\CallACLRelPatternRepository;

/**
 * CallACLRelPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallACLRelPatternDoctrineRepository extends EntityRepository implements CallACLRelPatternRepository
{
}
