<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\Changelog\ChangelogRepository;

/**
 * ChangelogDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangelogDoctrineRepository extends EntityRepository implements ChangelogRepository
{
}
