<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\CompanyAdmin\CompanyAdminRepository;

/**
 * CompanyAdminDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyAdminDoctrineRepository extends EntityRepository implements CompanyAdminRepository
{
}
