<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\DDI\DDIRepository;

/**
 * DDIDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DDIDoctrineRepository extends EntityRepository implements DDIRepository
{
}
