<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\EtagVersion\EtagVersionRepository;

/**
 * EtagVersionDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtagVersionDoctrineRepository extends EntityRepository implements EtagVersionRepository
{
}
