<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\Extension\ExtensionRepository;

/**
 * ExtensionDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionDoctrineRepository extends EntityRepository implements ExtensionRepository
{
}
