<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendarRepository;

/**
 * ExternalCallFilterRelCalendarDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalCallFilterRelCalendarDoctrineRepository extends EntityRepository implements ExternalCallFilterRelCalendarRepository
{
}
