<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\ExternalCallFilter\ExternalCallFilterRepository;

/**
 * ExternalCallFilterDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalCallFilterDoctrineRepository extends EntityRepository implements ExternalCallFilterRepository
{
}
