<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\FeaturesRelBrand\FeaturesRelBrandRepository;

/**
 * FeaturesRelBrandDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturesRelBrandDoctrineRepository extends EntityRepository implements FeaturesRelBrandRepository
{
}
