<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\FeaturesRelCompany\FeaturesRelCompanyRepository;

/**
 * FeaturesRelCompanyDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturesRelCompanyDoctrineRepository extends EntityRepository implements FeaturesRelCompanyRepository
{
}
