<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\GenericCallACLPattern\GenericCallACLPatternRepository;

/**
 * GenericCallACLPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenericCallACLPatternDoctrineRepository extends EntityRepository implements GenericCallACLPatternRepository
{
}
