<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\HolidayDate\HolidayDateRepository;

/**
 * HolidayDateDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayDateDoctrineRepository extends EntityRepository implements HolidayDateRepository
{
}
