<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUserRepository;

/**
 * HuntGroupsRelUserDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HuntGroupsRelUserDoctrineRepository extends EntityRepository implements HuntGroupsRelUserRepository
{
}
