<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\IVRCustom\IVRCustomRepository;

/**
 * IVRCustomDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IVRCustomDoctrineRepository extends EntityRepository implements IVRCustomRepository
{
}
