<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\IVRCustomEntry\IVRCustomEntryRepository;

/**
 * IVRCustomEntryDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IVRCustomEntryDoctrineRepository extends EntityRepository implements IVRCustomEntryRepository
{
}
