<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamAccCdr\KamAccCdrRepository;

/**
 * KamAccCdrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamAccCdrDoctrineRepository extends EntityRepository implements KamAccCdrRepository
{
}
