<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamRtpproxy\KamRtpproxyRepository;

/**
 * KamRtpproxyDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamRtpproxyDoctrineRepository extends EntityRepository implements KamRtpproxyRepository
{
}
