<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamTrunksAcc\KamTrunksAccRepository;

/**
 * KamTrunksAccDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamTrunksAccDoctrineRepository extends EntityRepository implements KamTrunksAccRepository
{
}
