<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamTrunksDialplan\KamTrunksDialplanRepository;

/**
 * KamTrunksDialplanDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamTrunksDialplanDoctrineRepository extends EntityRepository implements KamTrunksDialplanRepository
{
}
