<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamTrunksDomainAttr\KamTrunksDomainAttrRepository;

/**
 * KamTrunksDomainAttrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamTrunksDomainAttrDoctrineRepository extends EntityRepository implements KamTrunksDomainAttrRepository
{
}
