<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamTrunksHtable\KamTrunksHtableRepository;

/**
 * KamTrunksHtableDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamTrunksHtableDoctrineRepository extends EntityRepository implements KamTrunksHtableRepository
{
}
