<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamTrunksAddres\KamTrunksAddresRepository;

/**
 * KamTrunksAddresDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamTrunksAddresDoctrineRepository extends EntityRepository implements KamTrunksAddresRepository
{
}
