<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamUsersDomainAttr\KamUsersDomainAttrRepository;

/**
 * KamUsersDomainAttrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersDomainAttrDoctrineRepository extends EntityRepository implements KamUsersDomainAttrRepository
{
}
