<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamUsersMissedCall\KamUsersMissedCallRepository;

/**
 * KamUsersMissedCallDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersMissedCallDoctrineRepository extends EntityRepository implements KamUsersMissedCallRepository
{
}
