<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\KamUsersLocationAttr\KamUsersLocationAttrRepository;

/**
 * KamUsersLocationAttrDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamUsersLocationAttrDoctrineRepository extends EntityRepository implements KamUsersLocationAttrRepository
{
}
