<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\LcrGateway\LcrGatewayRepository;

/**
 * LcrGatewayDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LcrGatewayDoctrineRepository extends EntityRepository implements LcrGatewayRepository
{
}
