<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\MediaRelaySet\MediaRelaySetRepository;

/**
 * MediaRelaySetDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRelaySetDoctrineRepository extends EntityRepository implements MediaRelaySetRepository
{
}
