<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\MusicOnHold\MusicOnHoldRepository;

/**
 * MusicOnHoldDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicOnHoldDoctrineRepository extends EntityRepository implements MusicOnHoldRepository
{
}
