<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\OutgoingRouting\OutgoingRoutingRepository;

/**
 * OutgoingRoutingDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutgoingRoutingDoctrineRepository extends EntityRepository implements OutgoingRoutingRepository
{
}
