<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\PeerServer\PeerServerRepository;

/**
 * PeerServerDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeerServerDoctrineRepository extends EntityRepository implements PeerServerRepository
{
}
