<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\PricingPlansRelCompany\PricingPlansRelCompanyRepository;

/**
 * PricingPlansRelCompanyDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingPlansRelCompanyDoctrineRepository extends EntityRepository implements PricingPlansRelCompanyRepository
{
}
