<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\ProxyTrunk\ProxyTrunkRepository;

/**
 * ProxyTrunkDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyTrunkDoctrineRepository extends EntityRepository implements ProxyTrunkRepository
{
}
