<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\Recording\RecordingRepository;

/**
 * RecordingDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingDoctrineRepository extends EntityRepository implements RecordingRepository
{
}
