<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\RoutingPatternGroup\RoutingPatternGroupRepository;

/**
 * RoutingPatternGroupDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutingPatternGroupDoctrineRepository extends EntityRepository implements RoutingPatternGroupRepository
{
}
