<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\RoutingPattern\RoutingPatternRepository;

/**
 * RoutingPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutingPatternDoctrineRepository extends EntityRepository implements RoutingPatternRepository
{
}
