<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPatternRepository;

/**
 * RoutingPatternGroupsRelPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutingPatternGroupsRelPatternDoctrineRepository extends EntityRepository implements RoutingPatternGroupsRelPatternRepository
{
}
