<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\TargetPattern\TargetPatternRepository;

/**
 * TargetPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetPatternDoctrineRepository extends EntityRepository implements TargetPatternRepository
{
}
