<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\Terminal\TerminalRepository;

/**
 * TerminalDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminalDoctrineRepository extends EntityRepository implements TerminalRepository
{
}
