<?php

namespace Core\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Core\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunkRepository;

/**
 * TransformationRulesetGroupsTrunkDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransformationRulesetGroupsTrunkDoctrineRepository extends EntityRepository implements TransformationRulesetGroupsTrunkRepository
{
}
