Core\Model\KamDispatcher\KamDispatcher:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\KamDispatcherDoctrineRepository
  type: entity
  table: kam_dispatcher
  indexes:
    applicationServerId:
      columns:
        - applicationServerId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    setid:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    destination:
      type: string
      nullable: false
      length: 192
      options:
        fixed: false
        default: ''
    flags:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    priority:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '0'
    attrs:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
        default: ''
    description:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: ''
  manyToOne:
    applicationServer:
      targetEntity: \Core\Model\ApplicationServer\ApplicationServer
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        applicationServerId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
