Core\Model\KamRtpproxy\KamRtpproxy:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\KamRtpproxyDoctrineRepository
  type: entity
  table: kam_rtpproxy
  indexes:
    mediaRelaySetsId:
      columns:
        - mediaRelaySetsId
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    setid:
      type: string
      nullable: false
      length: 32
      options:
        fixed: false
        default: '0'
    url:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
    flags:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '0'
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: '1'
    description:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
  manyToOne:
    mediaRelaySet:
      targetEntity: \Core\Model\MediaRelaySet\MediaRelaySet
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        mediaRelaySetsId:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
