Core\Model\KamUsersWatcher\KamUsersWatcher:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\KamUsersWatcherDoctrineRepository
  type: entity
  table: kam_users_watchers
  uniqueConstraints:
    kam_users_watchers_idx:
      columns:
        - presentity_uri
        - watcher_username
        - watcher_domain
        - event
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    presentityUri:
      type: string
      nullable: false
      length: 128
      options:
        fixed: false
      column: presentity_uri
    watcherUsername:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
      column: watcher_username
    watcherDomain:
      type: string
      nullable: false
      length: 190
      options:
        fixed: false
      column: watcher_domain
    event:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: presence
    status:
      type: integer
      nullable: false
      options:
        unsigned: false
    reason:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    insertedTime:
      type: integer
      nullable: false
      options:
        unsigned: false
      column: inserted_time
  lifecycleCallbacks: {  }
