Core\Model\PricingPlansRelCompany\PricingPlansRelCompany:
  repositoryClass: Core\Infrastructure\Persistence\Doctrine\PricingPlansRelCompanyDoctrineRepository
  type: entity
  table: PricingPlansRelCompanies
  indexes:
    brandId:
      columns:
        - brandId
    IDX_78F195D2EDF37044:
      columns:
        - pricingPlanId
    IDX_78F195D22480E723:
      columns:
        - companyId
  uniqueConstraints:
    pricingPlanIdCompanyId:
      columns:
        - pricingPlanId
        - companyId
    metricCompanyId:
      columns:
        - companyId
        - metric
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    validFrom:
      type: datetime
      nullable: false
      column: validFrom
    validTo:
      type: datetime
      nullable: false
      column: validTo
    metric:
      type: integer
      nullable: false
      options:
        unsigned: false
        default: '10'
  manyToOne:
    pricingPlan:
      targetEntity: \Core\Model\PricingPlan\PricingPlan
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        pricingPlanId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    company:
      targetEntity: \Core\Model\Company\Company
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
    brand:
      targetEntity: \Core\Model\Brand\Brand
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
