#!/bin/bash
if [[ $0 == /* ]]; then
    BASEDIR=`dirname $0`       # Absolute
else
    BASEDIR=`dirname $PWD/$0`  # Relative
fi

/usr/bin/php ${BASEDIR}/../library/vendor/bin/phing  \
-f build_dev.xml $1 \
-De=localdev \
-Dk=/opt/irontec/ivozprovider/library/vendor \
-Da=/opt/irontec/ivozprovider/portals/application
