<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ApplicationServer\ApplicationServerRepository;

/**
 * ApplicationServerDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationServerDoctrineRepository extends EntityRepository implements ApplicationServerRepository
{
}
