<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\BrandURL\BrandURLRepository;

/**
 * BrandURLDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandURLDoctrineRepository extends EntityRepository implements BrandURLRepository
{
}
