<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\BrandService\BrandServiceRepository;

/**
 * BrandServiceDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandServiceDoctrineRepository extends EntityRepository implements BrandServiceRepository
{
}
