<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\CallForwardSetting\CallForwardSettingRepository;

/**
 * CallForwardSettingDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallForwardSettingDoctrineRepository extends EntityRepository implements CallForwardSettingRepository
{
}
