<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ChangeHistory\ChangeHistoryRepository;

/**
 * ChangeHistoryDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeHistoryDoctrineRepository extends EntityRepository implements ChangeHistoryRepository
{
}
