<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\CompanyService\CompanyServiceRepository;

/**
 * CompanyServiceDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyServiceDoctrineRepository extends EntityRepository implements CompanyServiceRepository
{
}
