<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelScheduleRepository;

/**
 * ExternalCallFilterRelScheduleDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalCallFilterRelScheduleDoctrineRepository extends EntityRepository implements ExternalCallFilterRelScheduleRepository
{
}
