<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\FaxesInOut\FaxesInOutRepository;

/**
 * FaxesInOutDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaxesInOutDoctrineRepository extends EntityRepository implements FaxesInOutRepository
{
}
