<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\FriendsPattern\FriendsPatternRepository;

/**
 * FriendsPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsPatternDoctrineRepository extends EntityRepository implements FriendsPatternRepository
{
}
