<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\GenericMusicOnHold\GenericMusicOnHoldRepository;

/**
 * GenericMusicOnHoldDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenericMusicOnHoldDoctrineRepository extends EntityRepository implements GenericMusicOnHoldRepository
{
}
