<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\HuntGroup\HuntGroupRepository;

/**
 * HuntGroupDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HuntGroupDoctrineRepository extends EntityRepository implements HuntGroupRepository
{
}
