<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\InvoiceTemplate\InvoiceTemplateRepository;

/**
 * InvoiceTemplateDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceTemplateDoctrineRepository extends EntityRepository implements InvoiceTemplateRepository
{
}
