<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\LcrRuleTarget\LcrRuleTargetRepository;

/**
 * LcrRuleTargetDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LcrRuleTargetDoctrineRepository extends EntityRepository implements LcrRuleTargetRepository
{
}
