<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\Locution\LocutionRepository;

/**
 * LocutionDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocutionDoctrineRepository extends EntityRepository implements LocutionRepository
{
}
