<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\MainOperator\MainOperatorRepository;

/**
 * MainOperatorDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainOperatorDoctrineRepository extends EntityRepository implements MainOperatorRepository
{
}
