<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\MediaRelaySet\MediaRelaySetRepository;

/**
 * MediaRelaySetDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRelaySetDoctrineRepository extends EntityRepository implements MediaRelaySetRepository
{
}
