<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\OutgoingRouting\OutgoingRoutingRepository;

/**
 * OutgoingRoutingDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutgoingRoutingDoctrineRepository extends EntityRepository implements OutgoingRoutingRepository
{
}
