<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ParsedCDR\ParsedCDRRepository;

/**
 * ParsedCDRDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParsedCDRDoctrineRepository extends EntityRepository implements ParsedCDRRepository
{
}
