<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\PeeringContract\PeeringContractRepository;

/**
 * PeeringContractDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeeringContractDoctrineRepository extends EntityRepository implements PeeringContractRepository
{
}
