<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\PickUpRelUser\PickUpRelUserRepository;

/**
 * PickUpRelUserDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PickUpRelUserDoctrineRepository extends EntityRepository implements PickUpRelUserRepository
{
}
