<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\PickUpGroup\PickUpGroupRepository;

/**
 * PickUpGroupDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PickUpGroupDoctrineRepository extends EntityRepository implements PickUpGroupRepository
{
}
