<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\PricingPlan\PricingPlanRepository;

/**
 * PricingPlanDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingPlanDoctrineRepository extends EntityRepository implements PricingPlanRepository
{
}
