<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPatternRepository;

/**
 * PricingPlansRelTargetPatternDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingPlansRelTargetPatternDoctrineRepository extends EntityRepository implements PricingPlansRelTargetPatternRepository
{
}
