<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\TerminalModel\TerminalModelRepository;

/**
 * TerminalModelDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminalModelDoctrineRepository extends EntityRepository implements TerminalModelRepository
{
}
