<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\XMLRPCLog\XMLRPCLogRepository;

/**
 * XMLRPCLogDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XMLRPCLogDoctrineRepository extends EntityRepository implements XMLRPCLogRepository
{
}
