services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## post_persist
  ##################################
  Kam\Domain\Service\Dispatcher\UpdateByApplicationServer:
    tags:
      - { name: ivoz.lifecycle.application_server.post_persist, priority: 10}
    arguments:
      $dispatcherRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Kam\\Domain\\Model\\Dispatcher\\Dispatcher")'

  Ivoz\Domain\Service\RequestProxyTrunksDispatcherReload:
    tags:
      - { name: ivoz.lifecycle.application_server.post_persist, priority: 20 }
        ## post_remove
      - { name: ivoz.lifecycle.application_server.post_remove, priority: 20 }
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'

  Ivoz\Domain\Service\RequestProxyUsersDispatcherReload:
    tags:
      - { name: ivoz.lifecycle.application_server.post_persist, priority: 21 }
        ## post_remove
      - { name: ivoz.lifecycle.application_server.post_remove, priority: 21 }
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
