services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Brand\SanitizeEmptyValues:
    tags:
      - { name: ivoz.lifecycle.brand.pre_persist, priority: 10 }

  ##################################
  ## post_persist
  ##################################
  Ivoz\Domain\Service\Domain\UpdateByBrand:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 20 }
    arguments:
      $domainRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\Domain\\Domain")'

  Kam\Domain\Service\UsersDomainAttr\UpdateByBrand:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 30 }
    arguments:
      $usersDomainAttrRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Kam\\Domain\\Model\\UsersDomainAttr\\UsersDomainAttr")'

  Ivoz\Domain\Service\RoutingPatternGroup\UpdateByBrand:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 40 }
    arguments:
      $routingPatternGroupRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\RoutingPatternGroup\\RoutingPatternGroup")'
      $countryRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\Country\\Country")'

  Ivoz\Domain\Service\RequestProxyTrunksLcrReload:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 50 }
        ## post_remove
      - { name: ivoz.lifecycle.brand.post_remove, priority: 50 }
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'

  Ivoz\Domain\Service\RequestProxyUsersDomainReload:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 51 }
        ## post_remove
      - { name: ivoz.lifecycle.brand.post_remove, priority: 51 }
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
