imports:
  - { resource: "@CoreBundle/Resources/config/lifecycle_application_server.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle_brand.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle_brand_service.yml" }

services:
  _defaults:
    autowire: true
    public: false

  Core\Infrastructure\Model\Lifecycle\DoctrineSubscriber:
      arguments:
        - "@service_container"
      tags:
          - { name: doctrine.event_subscriber }

  Core\Infrastructure\Model\Lifecycle\HandlerChain:
    public: true

