doctrine:
  orm:
    resolve_target_entities:
      Ast\Model\Hint\HintInterface: Ast\Model\Hint\Hint
      Ast\Model\PsAor\PsAorInterface: Ast\Model\PsAor\PsAor
      Ast\Model\PsEndpoint\PsEndpointInterface: Ast\Model\PsEndpoint\PsEndpoint
      Ast\Model\QueueMember\QueueMemberInterface: Ast\Model\QueueMember\QueueMember
      Ast\Model\Queue\QueueInterface: Ast\Model\Queue\Queue
      Core\Model\ApplicationServer\ApplicationServerInterface: Core\Model\ApplicationServer\ApplicationServer
      Core\Model\BillableCall\BillableCallInterface: Core\Model\BillableCall\BillableCall
      Core\Model\Brand\BrandInterface: Core\Model\Brand\Brand
      Core\Model\BrandOperator\BrandOperatorInterface: Core\Model\BrandOperator\BrandOperator
      Core\Model\BrandService\BrandServiceInterface: Core\Model\BrandService\BrandService
      Core\Model\BrandURL\BrandURLInterface: Core\Model\BrandURL\BrandURL
      Core\Model\BrandURL\BrandURLInterface: Core\Model\BrandURL\BrandURL
      Core\Model\Calendar\CalendarInterface: Core\Model\Calendar\Calendar
      Core\Model\CallACL\CallACLInterface: Core\Model\CallACL\CallACL
      Core\Model\CallACLPattern\CallACLPatternInterface: Core\Model\CallACLPattern\CallACLPattern
      Core\Model\CallACLRelPattern\CallACLRelPatternInterface: Core\Model\CallACLRelPattern\CallACLRelPattern
      Core\Model\CallForwardSetting\CallForwardSettingInterface: Core\Model\CallForwardSetting\CallForwardSetting
      Core\Model\ChangeHistory\ChangeHistoryInterface: Core\Model\ChangeHistory\ChangeHistory
      Core\Model\Changelog\ChangelogInterface: Core\Model\Changelog\Changelog
      Core\Model\CompanyAdmin\CompanyAdminInterface: Core\Model\CompanyAdmin\CompanyAdmin
      Core\Model\Company\CompanyInterface: Core\Model\Company\Company
      Core\Model\CompanyService\CompanyServiceInterface: Core\Model\CompanyService\CompanyService
      Core\Model\ConferenceRoom\ConferenceRoomInterface: Core\Model\ConferenceRoom\ConferenceRoom
      Core\Model\Country\CountryInterface: Core\Model\Country\Country
      Core\Model\DDI\DDIInterface: Core\Model\DDI\DDI
      Core\Model\Domain\DomainInterface: Core\Model\Domain\Domain
      Core\Model\EtagVersion\EtagVersionInterface: Core\Model\EtagVersion\EtagVersion
      Core\Model\Extension\ExtensionInterface: Core\Model\Extension\Extension
      Core\Model\ExternalCallFilter\ExternalCallFilterInterface: Core\Model\ExternalCallFilter\ExternalCallFilter
      Core\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendarInterface: Core\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar
      Core\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelScheduleInterface: Core\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule
      Core\Model\FaxesInOut\FaxesInOutInterface: Core\Model\FaxesInOut\FaxesInOut
      Core\Model\Fax\FaxInterface: Core\Model\Fax\Fax
      Core\Model\Feature\FeatureInterface: Core\Model\Feature\Feature
      Core\Model\FeaturesRelBrand\FeaturesRelBrandInterface: Core\Model\FeaturesRelBrand\FeaturesRelBrand
      Core\Model\FeaturesRelCompany\FeaturesRelCompanyInterface: Core\Model\FeaturesRelCompany\FeaturesRelCompany
      Core\Model\FixedCosts\FixedCostInterface: Core\Model\FixedCosts\FixedCost
      Core\Model\FixedCostsRelInvoice\FixedCostsRelInvoiceInterface: Core\Model\FixedCostsRelInvoice\FixedCostsRelInvoice
      Core\Model\Friend\FriendInterface: Core\Model\Friend\Friend
      Core\Model\FriendsPattern\FriendsPatternInterface: Core\Model\FriendsPattern\FriendsPattern
      Core\Model\GenericCallACLPattern\GenericCallACLPatternInterface: Core\Model\GenericCallACLPattern\GenericCallACLPattern
      Core\Model\GenericMusicOnHold\GenericMusicOnHoldInterface: Core\Model\GenericMusicOnHold\GenericMusicOnHold
      Core\Model\HolidayDate\HolidayDateInterface: Core\Model\HolidayDate\HolidayDate
      Core\Model\HuntGroup\HuntGroupInterface: Core\Model\HuntGroup\HuntGroup
      Core\Model\HuntGroupRelUser\HuntGroupRelUserInterface: Core\Model\HuntGroupRelUser\HuntGroupRelUser
      Core\Model\Invoice\InvoiceInterface: Core\Model\Invoice\Invoice
      Core\Model\InvoiceTemplate\InvoiceTemplateInterface: Core\Model\InvoiceTemplate\InvoiceTemplate
      Core\Model\IVRCommon\IVRCommonInterface: Core\Model\IVRCommon\IVRCommon
      Core\Model\IVRCustomEntry\IVRCustomEntryInterface: Core\Model\IVRCustomEntry\IVRCustomEntry
      Core\Model\IVRCustom\IVRCustomInterface: Core\Model\IVRCustom\IVRCustom
      Core\Model\Language\LanguageInterface: Core\Model\Language\Language
      Core\Model\LcrGateway\LcrGatewayInterface: Core\Model\LcrGateway\LcrGateway
      Core\Model\LcrRule\LcrRuleInterface: Core\Model\LcrRule\LcrRule
      Core\Model\LcrRuleTarget\LcrRuleTargetInterface: Core\Model\LcrRuleTarget\LcrRuleTarget
      Core\Model\Locution\LocutionInterface: Core\Model\Locution\Locution
      Core\Model\MainOperator\MainOperatorInterface: Core\Model\MainOperator\MainOperator
      Core\Model\MediaRelaySet\MediaRelaySetInterface: Core\Model\MediaRelaySet\MediaRelaySet
      Core\Model\Musiconhold\MusiconholdInterface: Core\Model\Musiconhold\Musiconhold
      Core\Model\MusicOnHold\MusicOnHoldInterface: Core\Model\MusicOnHold\MusicOnHold
      Core\Model\OutgoingRouting\OutgoingRoutingInterface: Core\Model\OutgoingRouting\OutgoingRouting
      Core\Model\ParsedCDR\ParsedCDRInterface: Core\Model\ParsedCDR\ParsedCDR
      Core\Model\ParsedCDRsGod\ParsedCDRsGodInterface: Core\Model\ParsedCDRsGod\ParsedCDRsGod
      Core\Model\PeeringContract\PeeringContractInterface: Core\Model\PeeringContract\PeeringContract
      Core\Model\PeerServer\PeerServerInterface: Core\Model\PeerServer\PeerServer
      Core\Model\PickUpGroup\PickUpGroupInterface: Core\Model\PickUpGroup\PickUpGroup
      Core\Model\PickUpRelUser\PickUpRelUserInterface: Core\Model\PickUpRelUser\PickUpRelUser
      Core\Model\PricingPlan\PricingPlanInterface: Core\Model\PricingPlan\PricingPlan
      Core\Model\PricingPlansRelCompany\PricingPlanRelCompanyInterface: Core\Model\PricingPlansRelCompany\PricingPlanRelCompany
      Core\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPatternInterface: Core\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPattern
      Core\Model\ProxyTrunk\ProxyTrunkInterface: Core\Model\ProxyTrunk\ProxyTrunk
      Core\Model\ProxyUser\ProxyUserInterface: Core\Model\ProxyUser\ProxyUser
      Core\Model\QueueMember\QueueMemberInterface: Core\Model\QueueMember\QueueMember
      Core\Model\Queue\QueueInterface: Core\Model\Queue\Queue
      Core\Model\Recording\RecordingInterface: Core\Model\Recording\Recording
      Core\Model\RoutingPatternGroup\RoutingPatternGroupInterface: Core\Model\RoutingPatternGroup\RoutingPatternGroup
      Core\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPatternInterface: Core\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern
      Core\Model\RoutingPattern\RoutingPatternInterface: Core\Model\RoutingPattern\RoutingPattern
      Core\Model\Schedule\ScheduleInterface: Core\Model\Schedule\Schedule
      Core\Model\Service\ServiceInterface: Core\Model\Service\Service
      Core\Model\TargetPattern\TargetPatternInterface: Core\Model\TargetPattern\TargetPattern
      Core\Model\TerminalManufacturer\TerminalManufacturerInterface: Core\Model\TerminalManufacturer\TerminalManufacturer
      Core\Model\TerminalModel\TerminalModelInterface: Core\Model\TerminalModel\TerminalModel
      Core\Model\Terminal\TerminalInterface: Core\Model\Terminal\Terminal
      Core\Model\Timezone\TimezoneInterface: Core\Model\Timezone\Timezone
      Core\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunkInterface: Core\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunk
      Core\Model\TrunksDialplan\TrunksDialplanInterface: Core\Model\TrunksDialplan\TrunksDialplan
      Core\Model\TrunksHtable\TrunksHtableInterface: Core\Model\TrunksHtable\TrunksHtable
      Core\Model\TrunksUacreg\TrunksUacregInterface: Core\Model\TrunksUacreg\TrunksUacreg
      Core\Model\UsersAcc\UsersAccInterface: Core\Model\UsersAcc\UsersAcc
      Core\Model\UsersHtable\UsersHtableInterface: Core\Model\UsersHtable\UsersHtable
      Core\Model\UsersLocation\UsersLocationInterface: Core\Model\UsersLocation\UsersLocation
      Core\Model\User\UserInterface: Core\Model\User\User
      Core\Model\Voicemail\VoicemailInterface: Core\Model\Voicemail\Voicemail
      Core\Model\XMLRPCLog\XMLRPCLogInterface: Core\Model\XMLRPCLog\XMLRPCLog
      Kam\Model\AccCdr\AccCdrInterface: Kam\Model\AccCdr\AccCdr
      Kam\Model\AccCdrsBrand\AccCdrsBrandInterface: Kam\Model\AccCdrsBrand\AccCdrsBrand
      Kam\Model\Dispatcher\DispatcherInterface: Kam\Model\Dispatcher\Dispatcher
      Kam\Model\PikeTrusted\PikeTrustedInterface: Kam\Model\PikeTrusted\PikeTrusted
      Kam\Model\Rtpproxy\RtpproxyInterface: Kam\Model\Rtpproxy\Rtpproxy
      Kam\Model\TrunksAcc\TrunksAccInterface: Kam\Model\TrunksAcc\TrunksAcc
      Kam\Model\TrunksAddress\TrunksAddressInterface: Kam\Model\TrunksAddress\TrunksAddress
      Kam\Model\TrunksDomainAttr\TrunksDomainAttrInterface: Kam\Model\TrunksDomainAttr\TrunksDomainAttr
      Kam\Model\TrunksDomain\TrunksDomainInterface: Kam\Model\TrunksDomain\TrunksDomain
      Kam\Model\UsersAddress\UsersAddressInterface: Kam\Model\UsersAddress\UsersAddress
      Kam\Model\UsersDomainAttr\UsersDomainAttrInterface: Kam\Model\UsersDomainAttr\UsersDomainAttr
      Kam\Model\UsersDomain\UsersDomainInterface: Kam\Model\UsersDomain\UsersDomain
      Kam\Model\UsersLocationAttr\UsersLocationAttrInterface: Kam\Model\UsersLocationAttr\UsersLocationAttr
      Kam\Model\UsersMissedCalls\UsersMissedCallsInterface: Kam\Model\UsersMissedCalls\UsersMissedCalls
      Kam\Model\User\UserInterface: Kam\Model\User\User
      Kam\Model\Version\VersionInterface: Kam\Model\Version\Version