doctrine:
  orm:
    resolve_target_entities:
      Ast\Domain\Model\Hint\HintInterface: Ast\Domain\Model\Hint\Hint
      Ast\Domain\Model\PsAor\PsAorInterface: Ast\Domain\Model\PsAor\PsAor
      Ast\Domain\Model\PsEndpoint\PsEndpointInterface: Ast\Domain\Model\PsEndpoint\PsEndpoint
      Ast\Domain\Model\QueueMember\QueueMemberInterface: Ast\Domain\Model\QueueMember\QueueMember
      Ast\Domain\Model\Queue\QueueInterface: Ast\Domain\Model\Queue\Queue
      Core\Domain\Model\ApplicationServer\ApplicationServerInterface: Core\Domain\Model\ApplicationServer\ApplicationServer
      Core\Domain\Model\BillableCall\BillableCallInterface: Core\Domain\Model\BillableCall\BillableCall
      Core\Domain\Model\Brand\BrandInterface: Core\Domain\Model\Brand\Brand
      Core\Domain\Model\BrandOperator\BrandOperatorInterface: Core\Domain\Model\BrandOperator\BrandOperator
      Core\Domain\Model\BrandService\BrandServiceInterface: Core\Domain\Model\BrandService\BrandService
      Core\Domain\Model\BrandURL\BrandURLInterface: Core\Domain\Model\BrandURL\BrandURL
      Core\Domain\Model\BrandURL\BrandURLInterface: Core\Domain\Model\BrandURL\BrandURL
      Core\Domain\Model\Calendar\CalendarInterface: Core\Domain\Model\Calendar\Calendar
      Core\Domain\Model\CallACL\CallACLInterface: Core\Domain\Model\CallACL\CallACL
      Core\Domain\Model\CallACLPattern\CallACLPatternInterface: Core\Domain\Model\CallACLPattern\CallACLPattern
      Core\Domain\Model\CallACLRelPattern\CallACLRelPatternInterface: Core\Domain\Model\CallACLRelPattern\CallACLRelPattern
      Core\Domain\Model\CallForwardSetting\CallForwardSettingInterface: Core\Domain\Model\CallForwardSetting\CallForwardSetting
      Core\Domain\Model\ChangeHistory\ChangeHistoryInterface: Core\Domain\Model\ChangeHistory\ChangeHistory
      Core\Domain\Model\Changelog\ChangelogInterface: Core\Domain\Model\Changelog\Changelog
      Core\Domain\Model\CompanyAdmin\CompanyAdminInterface: Core\Domain\Model\CompanyAdmin\CompanyAdmin
      Core\Domain\Model\Company\CompanyInterface: Core\Domain\Model\Company\Company
      Core\Domain\Model\CompanyService\CompanyServiceInterface: Core\Domain\Model\CompanyService\CompanyService
      Core\Domain\Model\ConferenceRoom\ConferenceRoomInterface: Core\Domain\Model\ConferenceRoom\ConferenceRoom
      Core\Domain\Model\Country\CountryInterface: Core\Domain\Model\Country\Country
      Core\Domain\Model\DDI\DDIInterface: Core\Domain\Model\DDI\DDI
      Core\Domain\Model\Domain\DomainInterface: Core\Domain\Model\Domain\Domain
      Core\Domain\Model\EtagVersion\EtagVersionInterface: Core\Domain\Model\EtagVersion\EtagVersion
      Core\Domain\Model\Extension\ExtensionInterface: Core\Domain\Model\Extension\Extension
      Core\Domain\Model\ExternalCallFilter\ExternalCallFilterInterface: Core\Domain\Model\ExternalCallFilter\ExternalCallFilter
      Core\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendarInterface: Core\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar
      Core\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelScheduleInterface: Core\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule
      Core\Domain\Model\FaxesInOut\FaxesInOutInterface: Core\Domain\Model\FaxesInOut\FaxesInOut
      Core\Domain\Model\Fax\FaxInterface: Core\Domain\Model\Fax\Fax
      Core\Domain\Model\Feature\FeatureInterface: Core\Domain\Model\Feature\Feature
      Core\Domain\Model\FeaturesRelBrand\FeaturesRelBrandInterface: Core\Domain\Model\FeaturesRelBrand\FeaturesRelBrand
      Core\Domain\Model\FeaturesRelCompany\FeaturesRelCompanyInterface: Core\Domain\Model\FeaturesRelCompany\FeaturesRelCompany
      Core\Domain\Model\FixedCost\FixedCostInterface: Core\Domain\Model\FixedCost\FixedCost
      Core\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoiceInterface: Core\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice
      Core\Domain\Model\Friend\FriendInterface: Core\Domain\Model\Friend\Friend
      Core\Domain\Model\FriendsPattern\FriendsPatternInterface: Core\Domain\Model\FriendsPattern\FriendsPattern
      Core\Domain\Model\GenericCallACLPattern\GenericCallACLPatternInterface: Core\Domain\Model\GenericCallACLPattern\GenericCallACLPattern
      Core\Domain\Model\GenericMusicOnHold\GenericMusicOnHoldInterface: Core\Domain\Model\GenericMusicOnHold\GenericMusicOnHold
      Core\Domain\Model\HolidayDate\HolidayDateInterface: Core\Domain\Model\HolidayDate\HolidayDate
      Core\Domain\Model\HuntGroup\HuntGroupInterface: Core\Domain\Model\HuntGroup\HuntGroup
      Core\Domain\Model\HuntGroupRelUser\HuntGroupRelUserInterface: Core\Domain\Model\HuntGroupRelUser\HuntGroupRelUser
      Core\Domain\Model\Invoice\InvoiceInterface: Core\Domain\Model\Invoice\Invoice
      Core\Domain\Model\InvoiceTemplate\InvoiceTemplateInterface: Core\Domain\Model\InvoiceTemplate\InvoiceTemplate
      Core\Domain\Model\IVRCommon\IVRCommonInterface: Core\Domain\Model\IVRCommon\IVRCommon
      Core\Domain\Model\IVRCustomEntry\IVRCustomEntryInterface: Core\Domain\Model\IVRCustomEntry\IVRCustomEntry
      Core\Domain\Model\IVRCustom\IVRCustomInterface: Core\Domain\Model\IVRCustom\IVRCustom
      Core\Domain\Model\Language\LanguageInterface: Core\Domain\Model\Language\Language
      Core\Domain\Model\LcrGateway\LcrGatewayInterface: Core\Domain\Model\LcrGateway\LcrGateway
      Core\Domain\Model\LcrRule\LcrRuleInterface: Core\Domain\Model\LcrRule\LcrRule
      Core\Domain\Model\LcrRuleTarget\LcrRuleTargetInterface: Core\Domain\Model\LcrRuleTarget\LcrRuleTarget
      Core\Domain\Model\Locution\LocutionInterface: Core\Domain\Model\Locution\Locution
      Core\Domain\Model\MainOperator\MainOperatorInterface: Core\Domain\Model\MainOperator\MainOperator
      Core\Domain\Model\MediaRelaySet\MediaRelaySetInterface: Core\Domain\Model\MediaRelaySet\MediaRelaySet
      Core\Domain\Model\Musiconhold\MusiconholdInterface: Core\Domain\Model\Musiconhold\Musiconhold
      Core\Domain\Model\MusicOnHold\MusicOnHoldInterface: Core\Domain\Model\MusicOnHold\MusicOnHold
      Core\Domain\Model\OutgoingRouting\OutgoingRoutingInterface: Core\Domain\Model\OutgoingRouting\OutgoingRouting
      Core\Domain\Model\ParsedCDR\ParsedCDRInterface: Core\Domain\Model\ParsedCDR\ParsedCDR
      Core\Domain\Model\ParsedCDRsGod\ParsedCDRsGodInterface: Core\Domain\Model\ParsedCDRsGod\ParsedCDRsGod
      Core\Domain\Model\PeeringContract\PeeringContractInterface: Core\Domain\Model\PeeringContract\PeeringContract
      Core\Domain\Model\PeerServer\PeerServerInterface: Core\Domain\Model\PeerServer\PeerServer
      Core\Domain\Model\PickUpGroup\PickUpGroupInterface: Core\Domain\Model\PickUpGroup\PickUpGroup
      Core\Domain\Model\PickUpRelUser\PickUpRelUserInterface: Core\Domain\Model\PickUpRelUser\PickUpRelUser
      Core\Domain\Model\PricingPlan\PricingPlanInterface: Core\Domain\Model\PricingPlan\PricingPlan
      Core\Domain\Model\PricingPlansRelCompany\PricingPlanRelCompanyInterface: Core\Domain\Model\PricingPlansRelCompany\PricingPlanRelCompany
      Core\Domain\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPatternInterface: Core\Domain\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPattern
      Core\Domain\Model\ProxyTrunk\ProxyTrunkInterface: Core\Domain\Model\ProxyTrunk\ProxyTrunk
      Core\Domain\Model\ProxyUser\ProxyUserInterface: Core\Domain\Model\ProxyUser\ProxyUser
      Core\Domain\Model\QueueMember\QueueMemberInterface: Core\Domain\Model\QueueMember\QueueMember
      Core\Domain\Model\Queue\QueueInterface: Core\Domain\Model\Queue\Queue
      Core\Domain\Model\Recording\RecordingInterface: Core\Domain\Model\Recording\Recording
      Core\Domain\Model\RoutingPatternGroup\RoutingPatternGroupInterface: Core\Domain\Model\RoutingPatternGroup\RoutingPatternGroup
      Core\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPatternInterface: Core\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern
      Core\Domain\Model\RoutingPattern\RoutingPatternInterface: Core\Domain\Model\RoutingPattern\RoutingPattern
      Core\Domain\Model\Schedule\ScheduleInterface: Core\Domain\Model\Schedule\Schedule
      Core\Domain\Model\Service\ServiceInterface: Core\Domain\Model\Service\Service
      Core\Domain\Model\TargetPattern\TargetPatternInterface: Core\Domain\Model\TargetPattern\TargetPattern
      Core\Domain\Model\TerminalManufacturer\TerminalManufacturerInterface: Core\Domain\Model\TerminalManufacturer\TerminalManufacturer
      Core\Domain\Model\TerminalModel\TerminalModelInterface: Core\Domain\Model\TerminalModel\TerminalModel
      Core\Domain\Model\Terminal\TerminalInterface: Core\Domain\Model\Terminal\Terminal
      Core\Domain\Model\Timezone\TimezoneInterface: Core\Domain\Model\Timezone\Timezone
      Core\Domain\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunkInterface: Core\Domain\Model\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunk
      Core\Domain\Model\TrunksDialplan\TrunksDialplanInterface: Core\Domain\Model\TrunksDialplan\TrunksDialplan
      Core\Domain\Model\TrunksHtable\TrunksHtableInterface: Core\Domain\Model\TrunksHtable\TrunksHtable
      Core\Domain\Model\TrunksUacreg\TrunksUacregInterface: Core\Domain\Model\TrunksUacreg\TrunksUacreg
      Core\Domain\Model\UsersAcc\UsersAccInterface: Core\Domain\Model\UsersAcc\UsersAcc
      Core\Domain\Model\UsersHtable\UsersHtableInterface: Core\Domain\Model\UsersHtable\UsersHtable
      Core\Domain\Model\UsersLocation\UsersLocationInterface: Core\Domain\Model\UsersLocation\UsersLocation
      Core\Domain\Model\User\UserInterface: Core\Domain\Model\User\User
      Core\Domain\Model\Voicemail\VoicemailInterface: Core\Domain\Model\Voicemail\Voicemail
      Core\Domain\Model\XMLRPCLog\XMLRPCLogInterface: Core\Domain\Model\XMLRPCLog\XMLRPCLog
      Kam\Domain\Model\AccCdr\AccCdrInterface: Kam\Domain\Model\AccCdr\AccCdr
      Kam\Domain\Model\AccCdrsBrand\AccCdrsBrandInterface: Kam\Domain\Model\AccCdrsBrand\AccCdrsBrand
      Kam\Domain\Model\Dispatcher\DispatcherInterface: Kam\Domain\Model\Dispatcher\Dispatcher
      Kam\Domain\Model\PikeTrusted\PikeTrustedInterface: Kam\Domain\Model\PikeTrusted\PikeTrusted
      Kam\Domain\Model\Rtpproxy\RtpproxyInterface: Kam\Domain\Model\Rtpproxy\Rtpproxy
      Kam\Domain\Model\TrunksAcc\TrunksAccInterface: Kam\Domain\Model\TrunksAcc\TrunksAcc
      Kam\Domain\Model\TrunksAddress\TrunksAddressInterface: Kam\Domain\Model\TrunksAddress\TrunksAddress
      Kam\Domain\Model\TrunksDomainAttr\TrunksDomainAttrInterface: Kam\Domain\Model\TrunksDomainAttr\TrunksDomainAttr
      Kam\Domain\Model\TrunksDomain\TrunksDomainInterface: Kam\Domain\Model\TrunksDomain\TrunksDomain
      Kam\Domain\Model\UsersAddress\UsersAddressInterface: Kam\Domain\Model\UsersAddress\UsersAddress
      Kam\Domain\Model\UsersDomainAttr\UsersDomainAttrInterface: Kam\Domain\Model\UsersDomainAttr\UsersDomainAttr
      Kam\Domain\Model\UsersDomain\UsersDomainInterface: Kam\Domain\Model\UsersDomain\UsersDomain
      Kam\Domain\Model\UsersLocationAttr\UsersLocationAttrInterface: Kam\Domain\Model\UsersLocationAttr\UsersLocationAttr
      Kam\Domain\Model\UsersMissedCalls\UsersMissedCallsInterface: Kam\Domain\Model\UsersMissedCalls\UsersMissedCalls
      Kam\Domain\Model\User\UserInterface: Kam\Domain\Model\User\User
      Kam\Domain\Model\Version\VersionInterface: Kam\Domain\Model\Version\Version