services:

    zf.query_builder_factory:
      class: ZfBundle\Services\QueryBuilderFactory
      arguments:
            - "@doctrine.orm.entity_manager"

    zf.data_gateway:
        class: ZfBundle\Services\DataGateway
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@zf.query_builder_factory"
            - "@core.create_entity_from_dto"
            - "@core.update_entity_from_dto"